/* Future tense: grammar reference and quiz sentences.
   In table cells, [square brackets] mark the part to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const FUTURE_TENSE = {
  id: 'future', pl: 'Czas przyszły', en: 'Future tense',
  intro: 'Imperfective verbs (ongoing or repeated actions) form the future with będę plus the verb: będę czytać. Perfective verbs (one completed action) have no present tense, so their present-looking forms already mean the future: przeczytam.',
  groups: [
    {
      id: 'future-byc', pl: 'Być: będę', en: 'Future of być', q: 'Jutro będę w domu.',
      summary: 'Być is the only Polish verb with its own future forms. They mean “will be”, and they are also the building block of the compound future.',
      tables: [
        { title: 'Być in the future',
          cols: [{ label: 'Singular', tint: 'all' }, { label: 'Plural', tint: 'all' }],
          rows: [
            { who: '1st person (ja, my)', cells: ['będ[ę]', 'będzi[emy]'] },
            { who: '2nd person (ty, wy)', cells: ['będzi[esz]', 'będzi[ecie]'] },
            { who: '3rd person (on, ona, ono / oni, one)', cells: ['będzi[e]', 'będ[ą]'] },
          ] },
      ],
      rules: [
        { t: 'On its own it means “will be”', ex: 'Jutro będę w domu.', en: 'Tomorrow I will be at home.' },
        { t: 'A noun after it takes the instrumental, just as after jest', ex: 'Za rok Ania będzie lekarką.', en: 'In a year Ania will be a doctor.' },
        { t: '“Nie ma” (there is no) becomes “nie będzie”, and the noun stays in the genitive', ex: 'Jutro nie będzie chleba.', en: 'There will be no bread tomorrow.' },
      ],
      watch: [
        'Only the ja and oni forms keep the hard d: będę, będą. All the others soften it to dzi: będziesz, będzie, będziemy, będziecie.',
        'Never add być or jest after it. “Będę być” does not exist.',
        'Nouns that exist only in the plural take będą: W sobotę będą moje urodziny.',
      ],
    },
    {
      id: 'future-bede-inf', pl: 'Będę + bezokol.', en: 'Będę + infinitive', q: 'będę czytać',
      summary: 'The future of być plus the infinitive of an imperfective verb. Use it for actions that will be in progress, will last some time or will be repeated. Only będę changes, the infinitive stays the same.',
      tables: [
        { title: 'Czytać (to read) in the compound future',
          cols: [{ label: 'Singular', tint: 'all' }, { label: 'Plural', tint: 'all' }],
          rows: [
            { who: '1st person (ja, my)', cells: ['[będę] czytać', '[będziemy] czytać'] },
            { who: '2nd person (ty, wy)', cells: ['[będziesz] czytać', '[będziecie] czytać'] },
            { who: '3rd person (on, ona, ono / oni, one)', cells: ['[będzie] czytać', '[będą] czytać'] },
          ] },
      ],
      rules: [
        { t: 'An action in progress, lasting some time, or repeated', ex: 'Jutro będę pracować cały dzień.', en: 'Tomorrow I will be working all day.' },
        { t: 'Only imperfective verbs can follow będę', ex: 'Będę czytać książkę. Przeczytam książkę.', en: 'I will be reading a book. I will read the book (and finish it).' },
        { t: 'Się can go between the two words or after the verb', ex: 'Będę się uczyć polskiego. Będę uczyć się polskiego.', en: 'I will be learning Polish (both orders are correct).' },
      ],
      watch: [
        'Never put a perfective verb after będę. “Będę zrobić” and “będę napisać” are always wrong: say zrobię and napiszę.',
        'The infinitive version does not change for gender, so it is the safe choice when you are unsure.',
        'With musieć, móc and chcieć use the -ł form instead: będę musiał, not “będę musieć”.',
      ],
    },
    {
      id: 'future-bede-l', pl: 'Będę + czytał', en: 'Będę + -ł form', q: 'będę czytał / czytała',
      summary: 'The future of być plus the past-tense form of an imperfective verb, without any personal ending. It means exactly the same as będę + infinitive, but it shows gender and number. With musieć, móc and chcieć it is the only natural choice.',
      tables: [
        { title: 'Singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['będę czyta[ł]', 'będę czyta[ła]', '(not used)'] },
            { who: 'ty', cells: ['będziesz czyta[ł]', 'będziesz czyta[ła]', '(not used)'] },
            { who: 'on / ona / ono', cells: ['będzie czyta[ł]', 'będzie czyta[ła]', 'będzie czyta[ło]'] },
          ] },
        { title: 'Plural',
          cols: [{ label: 'Groups with a man', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['będziemy czyta[li]', 'będziemy czyta[ły]'] },
            { who: 'wy', cells: ['będziecie czyta[li]', 'będziecie czyta[ły]'] },
            { who: 'oni / one', cells: ['będą czyta[li]', 'będą czyta[ły]'] },
          ] },
        { title: 'Verbs whose stem changes in this form',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'musieć (to have to)', cells: ['musia[ł]', 'musia[ła]', 'musie[li]', 'musia[ły]'] },
            { who: 'móc (to be able to)', cells: ['móg[ł]', 'mog[ła]', 'mog[li]', 'mog[ły]'] },
            { who: 'chcieć (to want)', cells: ['chcia[ł]', 'chcia[ła]', 'chcie[li]', 'chcia[ły]'] },
            { who: 'mieć (to have)', cells: ['mia[ł]', 'mia[ła]', 'mie[li]', 'mia[ły]'] },
            { who: 'jeść (to eat)', cells: ['jad[ł]', 'jad[ła]', 'jed[li]', 'jad[ły]'] },
            { who: 'iść (to go)', cells: ['szed[ł]', 'sz[ła]', 'sz[li]', 'sz[ły]'] },
          ] },
      ],
      rules: [
        { t: 'The second word agrees with the subject in gender', ex: 'Marek będzie czytał. Ania będzie czytała.', en: 'Marek will be reading. Ania will be reading.' },
        { t: 'In the plural, -li for any group that includes a man, -ły for everyone else', ex: 'Chłopcy będą grali. Dziewczyny będą grały.', en: 'The boys will be playing. The girls will be playing.' },
        { t: 'With musieć, móc and chcieć, followed by another infinitive', ex: 'Jutro będę musiała wcześnie wstać.', en: 'Tomorrow I (a woman) will have to get up early.' },
      ],
      watch: [
        'Do not add the past-tense personal endings. “Będę czytałem” is wrong, because the person is already in będę.',
        'Dzieci is not a group of men, so it takes -ły: dzieci będą spały.',
        'In verbs with -eć the vowel switches: a in the singular and in -ły, e before -li. Chciał, chciała, chciały, but chcieli.',
      ],
    },
    {
      id: 'future-perf', pl: 'Dokonane: zrobię', en: 'Perfective future', q: 'zrobię, napiszę, przeczytam',
      summary: 'A perfective verb describes one completed action, so it cannot happen “right now”. Conjugate it with the ordinary present-tense endings and the meaning is future. No będę is needed or allowed.',
      tables: [
        { title: 'The same three ending patterns as the present tense',
          cols: [{ label: 'zrobić (-ę, -isz)', tint: 'all' }, { label: 'napisać (-ę, -esz)', tint: 'all' }, { label: 'przeczytać (-am, -asz)', tint: 'all' }],
          rows: [
            { who: 'ja', cells: ['zrobi[ę]', 'napisz[ę]', 'przeczyt[am]'] },
            { who: 'ty', cells: ['zrob[isz]', 'napisz[esz]', 'przeczyt[asz]'] },
            { who: 'on / ona / ono', cells: ['zrob[i]', 'napisz[e]', 'przeczyt[a]'] },
            { who: 'my', cells: ['zrob[imy]', 'napisz[emy]', 'przeczyt[amy]'] },
            { who: 'wy', cells: ['zrob[icie]', 'napisz[ecie]', 'przeczyt[acie]'] },
            { who: 'oni / one', cells: ['zrobi[ą]', 'napisz[ą]', 'przeczyt[ają]'] },
          ] },
        { title: 'Everyday pairs',
          cols: [{ label: 'Imperfective', tint: 'all' }, { label: 'Perfective', tint: 'all' }, { label: 'ja, future', tint: 'all' }, { label: 'oni, future', tint: 'all' }],
          rows: [
            { who: 'to do, to make', cells: ['robić', '[z]robić', 'zrobi[ę]', 'zrobi[ą]'] },
            { who: 'to read', cells: ['czytać', '[prze]czytać', 'przeczyt[am]', 'przeczyt[ają]'] },
            { who: 'to write', cells: ['pisać', '[na]pisać', 'napisz[ę]', 'napisz[ą]'] },
            { who: 'to buy', cells: ['kupować', 'kupić', 'kupi[ę]', 'kupi[ą]'] },
            { who: 'to see', cells: ['widzieć', 'zobaczyć', 'zobacz[ę]', 'zobacz[ą]'] },
            { who: 'to cook', cells: ['gotować', '[u]gotować', 'ugotuj[ę]', 'ugotuj[ą]'] },
            { who: 'to phone', cells: ['dzwonić', '[za]dzwonić', 'zadzwoni[ę]', 'zadzwoni[ą]'] },
            { who: 'to pay', cells: ['płacić', '[za]płacić', 'zapłac[ę]', 'zapłac[ą]'] },
            { who: 'to finish', cells: ['kończyć', '[s]kończyć', 'skończ[ę]', 'skończ[ą]'] },
            { who: 'to drink', cells: ['pić', '[wy]pić', 'wypij[ę]', 'wypij[ą]'] },
            { who: 'to tidy up', cells: ['sprzątać', '[po]sprzątać', 'posprząt[am]', 'posprząt[ają]'] },
            { who: 'to learn', cells: ['uczyć się', '[na]uczyć się', 'naucz[ę] się', 'naucz[ą] się'] },
          ] },
      ],
      rules: [
        { t: 'One action that will be completed', ex: 'Jutro zrobię zakupy.', en: 'Tomorrow I will do the shopping.' },
        { t: 'The prefix does not change the endings: conjugate the verb as you would without it', ex: 'piszę → napiszę, czytam → przeczytam', en: 'I am writing → I will write, I am reading → I will read' },
        { t: 'Verbs in -ować switch to -uj-, as in the present', ex: 'Ugotuję obiad.', en: 'I will cook dinner.' },
      ],
      watch: [
        'Never combine będę with a perfective verb. “Będę zrobić” is wrong: say zrobię.',
        'Stem changes from the present tense stay: pisać → napiszę, pokazać → pokażę, płacić → zapłacę but zapłacisz.',
        'Some pairs use different words rather than a prefix: kupować / kupić, widzieć / zobaczyć.',
      ],
    },
    {
      id: 'future-irreg', pl: 'Pójdę, wezmę', en: 'Irregular perfectives', q: 'pójdę, wezmę, dam, zjem',
      summary: 'The most common perfective verbs are also the least regular. Learn the ja form and the oni form: everything else follows from those two.',
      tables: [
        { title: 'Going and coming',
          cols: [{ label: 'pójść (go on foot)', tint: 'all' }, { label: 'pojechać (go by vehicle)', tint: 'all' }, { label: 'przyjść (come)', tint: 'all' }],
          rows: [
            { who: 'ja', cells: ['pójd[ę]', 'pojad[ę]', 'przyjd[ę]'] },
            { who: 'ty', cells: ['pójdzi[esz]', 'pojedzi[esz]', 'przyjdzi[esz]'] },
            { who: 'on / ona / ono', cells: ['pójdzi[e]', 'pojedzi[e]', 'przyjdzi[e]'] },
            { who: 'my', cells: ['pójdzi[emy]', 'pojedzi[emy]', 'przyjdzi[emy]'] },
            { who: 'wy', cells: ['pójdzi[ecie]', 'pojedzi[ecie]', 'przyjdzi[ecie]'] },
            { who: 'oni / one', cells: ['pójd[ą]', 'pojad[ą]', 'przyjd[ą]'] },
          ] },
        { title: 'Verbs in -m with a surprise in the oni form',
          cols: [{ label: 'dać (give)', tint: 'all' }, { label: 'zjeść (eat)', tint: 'all' }, { label: 'powiedzieć (say, tell)', tint: 'all' }],
          rows: [
            { who: 'ja', cells: ['da[m]', 'zje[m]', 'powie[m]'] },
            { who: 'ty', cells: ['da[sz]', 'zje[sz]', 'powie[sz]'] },
            { who: 'on / ona / ono', cells: ['da', 'zje', 'powie'] },
            { who: 'my', cells: ['da[my]', 'zje[my]', 'powie[my]'] },
            { who: 'wy', cells: ['da[cie]', 'zje[cie]', 'powie[cie]'] },
            { who: 'oni / one', cells: ['da[dzą]', 'zje[dzą]', 'powie[dzą]'] },
          ] },
        { title: 'Stems that change',
          cols: [{ label: 'wziąć (take)', tint: 'all' }, { label: 'zacząć (start)', tint: 'all' }, { label: 'pomóc (help)', tint: 'all' }, { label: 'wrócić (return)', tint: 'all' }],
          rows: [
            { who: 'ja', cells: ['wezm[ę]', 'zaczn[ę]', 'pomog[ę]', 'wróc[ę]'] },
            { who: 'ty', cells: ['weźmi[esz]', 'zaczni[esz]', 'pomoż[esz]', 'wróc[isz]'] },
            { who: 'on / ona / ono', cells: ['weźmi[e]', 'zaczni[e]', 'pomoż[e]', 'wróc[i]'] },
            { who: 'my', cells: ['weźmi[emy]', 'zaczni[emy]', 'pomoż[emy]', 'wróc[imy]'] },
            { who: 'wy', cells: ['weźmi[ecie]', 'zaczni[ecie]', 'pomoż[ecie]', 'wróc[icie]'] },
            { who: 'oni / one', cells: ['wezm[ą]', 'zaczn[ą]', 'pomog[ą]', 'wróc[ą]'] },
          ] },
        { title: 'The pairs behind them',
          cols: [{ label: 'Imperfective', tint: 'all' }, { label: 'Perfective', tint: 'all' }, { label: 'ja, future', tint: 'all' }],
          rows: [
            { who: 'to go on foot', cells: ['iść', 'pójść', 'pójdę'] },
            { who: 'to go by vehicle', cells: ['jechać', 'pojechać', 'pojadę'] },
            { who: 'to take', cells: ['brać', 'wziąć', 'wezmę'] },
            { who: 'to say, to tell', cells: ['mówić', 'powiedzieć', 'powiem'] },
            { who: 'to give', cells: ['dawać', 'dać', 'dam'] },
            { who: 'to eat', cells: ['jeść', 'zjeść', 'zjem'] },
            { who: 'to start', cells: ['zaczynać', 'zacząć', 'zacznę'] },
            { who: 'to come back', cells: ['wracać', 'wrócić', 'wrócę'] },
            { who: 'to meet', cells: ['spotykać', 'spotkać', 'spotkam'] },
            { who: 'to help', cells: ['pomagać', 'pomóc', 'pomogę'] },
            { who: 'to know / to find out', cells: ['wiedzieć', 'dowiedzieć się', 'dowiem się'] },
          ] },
      ],
      rules: [
        { t: 'Pójść and pojechać are the one-trip futures of iść and jechać', ex: 'Jutro pójdę do kina, a w sierpniu pojadę nad morze.', en: 'Tomorrow I will go to the cinema, and in August I will go to the seaside.' },
        { t: 'Dać, zjeść and powiedzieć take -m and -sz, but -dzą for oni', ex: 'Dam ci książkę. Oni dadzą ci książkę.', en: 'I will give you a book. They will give you a book.' },
        { t: 'Wiedzieć is imperfective, so “I will know” is compound. “I will find out” is dowiem się', ex: 'Jutro będę wiedział. Jutro się dowiem.', en: 'Tomorrow I will know. Tomorrow I will find out.' },
      ],
      watch: [
        'Wziąć loses its ą completely: wezmę, weźmiesz, wezmą. The z is soft (ź) in every form except ja and oni.',
        'Pojechać has a in ja and oni, and e everywhere else: pojadę, pojadą, but pojedziesz, pojedzie.',
        'The oni forms are dadzą, zjedzą, powiedzą and wiedzą. “Dają” exists, but it is the present tense of dawać.',
      ],
    },
    {
      id: 'future-aspect', pl: 'Który aspekt?', en: 'Choosing the aspect', q: 'będę pisać czy napiszę?',
      summary: 'Here you get both verbs of a pair and choose. If the sentence is about a process, a length of time or a habit, use będę + the imperfective verb. If it is about one action that gets done, use the perfective verb on its own.',
      tables: [
        { title: 'Two futures side by side',
          cols: [{ label: 'Imperfective: będę + verb', tint: 'all' }, { label: 'Perfective: one word', tint: 'all' }],
          rows: [
            { who: 'What it shows', cells: ['an action in progress, lasting or repeated', 'one action, completed, with a result'] },
            { who: 'Typical signal words', cells: ['codziennie, często, zawsze, cały dzień, długo, przez godzinę, jak często?', 'zaraz, jak tylko, do piątku, w końcu, najpierw… a potem…'] },
            { who: 'Example', cells: ['[Będę pisać] maile przez dwie godziny.', '[Napiszę] jednego maila.'] },
            { who: 'In English', cells: ['I will be writing emails for two hours.', 'I will write one email.'] },
          ] },
      ],
      rules: [
        { t: 'How long or how often: imperfective', ex: 'W sobotę cały dzień będziemy sprzątać.', en: 'On Saturday we will be tidying up all day.' },
        { t: 'One finished action, often with a deadline or a result: perfective', ex: 'Przeczytam tę książkę do piątku.', en: 'I will read this book by Friday.' },
        { t: 'A chain of actions, one after another: perfective', ex: 'Najpierw zjem obiad, a potem zadzwonię.', en: 'First I will eat lunch, and then I will call.' },
      ],
      watch: [
        '“Przez” plus a length of time (przez godzinę, przez dwa lata) always goes with the imperfective verb.',
        '“Do” plus a deadline (do piątku, do jutra) asks whether the action will be finished, so it goes with the perfective verb.',
        'English “will” does not tell you the aspect. Ask yourself: is the point the activity itself, or getting it done?',
      ],
    },
  ],

  sentences: [
    // Być
    { c: 'future-byc', p: 'ja', s: 'Jutro{tomorrow} ___ w{at} domu{home|m2}.', base: 'być', hint: 'ja', gloss: 'to be', a: ['będę'], en: 'Tomorrow I will be at home.', why: 'The ja form is będę. It already means “I will be”, so nothing else is needed.' },
    { c: 'future-byc', p: 'ty', s: 'Gdzie{where} ___ jutro{tomorrow} wieczorem{in the evening|m2}?', base: 'być', hint: 'ty', gloss: 'to be', a: ['będziesz'], en: 'Where will you be tomorrow evening?', why: 'For ty the d softens to dzi and the ending is -esz: będziesz.' },
    { c: 'future-byc', p: 'ona', s: 'W{on} sobotę{Saturday|f} ___ ładna{nice|f} pogoda{weather|f}.', base: 'być', gloss: 'to be', a: ['będzie'], en: 'The weather will be nice on Saturday.', why: 'Pogoda is one thing, so third person singular: będzie.' },
    { c: 'future-byc', p: 'my', s: 'W_przyszłym_tygodniu{next week} ___ w{in} Warszawie{Warsaw|f}.', base: 'być', hint: 'my', gloss: 'to be', a: ['będziemy'], en: 'Next week we will be in Warsaw.', why: 'The my form adds -emy to the soft stem: będziemy.' },
    { c: 'future-byc', p: 'wy', s: 'Czy{(yes/no question)} ___ jutro{tomorrow} w{at} pracy{work|f}?', base: 'być', hint: 'wy', gloss: 'to be', a: ['będziecie'], en: 'Will you (all) be at work tomorrow?', why: 'The wy form adds -ecie to the soft stem: będziecie.' },
    { c: 'future-byc', p: 'oni', s: 'Moi{my|m.pl} rodzice{parents|m1.pl} ___ tutaj{here} o{at} piątej{five o’clock|f}.', base: 'być', gloss: 'to be', a: ['będą'], en: 'My parents will be here at five.', why: 'Rodzice is plural, so third person plural: będą. Like będę, it keeps the hard d.' },
    { c: 'future-byc', p: 'ona', s: 'Za{in} rok{a year|m2} Ania{Ania|f} ___ lekarką{a doctor|f}.', base: 'być', gloss: 'to be', a: ['będzie'], en: 'In a year Ania will be a doctor.', why: 'Ania is ona, so będzie. The noun after it is in the instrumental (lekarką), just as after jest.' },
    { c: 'future-byc', p: 'ja', s: 'Nie{not} ___ jutro{tomorrow} na{at} lekcji{the lesson|f}.', base: 'być', hint: 'ja', gloss: 'to be', a: ['będę'], en: 'I won’t be at the lesson tomorrow.', why: 'Negation changes nothing here: nie plus the ja form będę.' },
    { c: 'future-byc', p: 'ono', s: 'Marka{Marek|m1} jutro{tomorrow} nie{not} ___ w{at} pracy{work|f}.', base: 'być', hint: 'future of “nie ma”', gloss: 'to be', a: ['będzie'], en: 'Marek won’t be at work tomorrow.', why: '“Nie ma Marka” (Marek isn’t here) becomes “nie będzie Marka”. It is always będzie, and the person stays in the genitive.' },
    { c: 'future-byc', p: 'ty', s: 'Kiedy{when} ___ gotowy{ready|m}, Tomku{Tomek|m1}?', base: 'być', gloss: 'to be', a: ['będziesz'], en: 'When will you be ready, Tomek?', why: 'You are speaking to Tomek directly, so it is the ty form: będziesz.' },
    { c: 'future-byc', p: 'one', s: 'Dzieci{the children|n.pl} ___ głodne{hungry|n.pl} po{after} szkole{school|f}.', base: 'być', gloss: 'to be', a: ['będą'], en: 'The children will be hungry after school.', why: 'Dzieci is plural, so będą.' },
    { c: 'future-byc', p: 'my', s: '___ zmęczeni{tired|m.pl} po{after} podróży{the journey|f}.', base: 'być', hint: 'my', gloss: 'to be', a: ['Będziemy'], en: 'We will be tired after the journey.', why: 'The my form is będziemy. The adjective zmęczeni is plural to match.' },
    { c: 'future-byc', p: 'wy', s: 'Mam{I have} nadzieję{hope|f}, że{that} ___ zadowoleni{pleased|m.pl}.', base: 'być', hint: 'wy', gloss: 'to be', a: ['będziecie'], en: 'I hope you (all) will be pleased.', why: 'The wy form is będziecie.' },
    { c: 'future-byc', p: 'one', s: 'W{on} sobotę{Saturday|f} ___ moje{my|f.pl} urodziny{birthday|f.pl}.', base: 'być', gloss: 'to be', a: ['będą'], en: 'It will be my birthday on Saturday.', why: 'Urodziny exists only in the plural in Polish, so the verb is plural too: będą.' },
    { c: 'future-byc', p: 'on', s: 'O{at} której{what time|f} ___ obiad{dinner|m2}?', base: 'być', gloss: 'to be', a: ['będzie'], en: 'What time will dinner be?', why: 'Obiad is one thing, so third person singular: będzie.' },

    // Będę + infinitive
    { c: 'future-bede-inf', p: 'ja', s: 'Jutro{tomorrow} ___ książkę{a book|f}.', base: 'czytać', hint: 'ja, with the infinitive', gloss: 'to read', a: ['będę czytać', 'będę czytał', 'będę czytała'], en: 'Tomorrow I will be reading a book.', why: 'Czytać is imperfective, so the future needs będę. Only będę changes for the person, the infinitive stays as it is.' },
    { c: 'future-bede-inf', p: 'my', s: 'Wieczorem{in the evening|m2} ___ film{a film|m2}.', base: 'oglądać', hint: 'my, with the infinitive', gloss: 'to watch', a: ['będziemy oglądać', 'będziemy oglądali', 'będziemy oglądały'], en: 'In the evening we will be watching a film.', why: 'The my form of będę is będziemy. Oglądać is imperfective, so it can follow it unchanged.' },
    { c: 'future-bede-inf', p: 'ty', s: 'Co{what} ___ w{at} weekend{the weekend|m2}?', base: 'robić', hint: 'ty, with the infinitive', gloss: 'to do', a: ['będziesz robić', 'będziesz robił', 'będziesz robiła'], en: 'What will you be doing at the weekend?', why: 'The ty form is będziesz. The question is about how you will spend the time, so the imperfective robić fits.' },
    { c: 'future-bede-inf', p: 'on', s: 'W{in} lipcu{July|m2} Marek{Marek|m1} ___ w{in} Berlinie{Berlin|m2}.', base: 'pracować', hint: 'with the infinitive', gloss: 'to work', a: ['będzie pracować', 'będzie pracował'], en: 'In July Marek will be working in Berlin.', why: 'Marek is on, so będzie. Working for a whole month is an ongoing activity, so imperfective.' },
    { c: 'future-bede-inf', p: 'ona', s: 'Moja{my|f} siostra{sister|f} ___ w{in} Krakowie{Kraków|m2}.', base: 'studiować', hint: 'with the infinitive', gloss: 'to study (at university)', a: ['będzie studiować', 'będzie studiowała'], en: 'My sister will be studying in Kraków.', why: 'Siostra is ona, so będzie. The infinitive does not change for gender.' },
    { c: 'future-bede-inf', p: 'wy', s: 'Czy{(yes/no question)} ___ jutro{tomorrow} w_piłkę{football}?', base: 'grać', hint: 'wy, with the infinitive', gloss: 'to play', a: ['będziecie grać', 'będziecie grali', 'będziecie grały'], en: 'Will you (all) be playing football tomorrow?', why: 'The wy form is będziecie. Grać is imperfective, so it follows unchanged.' },
    { c: 'future-bede-inf', p: 'one', s: 'Dzieci{the children|n.pl} ___ się{themselves} w{in} ogrodzie{the garden|m2}.', base: 'bawić się', hint: 'with the infinitive; się is already in the sentence', gloss: 'to play', a: ['będą bawić', 'będą bawiły'], en: 'The children will be playing in the garden.', why: 'Dzieci is plural, so będą. Się stays with the verb as usual.' },
    { c: 'future-bede-inf', p: 'ja', s: 'Nie{not} ___ dzisiaj{today} kawy{coffee|f}.', base: 'pić', hint: 'ja, with the infinitive', gloss: 'to drink', a: ['będę pić', 'będę pił', 'będę piła'], en: 'I won’t be drinking coffee today.', why: 'Nie goes in front of będę. The object kawy is in the genitive because of the negation.' },
    { c: 'future-bede-inf', p: 'ono', s: 'Jutro{tomorrow} cały{all|m} dzień{day|m2} ___.', base: 'padać', hint: 'with the infinitive', gloss: 'to rain', a: ['będzie padać', 'będzie padało'], en: 'Tomorrow it will be raining all day.', why: 'Weather with no subject uses the third person singular: będzie. “Cały dzień” shows the rain lasts, so imperfective.' },
    { c: 'future-bede-inf', p: 'ja', s: 'Od{from} września{September|m2} ___ się{myself} polskiego{Polish|m}.', base: 'uczyć się', hint: 'ja, with the infinitive; się is already in the sentence', gloss: 'to learn, to study', a: ['będę uczyć', 'będę uczył', 'będę uczyła'], en: 'From September I will be learning Polish.', why: 'Learning from September on is a long process, so imperfective: będę uczyć się.' },
    { c: 'future-bede-inf', p: 'oni', s: 'Rodzice{my parents|m1.pl} ___ na{for} nas{us} na{at} dworcu{the station|m2}.', base: 'czekać', hint: 'with the infinitive', gloss: 'to wait', a: ['będą czekać', 'będą czekali'], en: 'My parents will be waiting for us at the station.', why: 'Rodzice is plural, so będą. Waiting is an action in progress, so imperfective.' },
    { c: 'future-bede-inf', p: 'wy', s: 'Jak{how} długo{long} ___ w{in} Polsce{Poland|f}?', base: 'mieszkać', hint: 'wy, with the infinitive', gloss: 'to live', a: ['będziecie mieszkać', 'będziecie mieszkali', 'będziecie mieszkały'], en: 'How long will you (all) be living in Poland?', why: 'The wy form is będziecie. “Jak długo” asks about a length of time, which calls for an imperfective verb.' },
    { c: 'future-bede-inf', p: 'ja', s: 'W{on} niedzielę{Sunday|f} ___ do{until} dziesiątej{ten o’clock|f}.', base: 'spać', hint: 'ja, with the infinitive', gloss: 'to sleep', a: ['będę spać', 'będę spał', 'będę spała'], en: 'On Sunday I will sleep until ten.', why: 'Sleeping until ten is an action that lasts, so będę plus the imperfective spać.' },
    { c: 'future-bede-inf', p: 'one', s: 'W{on} sobotę{Saturday|f} Anna{Anna|f} i{and} Ewa{Ewa|f} ___ obiad{dinner|m2} dla{for} całej{the whole|f} rodziny{family|f}.', base: 'gotować', hint: 'with the infinitive', gloss: 'to cook', a: ['będą gotować', 'będą gotowały'], en: 'On Saturday Anna and Ewa will be cooking dinner for the whole family.', why: 'Two people make a plural subject, so będą. The infinitive stays the same for everyone.' },

    // Będę + -ł form
    { c: 'future-bede-l', p: 'ja', s: 'Jutro{tomorrow} ___ cały{all|m} dzień{day|m2}.', base: 'pracować', hint: 'ja (a man), with the -ł form', gloss: 'to work', a: ['będę pracował', 'będę pracować'], en: 'Tomorrow I will be working all day.', why: 'A man says będę pracował: the masculine past form without the ending -em. The person is already in będę.' },
    { c: 'future-bede-l', p: 'ty', s: 'Aniu{Ania|f}, co{what} ___ w{on} sobotę{Saturday|f}?', base: 'robić', hint: 'with the -ł form', gloss: 'to do', a: ['będziesz robiła', 'będziesz robić'], en: 'Ania, what will you be doing on Saturday?', why: 'You are talking to a woman, so ty plus the feminine form: będziesz robiła.' },
    { c: 'future-bede-l', p: 'ja', s: 'Jutro{tomorrow} ___ wcześnie{early} wstać{get up}.', base: 'musieć', hint: 'ja (a woman)', gloss: 'to have to', a: ['będę musiała'], en: 'Tomorrow I will have to get up early.', why: 'Musieć takes the -ł form in the future, not the infinitive. A woman says będę musiała.' },
    { c: 'future-bede-l', p: 'on', s: 'Niestety{unfortunately} Piotr{Piotr|m1} nie{not} ___ przyjść{come}.', base: 'móc', gloss: 'to be able to', a: ['będzie mógł'], en: 'Unfortunately Piotr won’t be able to come.', why: 'Móc takes the -ł form in the future. For a man it is mógł, with ó.' },
    { c: 'future-bede-l', p: 'ty', s: 'Czy{(yes/no question)} ___ mi{me} jutro{tomorrow} pomóc{help}?', base: 'móc', hint: 'ty (to a man)', gloss: 'to be able to', a: ['będziesz mógł'], en: 'Will you be able to help me tomorrow?', why: 'Ty plus the masculine form of móc: będziesz mógł. To a woman it would be będziesz mogła.' },
    { c: 'future-bede-l', p: 'my', s: 'W{at} weekend{the weekend|m2} ___ w_tenisa{tennis}.', base: 'grać', hint: 'my (two men), with the -ł form', gloss: 'to play', a: ['będziemy grali', 'będziemy grać'], en: 'At the weekend we will be playing tennis.', why: 'A group with at least one man takes -li: będziemy grali.' },
    { c: 'future-bede-l', p: 'one', s: 'Moje{my|f.pl} córki{daughters|f.pl} ___ w{in} Gdańsku{Gdańsk|m2}.', base: 'studiować', hint: 'with the -ł form', gloss: 'to study (at university)', a: ['będą studiowały', 'będą studiować'], en: 'My daughters will be studying in Gdańsk.', why: 'Daughters are a group without men, so the plural ending is -ły: będą studiowały.' },
    { c: 'future-bede-l', p: 'oni', s: 'Chłopcy{the boys|m1.pl} ___ mecz{the match|m2}.', base: 'oglądać', hint: 'with the -ł form', gloss: 'to watch', a: ['będą oglądali', 'będą oglądać'], en: 'The boys will be watching the match.', why: 'Boys are a male group, so the plural ending is -li: będą oglądali.' },
    { c: 'future-bede-l', p: 'ono', s: 'Dziecko{the child|n} ___ u{at} babci{grandma’s|f}.', base: 'spać', hint: 'with the -ł form', gloss: 'to sleep', a: ['będzie spało', 'będzie spać'], en: 'The child will be sleeping at grandma’s.', why: 'Dziecko is neuter, so the form ends in -ło: będzie spało.' },
    { c: 'future-bede-l', p: 'ona', s: 'Kasia{Kasia|f} ___ na{for} ciebie{you} przed{in front of} kinem{the cinema|n}.', base: 'czekać', hint: 'with the -ł form', gloss: 'to wait', a: ['będzie czekała', 'będzie czekać'], en: 'Kasia will be waiting for you in front of the cinema.', why: 'Kasia is ona, so the feminine form in -ła: będzie czekała.' },
    { c: 'future-bede-l', p: 'my', s: 'Za{in} rok{a year|m2} ___ kupić{to buy} mieszkanie{a flat|n}.', base: 'chcieć', hint: 'my (a man and a woman)', gloss: 'to want', a: ['będziemy chcieli'], en: 'In a year we will want to buy a flat.', why: 'Chcieć takes the -ł form in the future. A mixed couple counts as a group with a man, so -li, and the a in chciał turns to e: chcieli.' },
    { c: 'future-bede-l', p: 'wy', s: 'Dziewczyny{girls|f.pl}, czy{(yes/no question)} ___ jutro{tomorrow} pracować{to work}?', base: 'musieć', gloss: 'to have to', a: ['będziecie musiały'], en: 'Girls, will you have to work tomorrow?', why: 'Wy for a group of women takes -ły: będziecie musiały. Musieć always uses this form in the future.' },
    { c: 'future-bede-l', p: 'one', s: 'Dzieci{the children|n.pl} nie{not} ___ iść{go} jutro{tomorrow} do{to} szkoły{school|f}.', base: 'musieć', gloss: 'to have to', a: ['będą musiały'], en: 'The children won’t have to go to school tomorrow.', why: 'Dzieci does not count as a group of men, so it takes -ły: będą musiały.' },
    { c: 'future-bede-l', p: 'ja', s: 'Wieczorem{in the evening|m2} ___ kolację{supper|f} z{with} rodzicami{my parents|m1.pl}.', base: 'jeść', hint: 'ja (a man), with the -ł form', gloss: 'to eat', a: ['będę jadł', 'będę jeść'], en: 'In the evening I will be having supper with my parents.', why: 'The -ł form of jeść is built on the stem jad-: jadł, jadła. A man says będę jadł.' },
    { c: 'future-bede-l', p: 'on', s: 'Mój{my|m} brat{brother|m1} ___ nowy{a new|m} samochód{car|m2}.', base: 'mieć', hint: 'with the -ł form', gloss: 'to have', a: ['będzie miał', 'będzie mieć'], en: 'My brother will have a new car.', why: 'Mieć is imperfective, so “will have” is compound. Brat is on, so the masculine form: będzie miał.' },

    // Regular perfectives
    { c: 'future-perf', p: 'ja', s: 'Jutro{tomorrow} ___ zakupy{the shopping|m2.pl}.', base: 'zrobić', hint: 'ja', gloss: 'to do (and finish)', a: ['zrobię'], en: 'Tomorrow I will do the shopping.', why: 'Zrobić is the perfective partner of robić. Conjugate it like robię with the prefix z-, and it already means the future.' },
    { c: 'future-perf', p: 'ty', s: 'Kiedy{when} ___ tę{this|f} książkę{book|f}?', base: 'przeczytać', hint: 'ty', gloss: 'to read (to the end)', a: ['przeczytasz'], en: 'When will you read this book?', why: 'Czytać / przeczytać. It conjugates like czytasz, with the prefix prze-: przeczytasz.' },
    { c: 'future-perf', p: 'ja', s: 'Wieczorem{in the evening|m2} ___ do{to} ciebie{you} maila{an email|m2}.', base: 'napisać', hint: 'ja', gloss: 'to write (and finish)', a: ['napiszę'], en: 'In the evening I will write you an email.', why: 'Pisać / napisać. The s changes to sz exactly as in the present piszę, so napiszę.' },
    { c: 'future-perf', p: 'ona', s: 'Mama{mum|f} ___ chleb{bread|m2} po{after} pracy{work|f}.', base: 'kupić', gloss: 'to buy', a: ['kupi'], en: 'Mum will buy bread after work.', why: 'Kupować / kupić. One purchase that gets done, so perfective. The ona form of an -ić verb ends in -i: kupi.' },
    { c: 'future-perf', p: 'my', s: '___ się{each other} jutro{tomorrow} w{at} szkole{school|f}.', base: 'zobaczyć się', hint: 'my; się is already in the sentence', gloss: 'to see each other', a: ['Zobaczymy'], en: 'We will see each other at school tomorrow.', why: 'Widzieć / zobaczyć. The my form of a -yć verb ends in -ymy: zobaczymy się.' },
    { c: 'future-perf', p: 'wy', s: 'Czy{(yes/no question)} ___ dzisiaj{today} obiad{dinner|m2}?', base: 'ugotować', hint: 'wy', gloss: 'to cook (until ready)', a: ['ugotujecie'], en: 'Will you (all) cook dinner today?', why: 'Gotować / ugotować. Verbs in -ować switch to -uj- when conjugated: ugotuję, ugotujecie.' },
    { c: 'future-perf', p: 'oni', s: 'Oni{they|m1.pl} ___ za{for} kolację{the dinner|f}.', base: 'zapłacić', gloss: 'to pay', a: ['zapłacą'], en: 'They will pay for the dinner.', why: 'Płacić / zapłacić. In the ja and oni forms ci hardens to c: zapłacę, zapłacą, but zapłacisz.' },
    { c: 'future-perf', p: 'ja', s: '___ do{to} ciebie{you} jutro{tomorrow} rano{in the morning}.', base: 'zadzwonić', hint: 'ja', gloss: 'to phone', a: ['Zadzwonię'], en: 'I will call you tomorrow morning.', why: 'Dzwonić / zadzwonić. One phone call, so perfective. It conjugates like dzwonię: zadzwonię.' },
    { c: 'future-perf', p: 'ty', s: 'O{at} której{what time|f} ___ pracę{work|f}?', base: 'skończyć', hint: 'ty', gloss: 'to finish', a: ['skończysz'], en: 'What time will you finish work?', why: 'Kończyć / skończyć. The ty form of a -yć verb ends in -ysz: skończysz.' },
    { c: 'future-perf', p: 'one', s: 'Dzieci{the children|n.pl} ___ pokój{the room|m2} po{after} obiedzie{dinner|m2}.', base: 'posprzątać', gloss: 'to tidy up', a: ['posprzątają'], en: 'The children will tidy up the room after dinner.', why: 'Sprzątać / posprzątać. It is an -am, -asz verb, so the oni form ends in -ają: posprzątają.' },
    { c: 'future-perf', p: 'ona', s: 'Ania{Ania|f} ___ kawę{her coffee|f} i{and} pójdzie{will go} do{to} pracy{work|f}.', base: 'wypić', gloss: 'to drink up', a: ['wypije'], en: 'Ania will drink her coffee and go to work.', why: 'Pić / wypić. It conjugates like pije, with the prefix wy-: wypije. She finishes the coffee first, so perfective.' },
    { c: 'future-perf', p: 'ja', s: 'W{in} tym{this|m} roku{year|m2} ___ się{myself} pływać{to swim}.', base: 'nauczyć się', hint: 'ja; się is already in the sentence', gloss: 'to learn (successfully)', a: ['nauczę'], en: 'This year I will learn to swim.', why: 'Uczyć się / nauczyć się. The perfective verb promises a result: you will be able to swim. It conjugates like uczę: nauczę się.' },
    { c: 'future-perf', p: 'ja', s: 'Zaraz{in a moment} ___ ci{you} moje{my|n.pl} zdjęcia{photos|n.pl}.', base: 'pokazać', hint: 'ja', gloss: 'to show', a: ['pokażę'], en: 'I will show you my photos in a moment.', why: 'Pokazywać / pokazać. The z changes to ż in every person: pokażę, pokażesz.' },
    { c: 'future-perf', p: 'ty', s: 'Czy{(yes/no question)} ___ mi{for me} bilet{a ticket|m2}?', base: 'kupić', hint: 'ty', gloss: 'to buy', a: ['kupisz'], en: 'Will you buy me a ticket?', why: 'Kupić is perfective, so kupisz already means “you will buy”. The ty ending of an -ić verb is -isz.' },
    { c: 'future-perf', p: 'ja', s: 'Poczekaj{wait}, ___ okno{the window|n}.', base: 'otworzyć', hint: 'ja', gloss: 'to open', a: ['otworzę'], en: 'Wait, I will open the window.', why: 'Otwierać / otworzyć. One quick completed action, so perfective: otworzę, otworzysz.' },
    { c: 'future-perf', p: 'oni', s: 'Tomek{Tomek|m1} i{and} Ola{Ola|f} ___ nas{us} na{to} obiad{dinner|m2}.', base: 'zaprosić', gloss: 'to invite', a: ['zaproszą'], en: 'Tomek and Ola will invite us to dinner.', why: 'Zapraszać / zaprosić. In the ja and oni forms si changes to sz: zaproszę, zaproszą, but zaprosisz.' },

    // Irregular perfectives
    { c: 'future-irreg', p: 'ja', s: 'Jutro{tomorrow} ___ do{to} kina{the cinema|n}.', base: 'pójść', hint: 'ja', gloss: 'to go (on foot)', a: ['pójdę'], en: 'Tomorrow I will go to the cinema.', why: 'Iść / pójść. It conjugates like idę with pó- in front, and the i becomes j: pójdę.' },
    { c: 'future-irreg', p: 'my', s: 'W{in} sierpniu{August|m2} ___ nad{to} morze{the sea|n}.', base: 'pojechać', hint: 'my', gloss: 'to go (by vehicle)', a: ['pojedziemy'], en: 'In August we will go to the seaside.', why: 'Jechać / pojechać. Like jedziemy with po- in front. Only ja and oni have a: pojadę, pojadą.' },
    { c: 'future-irreg', p: 'oni', s: 'Oni{they|m1.pl} ___ do{to} Gdańska{Gdańsk|m2} pociągiem{by train|m2}.', base: 'pojechać', gloss: 'to go (by vehicle)', a: ['pojadą'], en: 'They will go to Gdańsk by train.', why: 'The oni form of pojechać has a, like jadą: pojadą. The middle forms have e: pojedziesz, pojedzie.' },
    { c: 'future-irreg', p: 'ja', s: 'Pada{it’s raining}, więc{so} ___ parasol{an umbrella|m2}.', base: 'wziąć', hint: 'ja', gloss: 'to take', a: ['wezmę'], en: 'It’s raining, so I will take an umbrella.', why: 'Brać / wziąć. The future stem looks nothing like the infinitive: wezmę, weźmiesz, wezmą.' },
    { c: 'future-irreg', p: 'ty', s: 'Czy{(yes/no question)} ___ taksówkę{a taxi|f}?', base: 'wziąć', hint: 'ty', gloss: 'to take', a: ['weźmiesz'], en: 'Will you take a taxi?', why: 'Outside the ja and oni forms the z of wziąć is soft: weźmiesz, weźmie, weźmiemy.' },
    { c: 'future-irreg', p: 'ja', s: '___ ci{you} wszystko{everything} jutro{tomorrow}.', base: 'powiedzieć', hint: 'ja', gloss: 'to tell, to say', a: ['Powiem'], en: 'I will tell you everything tomorrow.', why: 'Mówić / powiedzieć. It conjugates like wiem: powiem, powiesz, powie.' },
    { c: 'future-irreg', p: 'oni', s: 'Rodzice{our parents|m1.pl} ___ nam{us}, co{what} robić{to do}.', base: 'powiedzieć', gloss: 'to tell, to say', a: ['powiedzą'], en: 'Our parents will tell us what to do.', why: 'The oni form of powiedzieć ends in -dzą, like wiedzą: powiedzą.' },
    { c: 'future-irreg', p: 'ona', s: 'Babcia{grandma|f} ___ ci{you} coś{something} słodkiego{sweet|n}.', base: 'dać', gloss: 'to give', a: ['da'], en: 'Grandma will give you something sweet.', why: 'Dawać / dać. Dać conjugates dam, dasz, da. The present “daje” belongs to dawać.' },
    { c: 'future-irreg', p: 'oni', s: 'Moi{my|m.pl} koledzy{friends|m1.pl} ___ mi{me} prezent{a present|m2}.', base: 'dać', gloss: 'to give', a: ['dadzą'], en: 'My friends will give me a present.', why: 'The oni form of dać is irregular: dadzą. “Dają” is the present tense of dawać.' },
    { c: 'future-irreg', p: 'one', s: 'Dzieci{the children|n.pl} ___ obiad{lunch|m2} w{at} szkole{school|f}.', base: 'zjeść', gloss: 'to eat (up)', a: ['zjedzą'], en: 'The children will eat lunch at school.', why: 'Jeść / zjeść. It conjugates like jem, and the oni form ends in -dzą: zjedzą.' },
    { c: 'future-irreg', p: 'ty', s: 'Co{what} ___ na{for} śniadanie{breakfast|n}?', base: 'zjeść', hint: 'ty', gloss: 'to eat (up)', a: ['zjesz'], en: 'What will you eat for breakfast?', why: 'Zjeść follows jem, jesz, je with the prefix z-: zjem, zjesz, zje.' },
    { c: 'future-irreg', p: 'on', s: 'Film{the film|m2} ___ się{itself} o{at} ósmej{eight o’clock|f}.', base: 'zacząć się', hint: 'się is already in the sentence', gloss: 'to start', a: ['zacznie'], en: 'The film will start at eight.', why: 'Zaczynać / zacząć. The ą disappears and an n comes in: zacznę, zaczniesz, zacznie.' },
    { c: 'future-irreg', p: 'ty', s: 'O{at} której{what time|f} ___ do{to} domu{home|m2}?', base: 'wrócić', hint: 'ty', gloss: 'to come back', a: ['wrócisz'], en: 'What time will you come back home?', why: 'Wracać / wrócić. A regular -ić form here: wrócisz. Only ja and oni harden ci to c.' },
    { c: 'future-irreg', p: 'ja', s: '___ jutro{tomorrow} wieczorem{in the evening|m2}.', base: 'wrócić', hint: 'ja', gloss: 'to come back', a: ['Wrócę'], en: 'I will be back tomorrow evening.', why: 'In the ja and oni forms of wrócić, ci hardens to c: wrócę, wrócą.' },
    { c: 'future-irreg', p: 'ja', s: 'Jutro{tomorrow} ___ się{each other} z{with} Anią{Ania|f} w{in} kawiarni{a café|f}.', base: 'spotkać się', hint: 'ja; się is already in the sentence', gloss: 'to meet up', a: ['spotkam'], en: 'Tomorrow I will meet Ania in a café.', why: 'Spotykać się / spotkać się. The perfective verb is shorter than its partner. It takes -am, -asz: spotkam się.' },
    { c: 'future-irreg', p: 'ja', s: 'Zaraz{in a moment} ___ się{myself}, o{at} której{what time|f} jest{is} pociąg{the train|m2}.', base: 'dowiedzieć się', hint: 'ja; się is already in the sentence', gloss: 'to find out', a: ['dowiem'], en: 'I will find out in a moment what time the train is.', why: 'Dowiedzieć się is the perfective “find out”. It conjugates like wiem: dowiem się, dowiesz się, dowiedzą się.' },
    { c: 'future-irreg', p: 'ja', s: 'Jutro{tomorrow} ___, czy{whether} mam{I have} tę{this|f} pracę{job|f}.', base: 'wiedzieć', hint: 'ja (a man); wiedzieć is imperfective', gloss: 'to know', a: ['będę wiedział', 'będę wiedzieć'], en: 'Tomorrow I will know whether I have got this job.', why: 'Wiedzieć is imperfective, so “I will know” needs będę: będę wiedział. The one-word option is a different verb: dowiem się, “I will find out”.' },
    { c: 'future-irreg', p: 'wy', s: 'Czy{(yes/no question)} ___ mi{me} jutro{tomorrow}?', base: 'pomóc', hint: 'wy', gloss: 'to help', a: ['pomożecie'], en: 'Will you (all) help me tomorrow?', why: 'Pomagać / pomóc. It follows mogę, możesz: g in ja and oni (pomogę, pomogą), ż everywhere else (pomożecie).' },
    { c: 'future-irreg', p: 'wy', s: 'Kiedy{when} ___ do{to} nas{our place}?', base: 'przyjść', hint: 'wy', gloss: 'to come (on foot)', a: ['przyjdziecie'], en: 'When will you (all) come to our place?', why: 'Przychodzić / przyjść. Like pójść, it is built on idę with j instead of i: przyjdę, przyjdziecie.' },

    // Choosing the aspect
    { c: 'future-aspect', p: 'ja', s: 'Od{from} jutra{tomorrow|n} codziennie{every day} ___ po_polsku{in Polish}.', base: 'czytać / przeczytać', hint: 'ja', gloss: 'to read', a: ['będę czytać', 'będę czytał', 'będę czytała'], en: 'From tomorrow I will read in Polish every day.', why: '“Codziennie” makes it a habit, and habits are imperfective: będę czytać.' },
    { c: 'future-aspect', p: 'ja', s: '___ tę{this|f} książkę{book|f} do{by} piątku{Friday|m2}.', base: 'czytać / przeczytać', hint: 'ja', gloss: 'to read', a: ['Przeczytam'], en: 'I will read this book by Friday.', why: 'A deadline means the book gets finished, so perfective: przeczytam. No będę.' },
    { c: 'future-aspect', p: 'ja', s: 'Jutro{tomorrow} przez{for} dwie{two|f.pl} godziny{hours|f.pl} ___ maile{emails|m2.pl}.', base: 'pisać / napisać', hint: 'ja', gloss: 'to write', a: ['będę pisać', 'będę pisał', 'będę pisała'], en: 'Tomorrow I will be writing emails for two hours.', why: '“Przez dwie godziny” says how long the activity lasts, so imperfective: będę pisać.' },
    { c: 'future-aspect', p: 'ja', s: 'Poczekaj{wait}, tylko{just} ___ jednego{one|m} maila{email|m2}.', base: 'pisać / napisać', hint: 'ja', gloss: 'to write', a: ['napiszę'], en: 'Wait, I will just write one email.', why: 'One email, written and done, so perfective: napiszę.' },
    { c: 'future-aspect', p: 'ja', s: '___ do{to} ciebie{you}, jak_tylko{as soon as} wrócę{I get back}.', base: 'dzwonić / zadzwonić', hint: 'ja', gloss: 'to phone', a: ['Zadzwonię'], en: 'I will call you as soon as I get back.', why: 'One call at one moment, so perfective: zadzwonię.' },
    { c: 'future-aspect', p: 'my', s: 'W{in} wakacje{the holidays|f.pl} ___ do{to} babci{grandma|f} co_tydzień{every week}.', base: 'dzwonić / zadzwonić', hint: 'my', gloss: 'to phone', a: ['będziemy dzwonić', 'będziemy dzwonili', 'będziemy dzwoniły'], en: 'In the holidays we will call grandma every week.', why: '“Co tydzień” means the calls repeat, so imperfective: będziemy dzwonić.' },
    { c: 'future-aspect', p: 'my', s: 'W{on} sobotę{Saturday|f} cały{all|m} dzień{day|m2} ___ dom{the house|m2}.', base: 'sprzątać / posprzątać', hint: 'my', gloss: 'to tidy up, to clean', a: ['będziemy sprzątać', 'będziemy sprzątali', 'będziemy sprzątały'], en: 'On Saturday we will be cleaning the house all day.', why: '“Cały dzień” puts the focus on how long it lasts, so imperfective: będziemy sprzątać.' },
    { c: 'future-aspect', p: 'my', s: 'Najpierw{first} ___ kuchnię{the kitchen|f}, a{and} potem{then} odpoczniemy{we will rest}.', base: 'sprzątać / posprzątać', hint: 'my', gloss: 'to tidy up, to clean', a: ['posprzątamy'], en: 'First we will clean the kitchen, and then we will rest.', why: 'The kitchen has to be finished before the rest starts. A chain of completed actions is perfective: posprzątamy.' },
    { c: 'future-aspect', p: 'on', s: 'Nie{not} mamy{we have} mleka{milk|n}. Marek{Marek|m1} ___ je{it|n} po{after} pracy{work|f}.', base: 'kupować / kupić', gloss: 'to buy', a: ['kupi'], en: 'We have no milk. Marek will buy it after work.', why: 'One purchase that gets done, so perfective: kupi.' },
    { c: 'future-aspect', p: 'ona', s: 'W{in} nowej{her new|f} pracy{job|f} Ewa{Ewa|f} codziennie{every day} ___ obiad{lunch|m2} w{in} stołówce{the canteen|f}.', base: 'jeść / zjeść', gloss: 'to eat', a: ['będzie jeść', 'będzie jadła'], en: 'In her new job Ewa will eat lunch in the canteen every day.', why: '“Codziennie” makes it a habit, so imperfective: będzie jeść, or będzie jadła.' },
    { c: 'future-aspect', p: 'ja', s: 'Jestem{I am} głodny{hungry|m}. Zaraz{in a moment} coś{something} ___.', base: 'jeść / zjeść', hint: 'ja', gloss: 'to eat', a: ['zjem'], en: 'I am hungry. I will eat something in a moment.', why: 'One quick meal with a result (no longer hungry), so perfective: zjem.' },
    { c: 'future-aspect', p: 'oni', s: 'Oni{they|m1.pl} ___ ten{this|m} dom{house|m2} przez{for} dwa{two|n.pl} lata{years|n.pl}.', base: 'budować / zbudować', gloss: 'to build', a: ['będą budować', 'będą budowali'], en: 'They will be building this house for two years.', why: '“Przez dwa lata” is a length of time, so imperfective: będą budować.' },
    { c: 'future-aspect', p: 'wy', s: 'Czy{(yes/no question)} ___ ten{this|m} raport{report|m2} do{by} jutra{tomorrow|n}?', base: 'kończyć / skończyć', hint: 'wy', gloss: 'to finish', a: ['skończycie'], en: 'Will you (all) finish this report by tomorrow?', why: 'A deadline asks whether the job will be done, so perfective: skończycie.' },
    { c: 'future-aspect', p: 'one', s: 'Dzieci{the children|n.pl} najpierw{first} ___ lekcje{their homework|f.pl}, a{and} potem{then} pójdą{will go} do{to} parku{the park|m2}.', base: 'odrabiać / odrobić', gloss: 'to do (homework)', a: ['odrobią'], en: 'The children will first do their homework, and then they will go to the park.', why: 'The homework must be finished before the park. Completed actions in a row are perfective: odrobią.' },
    { c: 'future-aspect', p: 'ty', s: 'Jak{how} często{often} ___ do{to} rodziców{your parents|m1.pl}?', base: 'pisać / napisać', hint: 'ty', gloss: 'to write', a: ['będziesz pisać', 'będziesz pisał', 'będziesz pisała'], en: 'How often will you write to your parents?', why: '“Jak często” asks about a repeated action, so imperfective: będziesz pisać.' },
  ],
};
