/* Past tense (czas przeszły): reference tables and quiz sentences.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const PAST_TENSE = {
  id: 'past', pl: 'Czas przeszły', en: 'Past tense',
  intro: 'Take the infinitive, swap -ć for -ł- and add an ending. The verb agrees with its subject in person, number and gender, so “I read” is czytałem when a man says it and czytałam when a woman does.',

  groups: [
    {
      id: 'past-regular', pl: 'Regularne', en: 'Regular verbs', q: 'czytać → czytał',
      summary: 'Verbs in -ać, -ić, -yć and -ować simply drop -ć and add -ł- plus the ending. The vowel before -ł- never changes.',
      tables: [
        { title: 'czytać, to read: singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['czyta[łem]', 'czyta[łam]', '—'] },
            { who: 'ty', cells: ['czyta[łeś]', 'czyta[łaś]', '—'] },
            { who: 'on / ona / ono', cells: ['czyta[ł]', 'czyta[ła]', 'czyta[ło]'] },
          ] },
        { title: 'czytać, to read: plural',
          cols: [{ label: 'Groups with a man', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['czyta[liśmy]', 'czyta[łyśmy]'] },
            { who: 'wy', cells: ['czyta[liście]', 'czyta[łyście]'] },
            { who: 'oni / one', cells: ['czyta[li]', 'czyta[ły]'] },
          ] },
        { title: 'The same pattern with other regular verbs',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'robić, to do', cells: ['robi[ł]', 'robi[ła]', 'robi[li]', 'robi[ły]'] },
            { who: 'uczyć się, to learn', cells: ['uczy[ł] się', 'uczy[ła] się', 'uczy[li] się', 'uczy[ły] się'] },
            { who: 'pracować, to work', cells: ['pracowa[ł]', 'pracowa[ła]', 'pracowa[li]', 'pracowa[ły]'] },
            { who: 'pić, to drink', cells: ['pi[ł]', 'pi[ła]', 'pi[li]', 'pi[ły]'] },
          ] },
      ],
      rules: [
        { t: 'Drop -ć, add -ł- and the ending for the person', ex: 'Wczoraj kupiłem chleb.', en: 'Yesterday I bought bread.' },
        { t: 'The speaker’s own gender decides between -łem and -łam', ex: 'Czytałam tę książkę.', en: 'I have read this book. (a woman speaking)' },
        { t: 'Verbs in -ować keep -owa- in the past, unlike the present (pracuję)', ex: 'Marek pracował w banku.', en: 'Marek worked in a bank.' },
        { t: 'The pronoun is usually left out because the ending already shows the person', ex: 'Co robiłeś w sobotę?', en: 'What did you do on Saturday?' },
      ],
      watch: [
        'The past is built from the infinitive, not from the present tense: pisać gives pisał, even though the present is piszę.',
        'There is no separate “did” or “was doing” form. Pick the imperfective verb (czytałem) for an activity or a habit and the perfective one (przeczytałem) for a finished result.',
        'In the my and wy forms the stress stays where it is in the oni form: czyTAli, czyTAliśmy, czyTAliście.',
      ],
    },
    {
      id: 'past-ec', pl: 'Czasowniki -eć', en: 'Verbs in -eć', q: 'mieć → miał, mieli',
      summary: 'Verbs in -eć turn the e into a before ł: miał, miała, miało, miały. Only the forms with -li, the ones for groups with a man, keep the e: mieli.',
      tables: [
        { title: 'mieć, to have: singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['mi[ałem]', 'mi[ałam]', '—'] },
            { who: 'ty', cells: ['mi[ałeś]', 'mi[ałaś]', '—'] },
            { who: 'on / ona / ono', cells: ['mi[ał]', 'mi[ała]', 'mi[ało]'] },
          ] },
        { title: 'mieć, to have: plural',
          cols: [{ label: 'Groups with a man', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['mi[eliśmy]', 'mi[ałyśmy]'] },
            { who: 'wy', cells: ['mi[eliście]', 'mi[ałyście]'] },
            { who: 'oni / one', cells: ['mi[eli]', 'mi[ały]'] },
          ] },
        { title: 'Other common verbs of this type',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'chcieć, to want', cells: ['chci[ał]', 'chci[ała]', 'chci[eli]', 'chci[ały]'] },
            { who: 'widzieć, to see', cells: ['widzi[ał]', 'widzi[ała]', 'widzi[eli]', 'widzi[ały]'] },
            { who: 'musieć, to have to', cells: ['musi[ał]', 'musi[ała]', 'musi[eli]', 'musi[ały]'] },
            { who: 'wiedzieć, to know', cells: ['wiedzi[ał]', 'wiedzi[ała]', 'wiedzi[eli]', 'wiedzi[ały]'] },
            { who: 'rozumieć, to understand', cells: ['rozumi[ał]', 'rozumi[ała]', 'rozumi[eli]', 'rozumi[ały]'] },
            { who: 'myśleć, to think', cells: ['myśl[ał]', 'myśl[ała]', 'myśl[eli]', 'myśl[ały]'] },
            { who: 'słyszeć, to hear', cells: ['słysz[ał]', 'słysz[ała]', 'słysz[eli]', 'słysz[ały]'] },
            { who: 'zapomnieć, to forget', cells: ['zapomni[ał]', 'zapomni[ała]', 'zapomni[eli]', 'zapomni[ały]'] },
          ] },
      ],
      rules: [
        { t: 'Before ł the e of the infinitive becomes a', ex: 'Anna miała psa.', en: 'Anna had a dog.' },
        { t: 'Before l, in the forms for groups with a man, the e stays', ex: 'Moi rodzice mieli psa.', en: 'My parents had a dog.' },
        { t: 'The plural for women and things has ł, so it takes a again', ex: 'Moje siostry miały psa.', en: 'My sisters had a dog.' },
      ],
      watch: [
        'It is easy to write “mieł” or “chcieł” by copying the infinitive. With ł the vowel is always a: miał, chciał.',
        'The opposite slip is “miali”. With -li the vowel is always e: mieli, chcieli, widzieli.',
        'A few verbs in -rzeć work differently, for example umrzeć (to die) gives umarł. Learn those one by one.',
      ],
    },
    {
      id: 'past-byc', pl: 'Być', en: 'To be', q: 'być → był, była, byli',
      summary: 'Być is fully regular in the past: by- plus the usual endings. You need it all the time, also for “there was”, the weather and “nie było”.',
      tables: [
        { title: 'być, to be: singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['by[łem]', 'by[łam]', '—'] },
            { who: 'ty', cells: ['by[łeś]', 'by[łaś]', '—'] },
            { who: 'on / ona / ono', cells: ['by[ł]', 'by[ła]', 'by[ło]'] },
          ] },
        { title: 'być, to be: plural',
          cols: [{ label: 'Groups with a man', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['by[liśmy]', 'by[łyśmy]'] },
            { who: 'wy', cells: ['by[liście]', 'by[łyście]'] },
            { who: 'oni / one', cells: ['by[li]', 'by[ły]'] },
          ] },
      ],
      rules: [
        { t: 'Where someone was, or what something was like', ex: 'Wczoraj byłam w pracy.', en: 'Yesterday I was at work. (a woman speaking)' },
        { t: 'Sentences with no real subject use the neuter było', ex: 'Wczoraj było zimno.', en: 'It was cold yesterday.' },
        { t: 'The past of “nie ma” is “nie było”, always neuter, with the genitive', ex: 'Nie było mleka.', en: 'There was no milk.' },
      ],
      watch: [
        'Things follow their grammatical gender: film był, kawa była, piwo było.',
        '“Nie było” never changes, even when the missing person is a woman or a group: Nie było Anny. Nie było studentów.',
        'In the plural only groups with at least one man take byli. Women, children, animals and things take były.',
      ],
    },
    {
      id: 'past-isc', pl: 'Iść, pójść', en: 'Iść and its family', q: 'iść → szedł, szła, szli',
      summary: 'Iść builds its past on a different stem: szedł for a man, but szła, szło, szli, szły without the e. Every prefixed verb (pójść, przyjść, wyjść, wejść) copies this pattern.',
      tables: [
        { title: 'iść, to go on foot: singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['sz[e]dłem', 'szłam', '—'] },
            { who: 'ty', cells: ['sz[e]dłeś', 'szłaś', '—'] },
            { who: 'on / ona / ono', cells: ['sz[e]dł', 'szła', 'szło'] },
          ] },
        { title: 'iść, to go on foot: plural',
          cols: [{ label: 'Groups with a man', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['sz[liśmy]', 'sz[łyśmy]'] },
            { who: 'wy', cells: ['sz[liście]', 'sz[łyście]'] },
            { who: 'oni / one', cells: ['sz[li]', 'sz[ły]'] },
          ] },
        { title: 'Prefixed verbs',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'pójść, to go (once)', cells: ['po[szedł]', 'po[szła]', 'po[szli]', 'po[szły]'] },
            { who: 'przyjść, to come', cells: ['przy[szedł]', 'przy[szła]', 'przy[szli]', 'przy[szły]'] },
            { who: 'wyjść, to leave', cells: ['wy[szedł]', 'wy[szła]', 'wy[szli]', 'wy[szły]'] },
            { who: 'wejść, to come in', cells: ['w[szedł]', 'we[szła]', 'we[szli]', 'we[szły]'] },
          ] },
      ],
      rules: [
        { t: 'Masculine singular has -szedł-, with the e and the d', ex: 'Marek poszedł do sklepu.', en: 'Marek went to the shop.' },
        { t: 'Every other form drops the e and the d: szła, szło, szli, szły', ex: 'Anna poszła do sklepu.', en: 'Anna went to the shop.' },
        { t: 'Use iść for being on the way, pójść for one completed trip', ex: 'Szłam do pracy, kiedy zadzwoniłeś.', en: 'I was walking to work when you called.' },
      ],
      watch: [
        'Forms like “poszłem” are a well-known mistake. A man says poszedłem, a woman says poszłam.',
        'Wejść moves its e around: wszedł for a man, but weszła, weszli, weszły.',
        'Iść is only for going on foot. For trips by car, bus or train use jechać and pojechać, which are regular: jechał, pojechała.',
      ],
    },
    {
      id: 'past-irregular', pl: 'Nieregularne', en: 'Other irregular stems', q: 'jeść → jadł, móc → mógł',
      summary: 'Infinitives in -ść, -źć and -c hide a consonant that comes back in the past (jeść → jadł, móc → mógł). Verbs in -ąć switch between ą and ę (wziął, wzięła).',
      tables: [
        { title: 'Infinitives in -ść, -źć and -c',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'jeść, to eat', cells: ['j[a]dł', 'j[a]dła', 'j[e]dli', 'j[a]dły'] },
            { who: 'usiąść, to sit down', cells: ['usi[a]dł', 'usi[a]dła', 'usi[e]dli', 'usi[a]dły'] },
            { who: 'znaleźć, to find', cells: ['znal[a]zł', 'znal[a]zła', 'znal[e]źli', 'znal[a]zły'] },
            { who: 'móc, can', cells: ['m[ó]gł', 'm[o]gła', 'm[o]gli', 'm[o]gły'] },
            { who: 'pomóc, to help', cells: ['pom[ó]gł', 'pom[o]gła', 'pom[o]gli', 'pom[o]gły'] },
            { who: 'nieść, to carry', cells: ['ni[ó]sł', 'ni[o]sła', 'ni[e]śli', 'ni[o]sły'] },
            { who: 'biec, to run', cells: ['bie[g]ł', 'bie[g]ła', 'bie[g]li', 'bie[g]ły'] },
            { who: 'upiec, to bake', cells: ['upie[k]ł', 'upie[k]ła', 'upie[k]li', 'upie[k]ły'] },
          ] },
        { title: 'Verbs in -ąć and -nąć',
          cols: [{ label: 'on', tint: 'm' }, { label: 'ona', tint: 'f' }, { label: 'oni', tint: 'm' }, { label: 'one', tint: 'all' }],
          rows: [
            { who: 'wziąć, to take', cells: ['wzi[ą]ł', 'wzi[ę]ła', 'wzi[ę]li', 'wzi[ę]ły'] },
            { who: 'zacząć, to begin', cells: ['zacz[ą]ł', 'zacz[ę]ła', 'zacz[ę]li', 'zacz[ę]ły'] },
            { who: 'odpocząć, to rest', cells: ['odpocz[ą]ł', 'odpocz[ę]ła', 'odpocz[ę]li', 'odpocz[ę]ły'] },
            { who: 'zamknąć, to close', cells: ['zamkn[ą]ł', 'zamkn[ę]ła', 'zamkn[ę]li', 'zamkn[ę]ły'] },
            { who: 'zmarznąć, to get cold', cells: ['zmarzł', 'zmarzła', 'zmarzli', 'zmarzły'] },
          ] },
        { title: 'móc, can: singular',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: 'ja', cells: ['m[o]głem', 'm[o]głam', '—'] },
            { who: 'ty', cells: ['m[o]głeś', 'm[o]głaś', '—'] },
            { who: 'on / ona / ono', cells: ['m[ó]gł', 'm[o]gła', 'm[o]gło'] },
          ] },
      ],
      rules: [
        { t: 'Jeść, usiąść and znaleźć have a, which turns to e only before -li', ex: 'Marek jadł zupę, a jego bracia jedli pizzę.', en: 'Marek was eating soup and his brothers were eating pizza.' },
        { t: 'Ó appears only in the bare “on” form. Any added ending brings o back', ex: 'On nie mógł przyjść, ale ja mogłem.', en: 'He couldn’t come, but I could.' },
        { t: 'Verbs in -ąć keep ą only in the masculine singular and have ę everywhere else', ex: 'Tomek wziął kawę, a Anna wzięła herbatę.', en: 'Tomek took a coffee and Anna took a tea.' },
        { t: 'Some -nąć verbs that describe a change of state lose -ną- in the past', ex: 'Zmarzłam na przystanku.', en: 'I got cold at the bus stop. (a woman speaking)' },
      ],
      watch: [
        'A man says wziąłem and zacząłem, with ą. A woman says wzięłam and zaczęłam, with ę.',
        'Mógł and niósł have ó, but mogłem and niosłem do not.',
        'Wziąć has no n in it. “Wzięłam”, never “wzięnłam”.',
        '“Kto” always takes the masculine singular, whoever the answer turns out to be: Kto wziął mój długopis?',
      ],
    },
    {
      id: 'past-plural', pl: 'Liczba mnoga', en: 'Plural: -li or -ły', q: 'oni byli, one były',
      summary: 'The plural has two sets of endings. Groups that include at least one man take -li. Groups of women, children, animals and things take -ły.',
      tables: [
        { title: 'The two plurals',
          cols: [{ label: 'Groups with a man (masculine personal)', tint: 'm' }, { label: 'Everyone and everything else', tint: 'all' }],
          rows: [
            { who: 'my', cells: ['robi[liśmy]', 'robi[łyśmy]'] },
            { who: 'wy', cells: ['robi[liście]', 'robi[łyście]'] },
            { who: 'oni / one', cells: ['robi[li]', 'robi[ły]'] },
          ] },
        { title: 'Which subject takes which form',
          cols: [{ label: 'Example subjects', tint: 'all' }, { label: 'Past of być', tint: 'all' }],
          rows: [
            { who: 'Men', cells: ['studenci, bracia, panowie', 'by[li]'] },
            { who: 'Mixed groups', cells: ['rodzice, ludzie, Anna i Piotr', 'by[li]'] },
            { who: 'Women', cells: ['siostry, koleżanki, Anna i Maria', 'by[ły]'] },
            { who: 'Children', cells: ['dzieci', 'by[ły]'] },
            { who: 'Animals', cells: ['psy, koty', 'by[ły]'] },
            { who: 'Things', cells: ['domy, samochody, książki, okna', 'by[ły]'] },
          ] },
      ],
      rules: [
        { t: 'One man in the group is enough for -li', ex: 'Anna i Piotr byli w kinie.', en: 'Anna and Piotr were at the cinema.' },
        { t: 'Groups of women take -ły', ex: 'Anna i Maria były w kinie.', en: 'Anna and Maria were at the cinema.' },
        { t: 'Masculine nouns for animals and things also take -ły', ex: 'Psy spały, a samochody stały przed domem.', en: 'The dogs were asleep and the cars stood in front of the house.' },
        { t: 'Stem changes follow the ending: e with -li, a with -ły', ex: 'Oni mieli czas, one nie miały.', en: 'They (the men) had time, they (the women) didn’t.' },
      ],
      watch: [
        'Dzieci takes -ły even when all the children are boys, because the word itself is not masculine personal: Dzieci spały.',
        'Rodzice, ludzie and dziadkowie count as groups with a man, so they take -li.',
        'In my and wy forms think about who is in the group. Two women say byłyśmy. A woman and a man say byliśmy.',
      ],
    },
  ],

  sentences: [
    // Regularne
    { c: 'past-regular', p: 'ja', s: 'Wczoraj{yesterday} ___ książkę{book|f}.', base: 'czytać', hint: 'ja, a woman', gloss: 'to read', a: ['czytałam'], en: 'Yesterday I was reading a book.', why: 'Drop -ć from czytać and add -ł-. A woman speaking about herself uses -am: czytałam.' },
    { c: 'past-regular', p: 'on', s: 'Marek{Marek|m1} ___ wczoraj{yesterday} obiad{dinner|m2}.', base: 'gotować', gloss: 'to cook', a: ['gotował'], en: 'Marek cooked dinner yesterday.', why: 'Marek is “on”, so the form is the bare stem with -ł. Verbs in -ować keep -owa- in the past.' },
    { c: 'past-regular', p: 'ty', s: 'Co{what} ___ w{at} weekend{weekend|m2}, Kasiu{Kasia|f}?', base: 'robić', hint: 'ty, a woman', gloss: 'to do', a: ['robiłaś'], en: 'What did you do at the weekend, Kasia?', why: 'Speaking to one woman: robi- plus -łaś.' },
    { c: 'past-regular', p: 'ona', s: 'Moja{my|f} babcia{grandma|f} ___ w{in} Krakowie{Kraków|m2}.', base: 'mieszkać', gloss: 'to live', a: ['mieszkała'], en: 'My grandma lived in Kraków.', why: 'Babcia is feminine, so “she” takes -ła.' },
    { c: 'past-regular', p: 'ono', s: 'Dziecko{child|n} ___ mleko{milk|n}.', base: 'pić', gloss: 'to drink', a: ['piło'], en: 'The child was drinking milk.', why: 'Dziecko is a neuter noun, so the verb takes -ło.' },
    { c: 'past-regular', p: 'ty', s: 'Czy{(question word)} ___ już{already} bilety{tickets|m2.pl}, Tomku{Tomek|m1}?', base: 'kupić', hint: 'ty, a man', gloss: 'to buy', a: ['kupiłeś'], en: 'Have you bought the tickets yet, Tomek?', why: 'Speaking to one man: kupi- plus -łeś.' },
    { c: 'past-regular', p: 'my', s: 'My{we} ___ całą{whole|f} noc{night|f}.', base: 'tańczyć', hint: 'my, a group of women', gloss: 'to dance', a: ['tańczyłyśmy'], en: 'We danced all night.', why: 'A group of women speaking about themselves: tańczy- plus -łyśmy.' },
    { c: 'past-regular', p: 'oni', s: 'Oni{they|m1.pl} ___ wczoraj{yesterday} film{film|m2}.', base: 'oglądać', gloss: 'to watch', a: ['oglądali'], en: 'They watched a film yesterday.', why: '“Oni” is a group with at least one man, so the ending is -li.' },
    { c: 'past-regular', p: 'ja', s: 'W{on} sobotę{Saturday|f} ___ do{until} wieczora{evening|m2}.', base: 'pracować', hint: 'ja, a man', gloss: 'to work', a: ['pracowałem'], en: 'On Saturday I worked until the evening.', why: 'A man speaking about himself uses -łem. The past keeps -owa-, unlike the present pracuję.' },
    { c: 'past-regular', p: 'wy', s: 'Czy{(question word)} ___ wczoraj{yesterday} do{to} mamy{mum|f}?', base: 'dzwonić', hint: 'wy, a group of men', gloss: 'to phone', a: ['dzwoniliście'], en: 'Did you phone mum yesterday?', why: 'Speaking to several men: dzwoni- plus -liście.' },
    { c: 'past-regular', p: 'ona', s: 'Ewa{Ewa|f} ___ się{herself} polskiego{Polish|m} w{at} szkole{school|f}.', base: 'uczyć', gloss: 'to teach (with się: to learn)', a: ['uczyła'], en: 'Ewa learned Polish at school.', why: 'Ewa is “ona”, so uczy- plus -ła. “Się” does not change.' },
    { c: 'past-regular', p: 'on', s: 'Mój{my|m} brat{brother|m1} ___ list{letter|m2} do{to} babci{grandma|f}.', base: 'napisać', gloss: 'to write', a: ['napisał'], en: 'My brother wrote a letter to grandma.', why: 'The past comes from the infinitive napisać, not from the present stem pisz-. “He” takes plain -ł.' },
    { c: 'past-regular', p: 'ty', s: 'Wczoraj{yesterday} bardzo{very} długo{long} ___.', base: 'spać', hint: 'ty, a man', gloss: 'to sleep', a: ['spałeś'], en: 'You slept for a very long time yesterday.', why: 'Speaking to one man: spa- plus -łeś. The present is śpisz, but the past follows the infinitive.' },
    { c: 'past-regular', p: 'ja', s: 'Jako{as} dziecko{child|n} nie{not} ___ zupy{soup|f}.', base: 'lubić', hint: 'ja, a woman', gloss: 'to like', a: ['lubiłam'], en: 'As a child I didn’t like soup.', why: 'A woman speaking about herself: lubi- plus -łam.' },

    // Czasowniki -eć
    { c: 'past-ec', p: 'ja', s: 'Wczoraj{yesterday} nie{not} ___ czasu{time|m2}.', base: 'mieć', hint: 'ja, a man', gloss: 'to have', a: ['miałem'], en: 'I didn’t have time yesterday.', why: 'Before ł the e of mieć turns into a: mia- plus -łem for a man.' },
    { c: 'past-ec', p: 'ona', s: 'Anna{Anna|f} ___ kupić{to buy} nowy{new|m} telefon{phone|m2}.', base: 'chcieć', gloss: 'to want', a: ['chciała'], en: 'Anna wanted to buy a new phone.', why: 'Before ł the e becomes a: chcia- plus -ła for “she”.' },
    { c: 'past-ec', p: 'ty', s: 'Czy{(question word)} ___ już{already} ten{this|m} film{film|m2}?', base: 'widzieć', hint: 'ty, a woman', gloss: 'to see', a: ['widziałaś'], en: 'Have you seen this film yet?', why: 'The e becomes a before ł, and one woman being spoken to takes -łaś.' },
    { c: 'past-ec', p: 'oni', s: 'Moi{my|m.pl} rodzice{parents|m1.pl} ___ duży{big|m} dom{house|m2}.', base: 'mieć', gloss: 'to have', a: ['mieli'], en: 'My parents had a big house.', why: 'Parents are a mixed group, so the ending is -li. Before l the e stays: mieli, not “miali”.' },
    { c: 'past-ec', p: 'on', s: 'Piotr{Piotr|m1} ___ wczoraj{yesterday} długo{long} pracować{to work}.', base: 'musieć', gloss: 'to have to', a: ['musiał'], en: 'Piotr had to work for a long time yesterday.', why: 'The e of musieć becomes a before ł. “He” takes plain -ł.' },
    { c: 'past-ec', p: 'ja', s: 'Nie{not} ___, że{that} masz{you have} brata{brother|m1}.', base: 'wiedzieć', hint: 'ja, a woman', gloss: 'to know', a: ['wiedziałam'], en: 'I didn’t know you had a brother.', why: 'The e becomes a before ł, and a woman speaking about herself uses -łam.' },
    { c: 'past-ec', p: 'oni', s: 'Studenci{students|m1.pl} nie{not} ___ pytania{question|n}.', base: 'rozumieć', gloss: 'to understand', a: ['rozumieli'], en: 'The students didn’t understand the question.', why: 'Studenci is a group with men, so -li. Before l the e stays: rozumieli.' },
    { c: 'past-ec', p: 'one', s: 'Moje{my|f.pl} siostry{sisters|f.pl} ___ jechać{to go} nad{to} morze{sea|n}.', base: 'chcieć', gloss: 'to want', a: ['chciały'], en: 'My sisters wanted to go to the seaside.', why: 'A group of women takes -ły. That ending has ł, so the vowel is a again: chciały.' },
    { c: 'past-ec', p: 'on', s: 'Kot{cat|m1} ___ na{on} kanapie{sofa|f}.', base: 'leżeć', gloss: 'to lie', a: ['leżał'], en: 'The cat was lying on the sofa.', why: 'Kot is masculine, so plain -ł. The e of leżeć becomes a before it.' },
    { c: 'past-ec', p: 'ja', s: 'Przepraszam{sorry}, ___ o{about} twoich{your|f.pl} urodzinach{birthday|f.pl}.', base: 'zapomnieć', hint: 'ja, a man', gloss: 'to forget', a: ['zapomniałem'], en: 'Sorry, I forgot about your birthday.', why: 'The e becomes a before ł, and a man speaking about himself uses -łem.' },
    { c: 'past-ec', p: 'ono', s: 'Dziecko{child|n} ___ lody{ice cream|m2.pl}.', base: 'chcieć', gloss: 'to want', a: ['chciało'], en: 'The child wanted ice cream.', why: 'Dziecko is neuter, so -ło. The vowel before ł is a.' },
    { c: 'past-ec', p: 'wy', s: 'Czy{(question word)} ___ tę{this|f} piosenkę{song|f}?', base: 'słyszeć', hint: 'wy, a group of men', gloss: 'to hear', a: ['słyszeliście'], en: 'Have you heard this song?', why: 'Speaking to several men: -liście. Before l the e stays, so słyszeliście.' },
    { c: 'past-ec', p: 'my', s: 'Wczoraj{yesterday} ___ o{about} tobie{you}.', base: 'myśleć', hint: 'my, a group of women', gloss: 'to think', a: ['myślałyśmy'], en: 'We were thinking about you yesterday.', why: 'Women speaking about themselves use -łyśmy. Because of the ł the vowel is a: myślałyśmy.' },
    { c: 'past-ec', p: 'one', s: 'Ola{Ola|f} i{and} Marta{Marta|f} ___ w{in} kawiarni{café|f}.', base: 'siedzieć', gloss: 'to sit', a: ['siedziały'], en: 'Ola and Marta were sitting in a café.', why: 'Two women take -ły, and before ł the e becomes a.' },
    { c: 'past-ec', p: 'on', s: 'Co{what} ___ nauczyciel{teacher|m1}?', base: 'powiedzieć', gloss: 'to say', a: ['powiedział'], en: 'What did the teacher say?', why: 'Nauczyciel is a man, so plain -ł. The e of powiedzieć becomes a before it.' },
    { c: 'past-ec', p: 'my', s: 'Nic{nothing} o{about} tym{that|n} nie{not} ___.', base: 'wiedzieć', hint: 'my, men and women', gloss: 'to know', a: ['wiedzieliśmy'], en: 'We knew nothing about that.', why: 'A mixed group speaking about itself uses -liśmy. Before l the e stays: wiedzieliśmy.' },

    // Być
    { c: 'past-byc', p: 'ja', s: 'Wczoraj{yesterday} ___ w{at} kinie{cinema|n}.', base: 'być', hint: 'ja, a man', gloss: 'to be', a: ['byłem'], en: 'Yesterday I was at the cinema.', why: 'By- plus -łem for a man speaking about himself.' },
    { c: 'past-byc', p: 'ty', s: 'Gdzie{where} ___ wczoraj{yesterday}, Magdo{Magda|f}?', base: 'być', hint: 'ty, a woman', gloss: 'to be', a: ['byłaś'], en: 'Where were you yesterday, Magda?', why: 'Speaking to one woman: by- plus -łaś.' },
    { c: 'past-byc', p: 'on', s: 'Ten{this|m} film{film|m2} ___ bardzo{very} dobry{good|m}.', base: 'być', gloss: 'to be', a: ['był'], en: 'This film was very good.', why: 'Film is a masculine noun, so the verb is był.' },
    { c: 'past-byc', p: 'ona', s: 'Pogoda{weather|f} ___ piękna{beautiful|f}.', base: 'być', gloss: 'to be', a: ['była'], en: 'The weather was beautiful.', why: 'Pogoda is feminine, so była. Things follow their grammatical gender.' },
    { c: 'past-byc', p: 'ono', s: 'To{this|n} mieszkanie{flat|n} ___ drogie{expensive|n}.', base: 'być', gloss: 'to be', a: ['było'], en: 'This flat was expensive.', why: 'Mieszkanie is neuter, so było.' },
    { c: 'past-byc', p: 'my', s: 'W{at} weekend{weekend|m2} ___ u{at} babci{grandma’s|f}.', base: 'być', hint: 'my, men and women', gloss: 'to be', a: ['byliśmy'], en: 'At the weekend we were at grandma’s.', why: 'A mixed group speaking about itself uses -liśmy.' },
    { c: 'past-byc', p: 'one', s: 'Moje{my|f.pl} koleżanki{female friends|f.pl} ___ w{in} Polsce{Poland|f} w{in} maju{May|m2}.', base: 'być', gloss: 'to be', a: ['były'], en: 'My friends were in Poland in May.', why: 'Koleżanki are all women, so the plural ending is -ły.' },
    { c: 'past-byc', p: 'ono', s: 'Wczoraj{yesterday} nie{not} ___ Marka{Marek|m1} w{at} pracy{work|f}.', base: 'być', gloss: 'to be', a: ['było'], en: 'Marek wasn’t at work yesterday.', why: 'The past of “nie ma” is “nie było”. It is always neuter singular, and the missing person goes into the genitive.' },
    { c: 'past-byc', p: 'wy', s: 'Czy{(question word)} ___ już{already} w{in} Gdańsku{Gdańsk|m2}?', base: 'być', hint: 'wy, a group of women', gloss: 'to be', a: ['byłyście'], en: 'Have you been to Gdańsk yet?', why: 'Speaking to several women: by- plus -łyście.' },
    { c: 'past-byc', p: 'oni', s: 'Moi{my|m.pl} bracia{brothers|m1.pl} ___ zmęczeni{tired|m.pl}.', base: 'być', gloss: 'to be', a: ['byli'], en: 'My brothers were tired.', why: 'Brothers are men, so the plural ending is -li.' },
    { c: 'past-byc', p: 'ja', s: 'W{in} zeszłym{last|m} tygodniu{week|m2} ___ chora{ill|f}.', base: 'być', hint: 'ja, a woman', gloss: 'to be', a: ['byłam'], en: 'Last week I was ill.', why: 'A woman speaking about herself: by- plus -łam. The adjective chora is feminine too.' },
    { c: 'past-byc', p: 'ono', s: 'Rano{in the morning} ___ zimno{cold}.', base: 'być', gloss: 'to be', a: ['było'], en: 'It was cold in the morning.', why: 'Weather sentences have no real subject, so Polish uses the neuter było.' },
    { c: 'past-byc', p: 'ty', s: 'Czy{(question word)} ___ kiedyś{ever} w{in} Warszawie{Warsaw|f}, Pawle{Paweł|m1}?', base: 'być', hint: 'ty, a man', gloss: 'to be', a: ['byłeś'], en: 'Have you ever been to Warsaw, Paweł?', why: 'Speaking to one man: by- plus -łeś.' },
    { c: 'past-byc', p: 'one', s: 'Te{these|m2.pl} pierogi{pierogi|m2.pl} ___ pyszne{delicious|m2.pl}.', base: 'być', gloss: 'to be', a: ['były'], en: 'These pierogi were delicious.', why: 'Pierogi are things, not men, so the plural is były even though pieróg is a masculine noun.' },
    { c: 'past-byc', p: 'ona', s: 'Ona{she|f} ___ wtedy{then} studentką{student|f}.', base: 'być', gloss: 'to be', a: ['była'], en: 'She was a student then.', why: '“Ona” takes -ła: była.' },

    // Iść, pójść
    { c: 'past-isc', p: 'ja', s: 'Wczoraj{yesterday} ___ do{to} kina{cinema|n}.', base: 'pójść', hint: 'ja, a man', gloss: 'to go', a: ['poszedłem'], en: 'Yesterday I went to the cinema.', why: 'Masculine singular forms keep -szedł-. Add -em for “I”: poszedłem, never “poszłem”.' },
    { c: 'past-isc', p: 'ona', s: 'Anna{Anna|f} ___ do{to} sklepu{shop|m2} po{for} chleb{bread|m2}.', base: 'pójść', gloss: 'to go', a: ['poszła'], en: 'Anna went to the shop for bread.', why: 'Every form except the masculine singular drops the e and the d: poszła.' },
    { c: 'past-isc', p: 'on', s: 'Marek{Marek|m1} ___ do{to} domu{home|m2} o{at} ósmej{eight|f}.', base: 'przyjść', gloss: 'to come', a: ['przyszedł'], en: 'Marek came home at eight.', why: 'Przyjść is przy- plus iść, so for a man it is przy- plus szedł.' },
    { c: 'past-isc', p: 'ty', s: 'Kiedy{when} cię{you} zobaczyłam{I saw|f}, ___ do{to} pracy{work|f}.', base: 'iść', hint: 'ty, a man', gloss: 'to go, to walk', a: ['szedłeś'], en: 'When I saw you, you were walking to work.', why: 'Speaking to one man: szedł- plus -eś. Iść, not pójść, because he was on his way.' },
    { c: 'past-isc', p: 'one', s: 'Dzieci{children|n.pl} ___ już{already} do{to} szkoły{school|f}.', base: 'pójść', gloss: 'to go', a: ['poszły'], en: 'The children have already gone to school.', why: 'Dzieci is not a masculine personal noun, so the plural is -ły: poszły.' },
    { c: 'past-isc', p: 'oni', s: 'Moi{my|m.pl} koledzy{friends|m1.pl} ___ na{to} mecz{match|m2}.', base: 'pójść', gloss: 'to go', a: ['poszli'], en: 'My friends went to the match.', why: 'Koledzy are men, so the ending is -li. The plural has no e or d: poszli.' },
    { c: 'past-isc', p: 'ty', s: 'O{at} której{what time|f} ___ z{from} domu{home|m2}, Ewo{Ewa|f}?', base: 'wyjść', hint: 'ty, a woman', gloss: 'to leave, to go out', a: ['wyszłaś'], en: 'What time did you leave home, Ewa?', why: 'Wy- plus the feminine stem szła-, plus -ś for “you”.' },
    { c: 'past-isc', p: 'wy', s: 'Dlaczego{why} nie{not} ___ na{to} imprezę{party|f}?', base: 'przyjść', hint: 'wy, men and women', gloss: 'to come', a: ['przyszliście'], en: 'Why didn’t you come to the party?', why: 'Speaking to a mixed group: przy- plus szli plus -ście.' },
    { c: 'past-isc', p: 'ona', s: 'Nauczycielka{teacher|f} ___ do{into} klasy{classroom|f}.', base: 'wejść', gloss: 'to come in, to enter', a: ['weszła'], en: 'The teacher came into the classroom.', why: 'Feminine of wejść is weszła. The e sits after the w because “wszła” would be hard to say.' },
    { c: 'past-isc', p: 'on', s: 'Tomek{Tomek|m1} ___ do{into} pokoju{room|m2} i{and} zamknął{closed|m} drzwi{door|n.pl}.', base: 'wejść', gloss: 'to come in, to enter', a: ['wszedł'], en: 'Tomek came into the room and closed the door.', why: 'Masculine of wejść is wszedł: w- plus szedł, with no extra e. Compare the feminine weszła.' },
    { c: 'past-isc', p: 'my', s: '___ powoli{slowly}, bo{because} padał{was falling|m} deszcz{rain|m2}.', base: 'iść', hint: 'my, a group of women', gloss: 'to go, to walk', a: ['Szłyśmy'], en: 'We were walking slowly because it was raining.', why: 'Women speaking about themselves: the stem szły- plus -śmy.' },
    { c: 'past-isc', p: 'my', s: 'Po{after} obiedzie{dinner|m2} ___ na{for} spacer{walk|m2}.', base: 'pójść', hint: 'my, men and women', gloss: 'to go', a: ['poszliśmy'], en: 'After dinner we went for a walk.', why: 'A mixed group speaking about itself: poszli plus -śmy.' },
    { c: 'past-isc', p: 'one', s: 'Ola{Ola|f} i{and} Kasia{Kasia|f} ___ wczoraj{yesterday} do{to} teatru{theatre|m2}.', base: 'pójść', gloss: 'to go', a: ['poszły'], en: 'Ola and Kasia went to the theatre yesterday.', why: 'Two women take the -ły plural: poszły.' },
    { c: 'past-isc', p: 'ono', s: 'Dziecko{child|n} ___ samo{alone|n} do{to} szkoły{school|f}.', base: 'pójść', gloss: 'to go', a: ['poszło'], en: 'The child went to school alone.', why: 'Dziecko is neuter, so po- plus szło.' },
    { c: 'past-isc', p: 'ja', s: '___ ulicą{along the street|f} i{and} nagle{suddenly} zobaczyłem{I saw|m} Annę{Anna|f}.', base: 'iść', hint: 'ja, a man', gloss: 'to go, to walk', a: ['Szedłem'], en: 'I was walking along the street and suddenly I saw Anna.', why: 'A man speaking about himself: szedł- plus -em. The ending of zobaczyłem shows the speaker is a man.' },
    { c: 'past-isc', p: 'on', s: 'Mój{my|m} syn{son|m1} ___ już{already} spać{to sleep}.', base: 'pójść', gloss: 'to go', a: ['poszedł'], en: 'My son has already gone to bed.', why: 'Syn is masculine singular, the one form that keeps the e and the d: poszedł.' },
    { c: 'past-isc', p: 'oni', s: 'Goście{guests|m1.pl} ___ o{at} północy{midnight|f}.', base: 'wyjść', gloss: 'to leave, to go out', a: ['wyszli'], en: 'The guests left at midnight.', why: 'Goście counts as a group with men, so wy- plus szli.' },

    // Nieregularne
    { c: 'past-irregular', p: 'ja', s: 'Na{for} śniadanie{breakfast|n} ___ jajka{eggs|n.pl}.', base: 'jeść', hint: 'ja, a man', gloss: 'to eat', a: ['jadłem'], en: 'I had eggs for breakfast.', why: 'The past stem of jeść is jad-. A man speaking about himself adds -łem.' },
    { c: 'past-irregular', p: 'oni', s: 'Chłopcy{boys|m1.pl} ___ pizzę{pizza|f}.', base: 'jeść', gloss: 'to eat', a: ['jedli'], en: 'The boys were eating pizza.', why: 'Boys take -li, and before -li the a of jad- turns into e: jedli.' },
    { c: 'past-irregular', p: 'ona', s: 'Ewa{Ewa|f} ___ całą{whole|f} czekoladę{chocolate bar|f}.', base: 'zjeść', gloss: 'to eat up', a: ['zjadła'], en: 'Ewa ate the whole chocolate bar.', why: 'Zjeść follows jeść: stem zjad- plus -ła for “she”.' },
    { c: 'past-irregular', p: 'ja', s: 'Nie{not} ___ wczoraj{yesterday} przyjść{to come}, bo{because} byłem{I was|m} chory{ill|m}.', base: 'móc', hint: 'ja, a man', gloss: 'can, to be able to', a: ['mogłem'], en: 'I couldn’t come yesterday because I was ill.', why: 'The past stem of móc is mog-. The ó appears only in mógł, so with the ending -em it is mogłem.' },
    { c: 'past-irregular', p: 'on', s: 'Paweł{Paweł|m1} nie{not} ___ znaleźć{to find} kluczy{keys|m2.pl}.', base: 'móc', gloss: 'can, to be able to', a: ['mógł'], en: 'Paweł couldn’t find his keys.', why: 'In the bare “on” form the o of mog- becomes ó: mógł.' },
    { c: 'past-irregular', p: 'ona', s: 'Marta{Marta|f} ___ mi{me} zrobić{to do} zakupy{shopping|m2.pl}.', base: 'pomóc', gloss: 'to help', a: ['pomogła'], en: 'Marta helped me do the shopping.', why: 'Pomóc follows móc: stem pomog-. The feminine has plain o: pomogła.' },
    { c: 'past-irregular', p: 'on', s: 'Kelner{waiter|m1} ___ nam{us} kawę{coffee|f}.', base: 'przynieść', gloss: 'to bring', a: ['przyniósł'], en: 'The waiter brought us coffee.', why: 'The past stem of -nieść is nios-, and in the bare “on” form o becomes ó: przyniósł.' },
    { c: 'past-irregular', p: 'ja', s: '___ ci{you} kwiaty{flowers|m2.pl}.', base: 'przynieść', hint: 'ja, a man', gloss: 'to bring', a: ['Przyniosłem'], en: 'I’ve brought you flowers.', why: 'The ó appears only in przyniósł. Once an ending is added the o comes back: przyniosłem.' },
    { c: 'past-irregular', p: 'ona', s: 'Babcia{grandma|f} ___ ciężką{heavy|f} torbę{bag|f}.', base: 'nieść', gloss: 'to carry', a: ['niosła'], en: 'Grandma was carrying a heavy bag.', why: 'Stem nios- plus -ła. The feminine has plain o.' },
    { c: 'past-irregular', p: 'on', s: 'Tomek{Tomek|m1} ___ okno{window|n}, bo{because} było{it was|n} zimno{cold}.', base: 'zamknąć', gloss: 'to close', a: ['zamknął'], en: 'Tomek closed the window because it was cold.', why: 'Verbs in -ąć keep ą in the masculine singular: zamknął.' },
    { c: 'past-irregular', p: 'ona', s: 'Anna{Anna|f} ___ drzwi{door|n.pl} na{with} klucz{key|m2}.', base: 'zamknąć', gloss: 'to close', a: ['zamknęła'], en: 'Anna locked the door.', why: 'Outside the masculine singular ą turns into ę: zamknęła.' },
    { c: 'past-irregular', p: 'ja', s: '___ parasol{umbrella|m2}, bo{because} padał{was falling|m} deszcz{rain|m2}.', base: 'wziąć', hint: 'ja, a woman', gloss: 'to take', a: ['Wzięłam'], en: 'I took an umbrella because it was raining.', why: 'Feminine forms of wziąć have ę: wzię- plus -łam. A man would say wziąłem.' },
    { c: 'past-irregular', p: 'on', s: 'Kto{who} ___ mój{my|m} długopis{pen|m2}?', base: 'wziąć', gloss: 'to take', a: ['wziął'], en: 'Who took my pen?', why: '“Kto” always takes the masculine singular, and that form keeps ą: wziął.' },
    { c: 'past-irregular', p: 'on', s: 'Film{film|m2} ___ się{itself} o{at} ósmej{eight|f}.', base: 'zacząć', gloss: 'to begin', a: ['zaczął'], en: 'The film started at eight.', why: 'Film is masculine singular, so ą stays: zaczął.' },
    { c: 'past-irregular', p: 'ona', s: 'Lekcja{lesson|f} ___ się{itself} o{at} dziewiątej{nine|f}.', base: 'zacząć', gloss: 'to begin', a: ['zaczęła'], en: 'The lesson started at nine.', why: 'Lekcja is feminine, so ą turns into ę: zaczęła.' },
    { c: 'past-irregular', p: 'ty', s: 'Gdzie{where} ___ ten{this|m} portfel{wallet|m2}?', base: 'znaleźć', hint: 'ty, a man', gloss: 'to find', a: ['znalazłeś'], en: 'Where did you find this wallet?', why: 'The past stem of znaleźć is znalaz-. Speaking to one man adds -łeś.' },
    { c: 'past-irregular', p: 'oni', s: 'Moi{my|m.pl} sąsiedzi{neighbours|m1.pl} ___ psa{dog|m1} w{in} parku{park|m2}.', base: 'znaleźć', gloss: 'to find', a: ['znaleźli'], en: 'My neighbours found a dog in the park.', why: 'Before -li the a of znalaz- turns into e and z softens to ź: znaleźli.' },
    { c: 'past-irregular', p: 'ona', s: 'Babcia{grandma|f} ___ ciasto{cake|n} na{for} moje{my|f.pl} urodziny{birthday|f.pl}.', base: 'upiec', gloss: 'to bake', a: ['upiekła'], en: 'Grandma baked a cake for my birthday.', why: 'Infinitives in -c hide a k or a g. Upiec has the stem upiek-, so upiekła.' },
    { c: 'past-irregular', p: 'on', s: 'Pies{dog|m1} ___ za{after} piłką{ball|f}.', base: 'biec', gloss: 'to run', a: ['biegł'], en: 'The dog was running after the ball.', why: 'Biec hides a g: the stem is bieg-. Pies is masculine, so biegł.' },
    { c: 'past-irregular', p: 'ona', s: 'Monika{Monika|f} ___ przy{by} oknie{window|n}.', base: 'usiąść', gloss: 'to sit down', a: ['usiadła'], en: 'Monika sat down by the window.', why: 'The past stem of usiąść is usiad-. “She” adds -ła.' },
    { c: 'past-irregular', p: 'oni', s: 'Goście{guests|m1.pl} ___ przy{at} stole{table|m2}.', base: 'usiąść', gloss: 'to sit down', a: ['usiedli'], en: 'The guests sat down at the table.', why: 'Before -li the a of usiad- turns into e, just as in jedli: usiedli.' },
    { c: 'past-irregular', p: 'ja', s: 'Na{at} przystanku{bus stop|m2} bardzo{very} ___.', base: 'zmarznąć', hint: 'ja, a man', gloss: 'to get cold', a: ['zmarzłem', 'zmarznąłem'], en: 'I got very cold at the bus stop.', why: 'Zmarznąć loses -ną- in the past. The stem is zmarz-, plus -łem for a man.' },
    { c: 'past-irregular', p: 'my', s: 'Po{after} pracy{work|f} ___ trochę{a little} w{in} parku{park|m2}.', base: 'odpocząć', hint: 'my, a group of women', gloss: 'to rest', a: ['odpoczęłyśmy'], en: 'After work we rested a little in the park.', why: 'Only the masculine singular keeps ą. Women speaking about themselves say odpoczę- plus -łyśmy.' },

    // Liczba mnoga
    { c: 'past-plural', p: 'oni', s: 'Chłopcy{boys|m1.pl} ___ w{in} parku{park|m2}.', base: 'biegać', gloss: 'to run around', a: ['biegali'], en: 'The boys were running around in the park.', why: 'Boys are male people, so the plural ending is -li.' },
    { c: 'past-plural', p: 'one', s: 'Dzieci{children|n.pl} ___ się{themselves} w{in} ogrodzie{garden|m2}.', base: 'bawić', gloss: 'to amuse (with się: to play)', a: ['bawiły'], en: 'The children were playing in the garden.', why: 'Dzieci is not a masculine personal noun, so it takes -ły even if the children are boys.' },
    { c: 'past-plural', p: 'oni', s: 'Anna{Anna|f} i{and} Piotr{Piotr|m1} ___ razem{together} kolację{supper|f}.', base: 'zrobić', gloss: 'to make', a: ['zrobili'], en: 'Anna and Piotr made supper together.', why: 'One man in the group is enough for -li.' },
    { c: 'past-plural', p: 'one', s: 'Anna{Anna|f} i{and} Maria{Maria|f} ___ razem{together} obiad{dinner|m2}.', base: 'zrobić', gloss: 'to make', a: ['zrobiły'], en: 'Anna and Maria made dinner together.', why: 'A group of women only takes -ły.' },
    { c: 'past-plural', p: 'one', s: 'Koty{cats|m2.pl} ___ na{on} łóżku{bed|n}.', base: 'spać', gloss: 'to sleep', a: ['spały'], en: 'The cats were sleeping on the bed.', why: 'Animals take -ły, even though kot is a masculine noun.' },
    { c: 'past-plural', p: 'one', s: 'Te{these|m2.pl} samochody{cars|m2.pl} ___ bardzo{very} dużo{a lot}.', base: 'kosztować', gloss: 'to cost', a: ['kosztowały'], en: 'These cars cost a great deal.', why: 'Things take -ły. Only nouns for male people count as masculine personal.' },
    { c: 'past-plural', p: 'oni', s: 'Moi{my|m.pl} bracia{brothers|m1.pl} ___ w{in} Anglii{England|f}.', base: 'pracować', gloss: 'to work', a: ['pracowali'], en: 'My brothers worked in England.', why: 'Brothers are men, so -li.' },
    { c: 'past-plural', p: 'one', s: 'Moje{my|f.pl} siostry{sisters|f.pl} ___ mi{me} prezent{present|m2}.', base: 'kupić', gloss: 'to buy', a: ['kupiły'], en: 'My sisters bought me a present.', why: 'Sisters are women, so -ły.' },
    { c: 'past-plural', p: 'oni', s: 'Rodzice{parents|m1.pl} ___ na{for} mnie{me} przed{in front of} szkołą{school|f}.', base: 'czekać', gloss: 'to wait', a: ['czekali'], en: 'My parents were waiting for me in front of the school.', why: 'Rodzice means mum and dad, a mixed group, so -li.' },
    { c: 'past-plural', p: 'oni', s: 'Ludzie{people|m1.pl} ___ na{at} przystanku{bus stop|m2}.', base: 'stać', gloss: 'to stand', a: ['stali'], en: 'People were standing at the bus stop.', why: 'Ludzie is a masculine personal noun, so -li.' },
    { c: 'past-plural', p: 'one', s: 'Dzieci{children|n.pl} ___ zupę{soup|f}.', base: 'jeść', gloss: 'to eat', a: ['jadły'], en: 'The children were eating soup.', why: 'Dzieci takes -ły, and with ł the stem keeps its a: jadły. Compare jedli for men.' },
    { c: 'past-plural', p: 'oni', s: 'Lekarze{doctors|m1.pl} ___ dużo{a lot of} pracy{work|f}.', base: 'mieć', gloss: 'to have', a: ['mieli'], en: 'The doctors had a lot of work.', why: 'Lekarze is masculine personal, so -li, and before l the e of mieć stays: mieli.' },
    { c: 'past-plural', p: 'one', s: 'Te{these|f.pl} kobiety{women|f.pl} ___ małe{small|n.pl} dzieci{children|n.pl}.', base: 'mieć', gloss: 'to have', a: ['miały'], en: 'These women had small children.', why: 'Women take -ły, and before ł the e of mieć becomes a: miały.' },
    { c: 'past-plural', p: 'oni', s: 'Ci{these|m.pl} panowie{gentlemen|m1.pl} ___ po_angielsku{in English}.', base: 'mówić', gloss: 'to speak', a: ['mówili'], en: 'These gentlemen were speaking English.', why: 'Panowie are men, so -li.' },
    { c: 'past-plural', p: 'one', s: 'Te{these|f.pl} panie{ladies|f.pl} ___ kawę{coffee|f}.', base: 'pić', gloss: 'to drink', a: ['piły'], en: 'These ladies were drinking coffee.', why: 'Panie are women, so -ły.' },
    { c: 'past-plural', p: 'my', s: 'Wczoraj{yesterday} ___ do{until} północy{midnight|f}.', base: 'rozmawiać', hint: 'my, two women', gloss: 'to talk', a: ['rozmawiałyśmy'], en: 'Yesterday we talked until midnight.', why: 'Two women speaking about themselves use -łyśmy.' },
    { c: 'past-plural', p: 'wy', s: 'Gdzie{where} ___ w{during} wakacje{holidays|f.pl}?', base: 'być', hint: 'wy, a man and a woman', gloss: 'to be', a: ['byliście'], en: 'Where were you during the holidays?', why: 'Speaking to a man and a woman together: one man is enough for -liście.' },
    { c: 'past-plural', p: 'oni', s: 'Moi{my|m.pl} dziadkowie{grandparents|m1.pl} ___ na{in} wsi{the countryside|f}.', base: 'mieszkać', gloss: 'to live', a: ['mieszkali'], en: 'My grandparents lived in the countryside.', why: 'Dziadkowie means grandma and grandpa, a group with a man, so -li.' },
    { c: 'past-plural', p: 'one', s: 'Listy{letters|m2.pl} ___ na{on} stole{table|m2}.', base: 'leżeć', gloss: 'to lie', a: ['leżały'], en: 'The letters were lying on the table.', why: 'Letters are things, so -ły. Before ł the e of leżeć becomes a.' },
    { c: 'past-plural', p: 'oni', s: 'Mój{my|m} syn{son|m1} i{and} jego{his|m} pies{dog|m1} ___ w{in} parku{park|m2}.', base: 'być', gloss: 'to be', a: ['byli'], en: 'My son and his dog were in the park.', why: 'The group includes a male person, the son, so the verb takes -li.' },
  ],
};
