/* Numbers: how a number changes the noun (and verb) next to it. Same format as data-past.js.
   In table cells, [square brackets] mark the part to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap.
   Sentences have no p (person); at: [row who, column label] names the table cell to highlight.
   Every sentence has kind: 'number' when the gap is the number itself, form when the gap is a noun,
   adjective or verb, or both (ordinals). form links the answer to the table that shows how the word changes:
   'noun gen.pl.f' and 'adj loc.sg.n' (case.number.gender) open that case's endings grid, 'verb past.ono' the
   past-tense tables. Genders are m1, m2, n, f; in the plural m1 means men and m2 any other masculine noun.
   Check with: node validate.js data-numbers.js NUMBERS */

const NUMBERS = {
  id: 'numbers', pl: 'Liczebniki', en: 'Numbers',
  intro: 'A number decides the case of the noun after it. One takes the singular, two to four take the nominative plural, and five and up take the genitive plural. Groups of men have their own forms, ordinals (first, second) behave like adjectives, and inside a sentence the number itself changes with the case. Start with Słownie to learn how to say the numbers themselves.',
  groups: [
    {
      id: 'num-say', pl: 'Słownie', en: 'Saying numbers', q: '47 → czterdzieści siedem',
      summary: 'Build a number from its parts, biggest first, with no word for “and”: 347 is trzysta czterdzieści siedem. The teens end in -naście, the tens in -dzieścia, -dzieści or -dziesiąt, and the hundreds in -ście, -sta or -set. Tysiąc itself follows the counting rule: dwa tysiące, pięć tysięcy.',
      tables: [
        { title: 'Units and teens',
          cols: [{ label: 'Units', tint: 'all' }, { label: 'Teens', tint: 'all' }],
          rows: [
            { who: '0 / 10', cells: ['zero', 'dziesięć'] },
            { who: '1 / 11', cells: ['jeden', 'jede[naście]'] },
            { who: '2 / 12', cells: ['dwa', 'dwa[naście]'] },
            { who: '3 / 13', cells: ['trzy', 'trzy[naście]'] },
            { who: '4 / 14', cells: ['cztery', 'czter[naście]'] },
            { who: '5 / 15', cells: ['pięć', 'pięt[naście]'] },
            { who: '6 / 16', cells: ['sześć', 'szes[naście]'] },
            { who: '7 / 17', cells: ['siedem', 'siedem[naście]'] },
            { who: '8 / 18', cells: ['osiem', 'osiem[naście]'] },
            { who: '9 / 19', cells: ['dziewięć', 'dziewięt[naście]'] },
          ] },
        { title: 'Tens and hundreds',
          cols: [{ label: 'Tens', tint: 'all' }, { label: 'Hundreds', tint: 'all' }],
          rows: [
            { who: '10 / 100', cells: ['dziesięć', 'sto'] },
            { who: '20 / 200', cells: ['dwa[dzieścia]', 'dwie[ście]'] },
            { who: '30 / 300', cells: ['trzy[dzieści]', 'trzy[sta]'] },
            { who: '40 / 400', cells: ['czter[dzieści]', 'czter[ysta]'] },
            { who: '50 / 500', cells: ['pięć[dziesiąt]', 'pięć[set]'] },
            { who: '60 / 600', cells: ['sześć[dziesiąt]', 'sześć[set]'] },
            { who: '70 / 700', cells: ['siedem[dziesiąt]', 'siedem[set]'] },
            { who: '80 / 800', cells: ['osiem[dziesiąt]', 'osiem[set]'] },
            { who: '90 / 900', cells: ['dziewięć[dziesiąt]', 'dziewięć[set]'] },
          ] },
        { title: 'Thousands',
          cols: [{ label: 'Word', tint: 'all' }, { label: 'Example', tint: 'all' }],
          rows: [
            { who: '1000', cells: ['tysiąc', 'tysiąc dwieście (1200)'] },
            { who: '2000 to 4000', cells: ['dwa, trzy, cztery tysiąc[e]', 'trzy tysiąc[e] pięćset (3500)'] },
            { who: '5000 and up', cells: ['pięć, sześć… tysię[cy]', 'dwadzieścia tysię[cy] (20 000)'] },
            { who: 'Years', cells: ['said as an ordinary number', 'tysiąc dziewięćset osiemdziesiąt dziewięć (1989)'] },
          ] },
      ],
      rules: [
        { t: 'Say the parts from biggest to smallest, with no “and”', ex: 'sto dwadzieścia trzy', en: 'one hundred and twenty-three' },
        { t: 'Twenty, thirty and forty end in -dzieścia or -dzieści, fifty to ninety in -dziesiąt', ex: 'trzydzieści, pięćdziesiąt', en: 'thirty, fifty' },
        { t: 'Two hundred is dwieście, three and four hundred take -sta, five hundred and up take -set', ex: 'dwieście, czterysta, osiemset', en: 'two hundred, four hundred, eight hundred' },
        { t: 'Tysiąc is a noun and follows the counting rule', ex: 'dwa tysiące, pięć tysięcy', en: 'two thousand, five thousand' },
      ],
      watch: [
        'Some teens change the unit: czternaście (no y), piętnaście and dziewiętnaście (t, not ć), szesnaście (no ś).',
        'Czterdzieści and czterysta drop the y of cztery.',
        'Piętnaście (15) and pięćdziesiąt (50) are easy to mix up. Listen for -naście.',
        'In the answer box, write the words separated by spaces, with no hyphens.',
      ],
    },
    {
      id: 'num-2-4', pl: 'Dwa–cztery', en: 'Two to four', q: 'dwa koty, dwie kobiety',
      summary: 'After 2, 3 and 4 the noun goes into the nominative plural and the verb is plural, just as with any plural subject. Two has a separate feminine form, dwie. Numbers ending in 2, 3 or 4 (22, 33, 104) follow the same rule, except 12, 13 and 14.',
      tables: [
        { title: 'Two, three and four with a noun',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Neuter', tint: 'n' }, { label: 'Feminine', tint: 'f' }],
          rows: [
            { who: '1', cells: ['jeden kot', 'jedno okno', 'jedna kobieta'] },
            { who: '2', cells: ['dwa kot[y]', 'dwa okn[a]', 'dw[ie] kobiet[y]'] },
            { who: '3', cells: ['trzy kot[y]', 'trzy okn[a]', 'trzy kobiet[y]'] },
            { who: '4', cells: ['cztery kot[y]', 'cztery okn[a]', 'cztery kobiet[y]'] },
            { who: '22, 23, 24', cells: ['dwadzieścia dwa kot[y]', 'dwadzieścia trzy okn[a]', 'dwadzieścia dw[ie] kobiet[y]'] },
          ] },
        { title: 'What the verb does',
          cols: [{ label: 'Present', tint: 'all' }, { label: 'Past', tint: 'all' }],
          rows: [
            { who: '1: singular', cells: ['Jedna kobieta czek[a].', 'Jedna kobieta czekał[a].'] },
            { who: '2 to 4: plural', cells: ['Dwie kobiety czekaj[ą].', 'Dwie kobiety czekał[y].'] },
          ] },
      ],
      rules: [
        { t: 'After 2, 3 and 4 the noun is in the nominative plural', ex: 'Mam dwa koty i trzy psy.', en: 'I have two cats and three dogs.' },
        { t: 'Dwie goes with feminine nouns, dwa with masculine and neuter ones', ex: 'Mam dwie siostry i dwa rowery.', en: 'I have two sisters and two bikes.' },
        { t: 'The verb is plural', ex: 'Na stole leżą cztery jabłka.', en: 'Four apples are lying on the table.' },
        { t: 'Bigger numbers that end in 2, 3 or 4 work the same way', ex: 'W klasie są dwadzieścia trzy krzesła.', en: 'There are twenty-three chairs in the classroom.' },
      ],
      watch: [
        'Jeden agrees like an adjective and the noun stays singular: jeden kot, jedna kobieta, jedno okno.',
        '12, 13 and 14 end in -naście, so they follow the five-and-up rule: dwanaście kotów, not dwanaście koty.',
        'Rok has an irregular plural: dwa lata, trzy lata, but pięć lat.',
        'Men are different: dwaj studenci or dwóch studentów, never dwa studenci. See the groups-with-men stripe.',
      ],
    },
    {
      id: 'num-5plus', pl: 'Pięć i więcej', en: 'Five and up', q: 'pięć kotów, dużo książek',
      summary: 'From 5 up the noun goes into the genitive plural and the verb is singular (neuter in the past tense). The same goes for 12 to 14, for bigger numbers ending in 5 to 9, 0 or 1, and for words of quantity: kilka, wiele, dużo, mało, ile.',
      tables: [
        { title: 'Five and up with a noun',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Neuter', tint: 'n' }, { label: 'Feminine', tint: 'f' }],
          rows: [
            { who: '5 to 21', cells: ['pięć kot[ów]', 'pięć okien', 'pięć kobiet'] },
            { who: '12, 13, 14', cells: ['dwanaście kot[ów]', 'trzynaście okien', 'czternaście kobiet'] },
            { who: '25, 31, 100', cells: ['dwadzieścia pięć kot[ów]', 'trzydzieści jeden okien', 'sto kobiet'] },
            { who: 'Quantity words', cells: ['kilka kot[ów]', 'dużo okien', 'mało kobiet'] },
          ] },
        { title: 'What the verb does',
          cols: [{ label: 'Present', tint: 'all' }, { label: 'Past', tint: 'all' }],
          rows: [
            { who: '2 to 4: plural', cells: ['Dwie kobiety czekaj[ą].', 'Dwie kobiety czekał[y].'] },
            { who: '5 and up: singular', cells: ['Pięć kobiet czek[a].', 'Pięć kobiet czekał[o].'] },
          ] },
      ],
      rules: [
        { t: 'From 5 up the noun is in the genitive plural', ex: 'Mam pięć książek.', en: 'I have five books.' },
        { t: 'The verb is singular, and in the past it takes the neuter -o', ex: 'Na przystanku czekało sześć osób.', en: 'Six people were waiting at the stop.' },
        { t: 'Kilka, wiele, dużo, mało and ile follow the same rule', ex: 'Ile masz lat?', en: 'How old are you? (literally: how many years do you have?)' },
        { t: 'Numbers ending in 1 (except 1 itself) also take the genitive plural', ex: 'Ona ma dwadzieścia jeden lat.', en: 'She is twenty-one.' },
      ],
      watch: [
        'Many genitive plurals have no ending: kobieta → kobiet, okno → okien (with an e slipping in), książka → książek.',
        'Dwadzieścia dwa, trzydzieści cztery go back to the two-to-four rule: dwadzieścia dwa koty.',
        'Pół (half), ćwierć (quarter) and tysiąc, milion also take the genitive: pół litra, tysiąc złotych.',
      ],
    },
    {
      id: 'num-men', pl: 'Mężczyźni', en: 'Groups with men', q: 'dwóch studentów, pięciu panów',
      summary: 'When the noun means men or a group with at least one man, numbers take their own forms: dwóch, trzech, czterech, pięciu, kilku, wielu, ilu. They go with the genitive plural and a singular verb. For 2 to 4 there is also an older form, dwaj, trzej, czterej, which takes the nominative plural and a plural verb.',
      tables: [
        { title: 'Numbers with men',
          cols: [{ label: 'Everyday form: genitive plural, verb singular', tint: 'm' }, { label: 'Also correct: nominative plural, verb plural', tint: 'all' }],
          rows: [
            { who: '2', cells: ['dw[óch] student[ów] przyszł[o]', 'dw[aj] studen[ci] przysz[li]'] },
            { who: '3', cells: ['trz[ech] student[ów] przyszł[o]', 'trz[ej] studen[ci] przysz[li]'] },
            { who: '4', cells: ['czter[ech] student[ów] przyszł[o]', 'czter[ej] studen[ci] przysz[li]'] },
            { who: '5 and up', cells: ['pię[ciu] student[ów] przyszł[o]', '—'] },
            { who: 'Some, many, how many', cells: ['kil[ku], wiel[u], il[u] student[ów]', '—'] },
          ] },
        { title: 'The same number with other nouns',
          cols: [{ label: 'Men', tint: 'm' }, { label: 'Women', tint: 'f' }, { label: 'Things and animals', tint: 'all' }],
          rows: [
            { who: '2', cells: ['dwóch braci', 'dwie siostry', 'dwa psy'] },
            { who: '5', cells: ['pięciu braci', 'pięć sióstr', 'pięć psów'] },
            { who: 'both', cells: ['obaj bracia, obu braci', 'obie siostry', 'oba psy'] },
          ] },
      ],
      rules: [
        { t: 'With men use dwóch, trzech, czterech, pięciu and so on, with the genitive plural', ex: 'W pokoju jest trzech studentów.', en: 'There are three students in the room.' },
        { t: 'The verb is singular, neuter in the past', ex: 'Na spotkanie przyszło pięciu panów.', en: 'Five gentlemen came to the meeting.' },
        { t: 'Dwaj, trzej and czterej take the nominative plural and a plural verb', ex: 'Dwaj bracia mieszkają w Krakowie.', en: 'Two brothers live in Kraków.' },
        { t: 'Kilku, wielu and ilu are the forms for men', ex: 'Ilu masz kolegów w pracy?', en: 'How many colleagues do you have at work?' },
      ],
      watch: [
        'This only applies to men and mixed groups. Dogs, women and children use the ordinary forms: dwa psy, dwie kobiety, pięć dzieci.',
        'Dzieci and osoby are not counted as men: pięć osób, dwoje dzieci.',
        'Dwaj, trzej, czterej exist only for 2, 3 and 4. From five on there is only pięciu, sześciu.',
      ],
    },
    {
      id: 'num-ordinal', pl: 'Porządkowe', en: 'First, second, third', q: 'pierwszy, drugi, trzeci',
      summary: 'Ordinal numbers are adjectives, so they take adjective endings and agree with their noun in gender, number and case. Drugi and trzeci end in -i and take the soft endings. They are used for floors, dates, clock times and anything in an order.',
      tables: [
        { title: 'Ordinals in the nominative',
          cols: [{ label: 'Masculine', tint: 'm' }, { label: 'Feminine', tint: 'f' }, { label: 'Neuter', tint: 'n' }],
          rows: [
            { who: '1st', cells: ['pierwsz[y]', 'pierwsz[a]', 'pierwsz[e]'] },
            { who: '2nd', cells: ['drug[i]', 'drug[a]', 'drug[ie]'] },
            { who: '3rd', cells: ['trzec[i]', 'trzeci[a]', 'trzeci[e]'] },
            { who: '4th, 5th, 6th', cells: ['czwart[y], piąt[y], szóst[y]', 'czwart[a], piąt[a], szóst[a]', 'czwart[e], piąt[e], szóst[e]'] },
            { who: '7th, 8th, 9th, 10th', cells: ['siódm[y], ósm[y], dziewiąt[y], dziesiąt[y]', 'siódm[a], ósm[a], dziewiąt[a], dziesiąt[a]', 'siódm[e], ósm[e], dziewiąt[e], dziesiąt[e]'] },
            { who: '20th, 100th', cells: ['dwudziest[y], set[ny]', 'dwudziest[a], setn[a]', 'dwudziest[e], setn[e]'] },
          ] },
        { title: 'Where you meet them',
          cols: [{ label: 'Pattern', tint: 'all' }, { label: 'Example', tint: 'all' }],
          rows: [
            { who: 'Today’s date', cells: ['day in the nominative, month in the genitive', 'Dziś jest piąt[y] maja.'] },
            { who: 'On a date', cells: ['day and month in the genitive', 'Przyjadę piąt[ego] maja.'] },
            { who: 'Clock time', cells: ['feminine, for godzina', 'Jest trzeci[a]. Spotkajmy się o trzeci[ej].'] },
            { who: 'Floor', cells: ['locative after na', 'Mieszkam na drugi[m] piętrze.'] },
          ] },
      ],
      rules: [
        { t: 'Ordinals agree with their noun like adjectives', ex: 'To jest moja pierwsza lekcja.', en: 'This is my first lesson.' },
        { t: 'On a date, the day and the month are both in the genitive', ex: 'Urodziłem się dziesiątego czerwca.', en: 'I was born on the tenth of June.' },
        { t: 'Clock times are feminine, because they agree with godzina', ex: 'Pociąg odjeżdża o szóstej.', en: 'The train leaves at six.' },
        { t: 'After a preposition the ordinal takes that case', ex: 'Mieszkam na trzecim piętrze.', en: 'I live on the third floor.' },
      ],
      watch: [
        'Drugi and trzeci take soft endings: drugiego, drugiej, trzecim, trzeciej.',
        'In compound ordinals every word changes: dwudziesty pierwszy, dwudziestego pierwszego.',
        'Years use the ordinal too: w dwa tysiące dwudziestym piątym roku (in 2025).',
      ],
    },
    {
      id: 'num-cases', pl: 'Odmiana', en: 'Numbers in other cases', q: 'z dwoma, o pięciu',
      summary: 'Numbers change with the case too. In the genitive, dative, instrumental and locative the five-and-up rule no longer applies: the number and the noun both take the case the sentence needs. The accusative looks like the nominative, except with men.',
      tables: [
        { title: 'Two, three, five through the cases',
          cols: [{ label: '2, masc. and neuter', tint: 'm' }, { label: '2, feminine', tint: 'f' }, { label: '3 (4 the same way)', tint: 'all' }, { label: '5 (6 and up the same way)', tint: 'all' }],
          rows: [
            { who: 'Nominative', cells: ['dwa', 'dwie', 'trzy', 'pięć'] },
            { who: 'Genitive', cells: ['dw[óch]', 'dw[óch]', 'trz[ech]', 'pię[ciu]'] },
            { who: 'Dative', cells: ['dw[óm]', 'dw[óm]', 'trz[em]', 'pię[ciu]'] },
            { who: 'Accusative', cells: ['dwa (men: dwóch)', 'dwie', 'trzy (men: trzech)', 'pięć (men: pięciu)'] },
            { who: 'Instrumental', cells: ['dw[oma]', 'dw[iema]', 'trz[ema]', 'pię[cioma]'] },
            { who: 'Locative', cells: ['dw[óch]', 'dw[óch]', 'trz[ech]', 'pię[ciu]'] },
          ] },
      ],
      rules: [
        { t: 'In the instrumental the number and the noun are both instrumental', ex: 'Mieszkam z dwoma kolegami.', en: 'I live with two friends.' },
        { t: 'In the genitive the noun is genitive plural after every number', ex: 'Czekam od trzech godzin.', en: 'I have been waiting for three hours.' },
        { t: 'The same goes for the locative and the dative', ex: 'Opowiadam o pięciu miastach.', en: 'I am talking about five cities.' },
        { t: 'The accusative looks like the nominative, except with men', ex: 'Widzę dwa koty, ale znam dwóch lekarzy.', en: 'I see two cats, but I know two doctors.' },
      ],
      watch: [
        'Dwie has its own instrumental: z dwiema siostrami. Z dwoma siostrami is heard too, but dwiema is the standard.',
        'Genitive and locative of 2, 3 and 4 look the same: od dwóch, o dwóch.',
        'Pięć and higher use -ciu for almost every case, and -cioma for the instrumental: z pięcioma, z sześcioma.',
      ],
    },
  ],
  sentences: [
    // Słownie
    { c: 'num-say', at: ['1 / 11','Teens'], kind: 'number', s: '___', base: '11', gloss: 'eleven', a: ['jedenaście'], en: 'eleven', why: 'The teens add -naście to the unit. Jeden and -naście share one n: jedenaście.' },
    { c: 'num-say', at: ['4 / 14','Teens'], kind: 'number', s: '___', base: '14', gloss: 'fourteen', a: ['czternaście'], en: 'fourteen', why: 'Cztery drops its y before -naście: czternaście.' },
    { c: 'num-say', at: ['5 / 15','Teens'], kind: 'number', s: '___', base: '15', gloss: 'fifteen', a: ['piętnaście'], en: 'fifteen', why: 'Pięć turns its ć into t before -naście: piętnaście.' },
    { c: 'num-say', at: ['6 / 16','Teens'], kind: 'number', s: '___', base: '16', gloss: 'sixteen', a: ['szesnaście'], en: 'sixteen', why: 'Sześć loses its ś and ć before -naście: szesnaście.' },
    { c: 'num-say', at: ['9 / 19','Teens'], kind: 'number', s: '___', base: '19', gloss: 'nineteen', a: ['dziewiętnaście'], en: 'nineteen', why: 'Like piętnaście, dziewięć turns its ć into t: dziewiętnaście.' },
    { c: 'num-say', at: ['20 / 200','Tens'], kind: 'number', s: '___', base: '20', gloss: 'twenty', a: ['dwadzieścia'], en: 'twenty', why: 'Twenty is dwa plus -dzieścia: dwadzieścia.' },
    { c: 'num-say', at: ['30 / 300','Tens'], kind: 'number', s: '___', base: '38', gloss: 'thirty-eight', a: ['trzydzieści osiem'], en: 'thirty-eight', why: 'Thirty is trzydzieści, then the unit follows with no “and”: trzydzieści osiem.' },
    { c: 'num-say', at: ['40 / 400','Tens'], kind: 'number', s: '___', base: '44', gloss: 'forty-four', a: ['czterdzieści cztery'], en: 'forty-four', why: 'Forty drops the y of cztery: czterdzieści. The unit keeps it: cztery.' },
    { c: 'num-say', at: ['50 / 500','Tens'], kind: 'number', s: '___', base: '56', gloss: 'fifty-six', a: ['pięćdziesiąt sześć'], en: 'fifty-six', why: 'From fifty on the tens end in -dziesiąt: pięćdziesiąt sześć.' },
    { c: 'num-say', at: ['60 / 600','Tens'], kind: 'number', s: '___', base: '67', gloss: 'sixty-seven', a: ['sześćdziesiąt siedem'], en: 'sixty-seven', why: 'Sześć plus -dziesiąt, then the unit: sześćdziesiąt siedem.' },
    { c: 'num-say', at: ['70 / 700','Tens'], kind: 'number', s: '___', base: '73', gloss: 'seventy-three', a: ['siedemdziesiąt trzy'], en: 'seventy-three', why: 'Siedem plus -dziesiąt, then the unit: siedemdziesiąt trzy.' },
    { c: 'num-say', at: ['90 / 900','Tens'], kind: 'number', s: '___', base: '99', gloss: 'ninety-nine', a: ['dziewięćdziesiąt dziewięć'], en: 'ninety-nine', why: 'Dziewięć plus -dziesiąt, then the unit: dziewięćdziesiąt dziewięć.' },
    { c: 'num-say', at: ['20 / 200','Hundreds'], kind: 'number', s: '___', base: '200', gloss: 'two hundred', a: ['dwieście'], en: 'two hundred', why: 'Two hundred is irregular: dwieście, built on the feminine dwie.' },
    { c: 'num-say', at: ['30 / 300','Hundreds'], kind: 'number', s: '___', base: '340', gloss: 'three hundred and forty', a: ['trzysta czterdzieści'], en: 'three hundred and forty', why: 'Three and four hundred take -sta: trzysta. Then the tens: czterdzieści.' },
    { c: 'num-say', at: ['40 / 400','Hundreds'], kind: 'number', s: '___', base: '415', gloss: 'four hundred and fifteen', a: ['czterysta piętnaście'], en: 'four hundred and fifteen', why: 'Four hundred is czterysta, without the y of cztery. Then the teen: piętnaście.' },
    { c: 'num-say', at: ['60 / 600','Hundreds'], kind: 'number', s: '___', base: '600', gloss: 'six hundred', a: ['sześćset'], en: 'six hundred', why: 'From five hundred on the hundreds end in -set: sześćset.' },
    { c: 'num-say', at: ['90 / 900','Hundreds'], kind: 'number', s: '___', base: '950', gloss: 'nine hundred and fifty', a: ['dziewięćset pięćdziesiąt'], en: 'nine hundred and fifty', why: 'Dziewięćset for the hundreds, then pięćdziesiąt for the tens.' },
    { c: 'num-say', at: ['1000','Word'], kind: 'number', s: '___', base: '1000', gloss: 'one thousand', a: ['tysiąc', 'jeden tysiąc'], en: 'one thousand', why: 'A thousand is just tysiąc. Jeden is usually left out.' },
    { c: 'num-say', at: ['2000 to 4000','Word'], kind: 'number', s: '___', base: '3500', gloss: 'three thousand five hundred', a: ['trzy tysiące pięćset'], en: 'three thousand five hundred', why: 'After three, tysiąc takes the nominative plural: trzy tysiące. Then pięćset.' },
    { c: 'num-say', at: ['Years','Example'], kind: 'number', s: '___', base: '1989', gloss: 'nineteen eighty-nine', a: ['tysiąc dziewięćset osiemdziesiąt dziewięć'], en: 'nineteen eighty-nine', why: 'A year is read as a whole number, not in pairs: tysiąc dziewięćset osiemdziesiąt dziewięć.' },
    { c: 'num-say', at: ['30 / 300','Tens'], kind: 'number', s: 'Mam{I have} ___ lat{years|m2.pl}.', base: '35', gloss: 'thirty-five', a: ['trzydzieści pięć'], en: 'I am thirty-five.', why: 'Trzydzieści plus pięć. Five takes the genitive plural, which is why the noun is lat.' },
    { c: 'num-say', at: ['20 / 200','Hundreds'], kind: 'number', s: 'Ta{this|f} kurtka{jacket|f} kosztuje{costs} ___ złotych{zlotys|m2.pl}.', base: '250', gloss: 'two hundred and fifty', a: ['dwieście pięćdziesiąt'], en: 'This jacket costs two hundred and fifty zlotys.', why: 'Dwieście for 200, then pięćdziesiąt for 50.' },
    { c: 'num-say', at: ['10 / 100','Hundreds'], kind: 'number', s: 'Autobus{the bus|m2} numer{number|m2} ___ jedzie{goes} na{to} lotnisko{airport|n}.', base: '175', gloss: 'one hundred and seventy-five', a: ['sto siedemdziesiąt pięć'], en: 'The number 175 bus goes to the airport.', why: 'Sto, then siedemdziesiąt, then pięć, with no “and” between them.' },
    { c: 'num-say', at: ['5000 and up','Word'], kind: 'number', s: 'Ten{this|m2} samochód{car|m2} kosztował{cost} ___ złotych{zlotys|m2.pl}.', base: '8000', gloss: 'eight thousand', a: ['osiem tysięcy'], en: 'This car cost eight thousand zlotys.', why: 'From five up tysiąc takes the genitive plural: osiem tysięcy.' },

    // Dwa–cztery
    { c: 'num-2-4', at: ['2','Feminine'], form: 'noun nom.pl.f', s: 'Mam{I have} dwie{two} ___.', base: 'siostra', gloss: 'sister', a: ['siostry'], en: 'I have two sisters.', why: 'After two the noun goes into the nominative plural: siostry. Dwie is the feminine form of two.' },
    { c: 'num-2-4', at: ['3','Neuter'], form: 'noun nom.pl.n', s: 'Na{on} stole{table|m2} leżą{are lying} trzy{three} ___.', base: 'jabłko', gloss: 'apple', a: ['jabłka'], en: 'Three apples are lying on the table.', why: 'After three the noun is in the nominative plural. Neuter nouns in -o take -a: jabłka.' },
    { c: 'num-2-4', at: ['2','Feminine'], kind: 'number', s: 'Mam{I have} ___ córki{daughters|f.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwie'], en: 'I have two daughters.', why: 'Córka is feminine, so two is dwie, not dwa.' },
    { c: 'num-2-4', at: ['3','Feminine'], form: 'noun acc.pl.f', s: 'Czekam{I have been waiting} już{already} trzy{three} ___.', base: 'minuta', gloss: 'minute', a: ['minuty'], en: 'I have been waiting for three minutes already.', why: 'After three the noun takes the plural form minuty, the same as the nominative plural.' },
    { c: 'num-2-4', at: ['2','Masculine'], form: 'noun acc.pl.m2', s: 'Mój{my|m1} syn{son|m1} ma{has} dwa{two} ___.', base: 'rok', gloss: 'year', a: ['lata'], en: 'My son is two years old.', why: 'Rok has an irregular plural: dwa lata, trzy lata, cztery lata.' },
    { c: 'num-2-4', at: ['22, 23, 24','Feminine'], form: 'noun nom.pl.f', s: 'W{in} klasie{classroom|f} są{there are} dwadzieścia{twenty} dwie{two} ___.', base: 'ławka', gloss: 'desk', a: ['ławki'], en: 'There are twenty-two desks in the classroom.', why: 'Twenty-two ends in two, so the noun is in the nominative plural: ławki.' },
    { c: 'num-2-4', at: ['2','Masculine'], form: 'noun nom.pl.m2', s: 'Dwa{two} ___ szczekają{are barking} pod{under} oknem{window|n}.', base: 'pies', gloss: 'dog', a: ['psy'], en: 'Two dogs are barking under the window.', why: 'After two the noun is in the nominative plural. Pies loses its e: psy.' },
    { c: 'num-2-4', at: ['2 to 4: plural','Present'], form: 'verb present.one', s: 'Na{at} przystanku{stop|m2} ___ dwie{two} kobiety{women|f.pl}.', base: 'czekać', gloss: 'to wait', a: ['czekają'], en: 'Two women are waiting at the stop.', why: 'With two, three and four the verb is plural, just as with any plural subject: czekają.' },
    { c: 'num-2-4', at: ['2','Masculine'], form: 'noun acc.pl.m2', s: 'Kupiłem{I bought} dwa{two} ___ do{to} Gdańska{Gdańsk|m2}.', base: 'bilet', gloss: 'ticket', a: ['bilety'], en: 'I bought two tickets to Gdańsk.', why: 'After two the noun is in the nominative plural. Bilet is a masculine thing, so it takes -y: bilety.' },
    { c: 'num-2-4', at: ['4','Feminine'], form: 'noun nom.pl.f', s: 'W{in} tym{this|m2} budynku{building|m2} są{there are} cztery{four} ___.', base: 'winda', gloss: 'lift', a: ['windy'], en: 'There are four lifts in this building.', why: 'After four the noun is in the nominative plural. Feminine nouns in -a take -y: windy.' },
    { c: 'num-2-4', at: ['3','Masculine'], form: 'noun nom.pl.m2', s: 'Na{in} parkingu{car park|m2} stały{were standing} trzy{three} ___.', base: 'samochód', gloss: 'car', a: ['samochody'], en: 'Three cars were parked in the car park.', why: 'After three the noun is in the nominative plural: samochody. The verb is plural too.' },
    { c: 'num-2-4', at: ['2','Neuter'], kind: 'number', s: 'Mamy{we have} ___ nowe{new|n.pl} okna{windows|n.pl} w{in} kuchni{kitchen|f}.', base: '2', gloss: 'two', a: ['dwa'], en: 'We have two new windows in the kitchen.', why: 'Okno is neuter, and neuter nouns take dwa, not dwie.' },

    { c: 'num-2-4', at: ['1','Feminine'], kind: 'number', s: 'Mam{I have} tylko{only} ___ siostrę{sister|f}.', base: 'jeden', hint: '1', gloss: 'one', a: ['jedną'], en: 'I have only one sister.', why: 'Jeden agrees like an adjective. Siostrę is feminine accusative, so one is jedną.' },
    { c: 'num-2-4', at: ['1','Neuter'], kind: 'number', s: 'W{in} pokoju{room|m2} jest{there is} tylko{only} ___ okno{window|n}.', base: 'jeden', hint: '1', gloss: 'one', a: ['jedno'], en: 'There is only one window in the room.', why: 'Okno is neuter, so one takes the neuter form jedno.' },
    { c: 'num-2-4', at: ['2','Feminine'], kind: 'number', s: 'Zamówiliśmy{we ordered} ___ pizze{pizzas|f.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwie'], en: 'We ordered two pizzas.', why: 'Pizza is feminine, so two is dwie.' },
    { c: 'num-2-4', at: ['22, 23, 24','Feminine'], kind: 'number', s: 'W{in} grupie{group|f} są{there are} dwadzieścia{twenty} ___ studentki{students|f.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwie'], en: 'There are twenty-two female students in the group.', why: 'The last word of the number agrees with the noun. Studentki are feminine, so twenty-two ends in dwie.' },
    // Pięć i więcej
    { c: 'num-5plus', at: ['5 to 21','Feminine'], form: 'noun gen.pl.f', s: 'Mam{I have} pięć{five} ___.', base: 'książka', gloss: 'book', a: ['książek'], en: 'I have five books.', why: 'From five up the noun takes the genitive plural. Książka drops its ending and an e slips in: książek.' },
    { c: 'num-5plus', at: ['5 to 21','Masculine'], form: 'noun gen.pl.m2', s: 'W{in} tym{this|n} mieście{town|n} jest{there are} sześć{six} ___.', base: 'kościół', gloss: 'church', a: ['kościołów'], en: 'There are six churches in this town.', why: 'After six the noun is in the genitive plural. Masculine nouns usually take -ów: kościołów.' },
    { c: 'num-5plus', at: ['5 to 21','Neuter'], form: 'noun gen.pl.n', s: 'Kupiłam{I bought} dziesięć{ten} ___.', base: 'jajko', gloss: 'egg', a: ['jajek'], en: 'I bought ten eggs.', why: 'After ten the noun takes the genitive plural. Jajko has no ending there and an e slips in: jajek.' },
    { c: 'num-5plus', at: ['Quantity words','Feminine'], form: 'noun gen.pl.f', s: 'Na{at} imprezie{party|f} było{there were} dużo{a lot of} ___.', base: 'osoba', gloss: 'person', a: ['osób'], en: 'There were a lot of people at the party.', why: 'Dużo works like five and up, so the noun is genitive plural: osób.' },
    { c: 'num-5plus', at: ['Quantity words','Neuter'], form: 'noun gen.pl.n', s: 'Ile{how many} ___ jest{are there} w{in} tym{this|m2} pokoju{room|m2}?', base: 'krzesło', gloss: 'chair', a: ['krzeseł'], en: 'How many chairs are there in this room?', why: 'Ile takes the genitive plural. Krzesło loses its ending and an e slips in: krzeseł.' },
    { c: 'num-5plus', at: ['25, 31, 100','Masculine'], form: 'noun gen.pl.m2', s: 'Moja{my|f} babcia{grandma|f} ma{has} osiemdziesiąt{eighty} ___.', base: 'rok', gloss: 'year', a: ['lat'], en: 'My grandma is eighty years old.', why: 'From five up rok uses the genitive plural lat: osiemdziesiąt lat.' },
    { c: 'num-5plus', at: ['5 and up: singular','Past'], form: 'verb past.ono', s: 'W{in} autobusie{bus|m2} ___ siedem{seven} kobiet{women|f.pl}.', base: 'jechać', gloss: 'to ride', a: ['jechało'], en: 'Seven women were riding on the bus.', why: 'With five and up the verb is singular, and in the past tense it takes the neuter -o: jechało.' },
    { c: 'num-5plus', at: ['5 and up: singular','Past'], form: 'verb past.ono', s: 'Wczoraj{yesterday} ___ pięć{five} listów{letters|m2.pl}.', base: 'przyjść', gloss: 'to come', a: ['przyszło'], en: 'Five letters came yesterday.', why: 'After five the past-tense verb is neuter singular: przyszło.' },
    { c: 'num-5plus', at: ['5 to 21','Masculine'], form: 'noun gen.pl.m2', s: 'Ten{this|m2} pociąg{train|m2} ma{has} osiem{eight} ___.', base: 'wagon', gloss: 'carriage', a: ['wagonów'], en: 'This train has eight carriages.', why: 'From five up the noun takes the genitive plural. Masculine nouns usually take -ów: wagonów.' },
    { c: 'num-5plus', at: ['Quantity words','Feminine'], form: 'noun gen.pl.f', s: 'Zostało{remained} mi{to me} tylko{only} kilka{a few} ___.', base: 'minuta', gloss: 'minute', a: ['minut'], en: 'I only have a few minutes left.', why: 'Kilka follows the five-and-up rule, so the noun is genitive plural: minut. The verb is neuter singular, zostało.' },
    { c: 'num-5plus', at: ['12, 13, 14','Masculine'], form: 'noun gen.pl.m2', s: 'Na{in} drzewie{tree|n} siedzi{is sitting} dwanaście{twelve} ___.', base: 'ptak', gloss: 'bird', a: ['ptaków'], en: 'Twelve birds are sitting in the tree.', why: 'Twelve ends in -naście, so it follows the five-and-up rule: genitive plural ptaków and a singular verb.' },
    { c: 'num-5plus', at: ['25, 31, 100','Feminine'], form: 'noun gen.pl.f', s: 'W{in} tej{this|f} klasie{class|f} jest{there are} dwadzieścia{twenty} jeden{one} ___.', base: 'uczennica', gloss: 'schoolgirl', a: ['uczennic'], en: 'There are twenty-one girls in this class.', why: 'Numbers ending in 1, except 1 itself, take the genitive plural: uczennic.' },

    // Mężczyźni
    { c: 'num-men', at: ['2','Everyday form: genitive plural, verb singular'], form: 'noun gen.pl.m1', s: 'W{in} poczekalni{waiting room|f} czeka{is waiting} dwóch{two} ___.', base: 'lekarz', gloss: 'doctor', a: ['lekarzy'], en: 'Two doctors are waiting in the waiting room.', why: 'Dwóch is the form for men, and it takes the genitive plural: lekarzy.' },
    { c: 'num-men', at: ['5 and up','Everyday form: genitive plural, verb singular'], form: 'noun gen.pl.m1', s: 'Na{to} imprezę{party|f} przyszło{came} pięciu{five} ___.', base: 'kolega', gloss: 'friend', a: ['kolegów'], en: 'Five friends came to the party.', why: 'Pięciu is used for men and takes the genitive plural: kolegów.' },
    { c: 'num-men', at: ['3','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'Mam{I have} ___ braci{brothers|m1.pl}.', base: 'trzy', hint: '3', gloss: 'three', a: ['trzech'], en: 'I have three brothers.', why: 'Brothers are men, so three is trzech, with the genitive plural braci.' },
    { c: 'num-men', at: ['2','Also correct: nominative plural, verb plural'], kind: 'number', s: '___ policjanci{policemen|m1.pl} stali{were standing} przed{in front of} bankiem{bank|m2}.', base: 'dwa', hint: '2', gloss: 'two', a: ['Dwaj'], en: 'Two policemen were standing in front of the bank.', why: 'Policjanci is nominative plural and the verb is plural, so the number must be dwaj.' },
    { c: 'num-men', at: ['5 and up','Everyday form: genitive plural, verb singular'], form: 'verb past.ono', s: 'Na{to} mecz{match|m2} ___ sześciu{six} chłopców{boys|m1.pl}.', base: 'przyjść', gloss: 'to come', a: ['przyszło'], en: 'Six boys came to the match.', why: 'With sześciu and the genitive plural the verb is singular, neuter in the past: przyszło.' },
    { c: 'num-men', at: ['4','Also correct: nominative plural, verb plural'], form: 'verb past.oni', s: 'Czterej{four} kelnerzy{waiters|m1.pl} ___ bardzo{very} szybko{quickly}.', base: 'pracować', gloss: 'to work', a: ['pracowali'], en: 'Four waiters were working very fast.', why: 'Czterej takes the nominative plural and a plural verb. For men the past plural ends in -li: pracowali.' },
    { c: 'num-men', at: ['Some, many, how many','Everyday form: genitive plural, verb singular'], form: 'noun gen.pl.m1', s: 'Ilu{how many} ___ pracuje{works} w{in} twoim{your|n} biurze{office|n}?', base: 'mężczyzna', gloss: 'man', a: ['mężczyzn'], en: 'How many men work in your office?', why: 'Ilu is the form for men and takes the genitive plural: mężczyzn.' },
    { c: 'num-men', at: ['Some, many, how many','Everyday form: genitive plural, verb singular'], form: 'noun gen.pl.m1', s: 'Znam{I know} kilku{a few} ___ z{from} pracy{work|f}.', base: 'Anglik', gloss: 'Englishman', a: ['Anglików'], en: 'I know a few Englishmen from work.', why: 'Kilku is used for men and takes the genitive plural: Anglików.' },
    { c: 'num-men', at: ['5 and up','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'W{in} autobusie{bus|m2} siedziało{were sitting} ___ żołnierzy{soldiers|m1.pl}.', base: 'siedem', hint: '7', gloss: 'seven', a: ['siedmiu'], en: 'Seven soldiers were sitting on the bus.', why: 'Soldiers are men, so seven takes its men form, siedmiu.' },
    { c: 'num-men', at: ['Some, many, how many','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'Na{at} spotkaniu{meeting|n} było{there were} ___ nauczycieli{teachers|m1.pl}.', base: 'wiele', hint: 'many', gloss: 'many', a: ['wielu'], en: 'There were many teachers at the meeting.', why: 'With men (or a mixed group) wiele becomes wielu.' },
    { c: 'num-men', at: ['3','Also correct: nominative plural, verb plural'], form: 'noun nom.pl.m1', s: 'Trzej{three} ___ grali{were playing} w{at} piłkę{ball|f} na{in} podwórku{yard|n}.', base: 'chłopiec', gloss: 'boy', a: ['chłopcy'], en: 'Three boys were playing football in the yard.', why: 'Trzej takes the nominative plural: chłopcy. The verb is plural too.' },
    { c: 'num-men', at: ['4','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'Do{to} kina{cinema|n} poszło{went} ___ przyjaciół{friends|m1.pl}.', base: 'cztery', hint: '4', gloss: 'four', a: ['czterech'], en: 'Four friends went to the cinema.', why: 'Przyjaciół is genitive plural and the verb is neuter singular, so the number is the men form czterech.' },

    { c: 'num-men', at: ['5 and up','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'W{in} drużynie{team|f} gra{plays} ___ piłkarzy{footballers|m1.pl}.', base: 'jedenaście', hint: '11', gloss: 'eleven', a: ['jedenastu'], en: 'Eleven footballers play in a team.', why: 'Footballers are men, so eleven takes its men form: jedenastu.' },
    { c: 'num-men', at: ['Some, many, how many','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'Na{at} przystanku{stop|m2} czekało{were waiting} ___ mężczyzn{men|m1.pl}.', base: 'kilka', hint: 'a few', gloss: 'a few', a: ['kilku'], en: 'A few men were waiting at the stop.', why: 'With men kilka becomes kilku.' },
    { c: 'num-men', at: ['Some, many, how many','Everyday form: genitive plural, verb singular'], kind: 'number', s: '___ masz{do you have} braci{brothers|m1.pl}?', base: 'ile', hint: 'how many', gloss: 'how many', a: ['Ilu'], en: 'How many brothers do you have?', why: 'Brothers are men, so ile becomes ilu.' },
    { c: 'num-men', at: ['2','Also correct: nominative plural, verb plural'], kind: 'number', s: '___ synowie{sons|m1.pl} pracują{work} w{in} Anglii{England|f}.', base: 'dwa', hint: '2', gloss: 'two', a: ['Dwaj'], en: 'Two sons work in England.', why: 'Synowie is nominative plural and the verb is plural, so two takes the form dwaj.' },
    { c: 'num-men', at: ['5 and up','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'W{in} biurze{office|n} pracuje{work} ___ informatyków{IT specialists|m1.pl}.', base: 'osiem', hint: '8', gloss: 'eight', a: ['ośmiu'], en: 'Eight IT specialists work in the office.', why: 'For men osiem becomes ośmiu, with ś as in the other cases.' },
    { c: 'num-men', at: ['2','Everyday form: genitive plural, verb singular'], kind: 'number', s: 'Na{to} wykład{lecture|m2} przyszło{came} tylko{only} ___ studentów{students|m1.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwóch'], en: 'Only two students came to the lecture.', why: 'Studentów is genitive plural and the verb is neuter singular, so two takes the men form dwóch.' },
    // Porządkowe
    { c: 'num-ordinal', at: ['Floor','Example'], kind: 'number', form: 'adj loc.sg.n', s: 'Mieszkam{I live} na{on} ___ piętrze{floor|n}.', base: 'piąty', hint: '5th', gloss: 'fifth', a: ['piątym'], en: 'I live on the fifth floor.', why: 'Na with a place takes the locative. Piętro is neuter, so the ordinal ends in -ym: piątym.' },
    { c: 'num-ordinal', at: ['On a date','Example'], kind: 'number', form: 'adj gen.sg.m2', s: 'Egzamin{the exam|m2} mam{I have} ___ czerwca{of June|m2}.', base: 'trzeci', hint: '3rd', gloss: 'third', a: ['trzeciego'], en: 'I have the exam on the third of June.', why: 'On a date the day is in the genitive. Trzeci takes the soft ending: trzeciego.' },
    { c: 'num-ordinal', at: ['On a date','Example'], kind: 'number', form: 'adj gen.sg.m2', s: 'Urodziłam{I was born} się{(reflexive)} ___ marca{of March|m2}.', base: 'drugi', hint: '2nd', gloss: 'second', a: ['drugiego'], en: 'I was born on the second of March.', why: 'On a date the day is in the genitive. Drugi takes the soft ending: drugiego.' },
    { c: 'num-ordinal', at: ['Clock time','Example'], kind: 'number', form: 'adj loc.sg.f', s: 'Spotkajmy{let\'s meet} się{(reflexive)} o{at} ___.', base: 'ósmy', hint: '8:00', gloss: 'eighth', a: ['ósmej'], en: 'Let\'s meet at eight.', why: 'Clock times are feminine because of godzina. O takes the locative: o ósmej.' },
    { c: 'num-ordinal', at: ['Clock time','Example'], kind: 'number', form: 'adj nom.sg.f', s: 'Jest{it is} już{already} ___.', base: 'siódmy', hint: '7:00', gloss: 'seventh', a: ['siódma'], en: 'It\'s already seven o\'clock.', why: 'Telling the time uses the feminine nominative, agreeing with godzina: siódma.' },
    { c: 'num-ordinal', at: ['1st','Feminine'], kind: 'number', form: 'adj nom.sg.f', s: 'To{this} jest{is} moja{my|f} ___ podróż{trip|f} do{to} Polski{Poland|f}.', base: 'pierwszy', hint: '1st', gloss: 'first', a: ['pierwsza'], en: 'This is my first trip to Poland.', why: 'Podróż is feminine, so the ordinal takes the feminine ending: pierwsza.' },
    { c: 'num-ordinal', at: ['3rd','Masculine'], kind: 'number', form: 'adj loc.sg.m2', s: 'Siedzieliśmy{we sat} w{in} ___ rzędzie{row|m2}.', base: 'trzeci', hint: '3rd', gloss: 'third', a: ['trzecim'], en: 'We sat in the third row.', why: 'W with a place takes the locative. Trzeci is soft, so it becomes trzecim.' },
    { c: 'num-ordinal', at: ['4th, 5th, 6th','Feminine'], kind: 'number', form: 'adj gen.sg.f', s: 'Mój{my|m1} syn{son|m1} chodzi{goes} do{to} ___ klasy{class|f}.', base: 'czwarty', hint: '4th', gloss: 'fourth', a: ['czwartej'], en: 'My son is in fourth grade.', why: 'Do takes the genitive and klasa is feminine, so the ordinal is czwartej.' },
    { c: 'num-ordinal', at: ['7th, 8th, 9th, 10th','Masculine'], kind: 'number', form: 'adj gen.sg.m2', s: 'Nie{not} widziałem{I have seen} ___ odcinka{episode|m2}.', base: 'dziewiąty', hint: '9th', gloss: 'ninth', a: ['dziewiątego'], en: 'I haven\'t seen the ninth episode.', why: 'After a negated verb the object is in the genitive, so the ordinal takes -ego: dziewiątego.' },
    { c: 'num-ordinal', at: ['3rd','Neuter'], kind: 'number', form: 'adj nom.sg.n', s: 'To{this} jest{is} nasze{our|n} ___ dziecko{child|n}.', base: 'trzeci', hint: '3rd', gloss: 'third', a: ['trzecie'], en: 'This is our third child.', why: 'Dziecko is neuter, and trzeci takes the soft neuter ending: trzecie.' },
    { c: 'num-ordinal', at: ['Clock time','Example'], kind: 'number', form: 'adj loc.sg.f', s: 'Wróciłem{I came back} do{to} domu{home|m2} po{after} ___.', base: 'dziesiąty', hint: '10:00', gloss: 'tenth', a: ['dziesiątej'], en: 'I came home after ten.', why: 'Clock times are feminine. Po takes the locative: po dziesiątej.' },
    { c: 'num-ordinal', at: ['20th, 100th','Masculine'], kind: 'number', form: 'adj loc.sg.m2', s: 'Mój{my|m1} dziadek{grandfather|m1} urodził{was born} się{(reflexive)} w{in} tysiąc{one thousand} dziewięćset{nine hundred} ___ roku{year|m2}.', base: 'pięćdziesiąty', hint: '1950', gloss: 'fiftieth', a: ['pięćdziesiątym'], en: 'My grandfather was born in 1950.', why: 'Years use the ordinal. W with roku takes the locative, so the last word is pięćdziesiątym.' },

    { c: 'num-ordinal', at: ['On a date','Example'], kind: 'number', form: 'adj gen.sg.m2', s: 'Wyjeżdżamy{we are leaving} ___ sierpnia{of August|m2}.', base: 'piętnasty', hint: '15th', gloss: 'fifteenth', a: ['piętnastego'], en: 'We are leaving on the fifteenth of August.', why: 'On a date the day is in the genitive, so the ordinal takes -ego: piętnastego.' },
    { c: 'num-ordinal', at: ['Clock time','Example'], kind: 'number', form: 'adj loc.sg.f', s: 'Lekcja{the lesson|f} zaczyna{starts} się{(reflexive)} o{at} ___.', base: 'dziewiąty', hint: '9:00', gloss: 'ninth', a: ['dziewiątej'], en: 'The lesson starts at nine.', why: 'Clock times are feminine, and o takes the locative: o dziewiątej.' },
    { c: 'num-ordinal', at: ['2nd','Masculine'], kind: 'number', form: 'adj loc.sg.m2', s: 'Wysiądź{get off} na{at} ___ przystanku{stop|m2}.', base: 'drugi', hint: '2nd', gloss: 'second', a: ['drugim'], en: 'Get off at the second stop.', why: 'Na with a place takes the locative. Drugi is soft, so it becomes drugim.' },
    // Odmiana
    { c: 'num-cases', at: ['Instrumental','2, feminine'], kind: 'number', s: 'Mieszkam{I live} z{with} ___ siostrami{sisters|f.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwiema', 'dwoma'], en: 'I live with my two sisters.', why: 'Z takes the instrumental. For feminine nouns the standard form of two is dwiema.' },
    { c: 'num-cases', at: ['Instrumental','3 (4 the same way)'], form: 'noun ins.pl.m1', s: 'Rozmawiałem{I talked} z{with} trzema{three} ___.', base: 'sąsiad', gloss: 'neighbour', a: ['sąsiadami'], en: 'I talked to three neighbours.', why: 'After z both the number and the noun are instrumental: trzema sąsiadami.' },
    { c: 'num-cases', at: ['Genitive','5 (6 and up the same way)'], kind: 'number', s: 'Zadzwoniłem{I called} do{to} ___ firm{companies|f.pl}.', base: 'pięć', hint: '5', gloss: 'five', a: ['pięciu'], en: 'I called five companies.', why: 'Do takes the genitive, and the genitive of pięć is pięciu.' },
    { c: 'num-cases', at: ['Locative','2, feminine'], kind: 'number', s: 'Opowiadała{she was talking} o{about} ___ podróżach{trips|f.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwóch'], en: 'She was talking about two trips.', why: 'O takes the locative. The locative of two is dwóch for every gender.' },
    { c: 'num-cases', at: ['Dative','3 (4 the same way)'], form: 'noun dat.pl.f', s: 'Pomagam{I help} trzem{three} ___.', base: 'sąsiadka', gloss: 'neighbour', a: ['sąsiadkom'], en: 'I help three neighbours.', why: 'Pomagać takes the dative, so both words are dative: trzem sąsiadkom.' },
    { c: 'num-cases', at: ['Dative','2, masc. and neuter'], kind: 'number', s: 'Wysłałem{I sent} zdjęcia{photos|n.pl} ___ kolegom{friends|m1.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwóm'], en: 'I sent the photos to two friends.', why: 'Kolegom is dative, so the number is dative too: dwóm.' },
    { c: 'num-cases', at: ['Instrumental','5 (6 and up the same way)'], form: 'noun ins.pl.f', s: 'Jadę{I am travelling} z{with} pięcioma{five} ___.', base: 'walizka', gloss: 'suitcase', a: ['walizkami'], en: 'I am travelling with five suitcases.', why: 'In the instrumental the five-and-up rule no longer applies: pięcioma walizkami, both instrumental.' },
    { c: 'num-cases', at: ['Instrumental','3 (4 the same way)'], kind: 'number', s: 'Szukam{I am looking for} mieszkania{flat|n} z{with} ___ pokojami{rooms|m2.pl}.', base: 'trzy', hint: '3', gloss: 'three', a: ['trzema'], en: 'I am looking for a flat with three rooms.', why: 'Z takes the instrumental, and the instrumental of trzy is trzema.' },
    { c: 'num-cases', at: ['Genitive','3 (4 the same way)'], form: 'noun gen.pl.n', s: 'Brakuje{are missing} nam{to us} czterech{four} ___.', base: 'krzesło', gloss: 'chair', a: ['krzeseł'], en: 'We are four chairs short.', why: 'Brakować takes the genitive, so the noun is genitive plural after czterech: krzeseł.' },
    { c: 'num-cases', at: ['Accusative','2, masc. and neuter'], kind: 'number', s: 'Widzę{I see} ___ policjantów{policemen|m1.pl} przed{in front of} sklepem{shop|m2}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwóch'], en: 'I see two policemen in front of the shop.', why: 'In the accusative men take the genitive-looking form: dwóch policjantów.' },
    { c: 'num-cases', at: ['Accusative','2, feminine'], form: 'noun acc.pl.f', s: 'Zaprosiłam{I invited} dwie{two} ___ na{for} kawę{coffee|f}.', base: 'koleżanka', gloss: 'friend', a: ['koleżanki'], en: 'I invited two friends for coffee.', why: 'The accusative looks like the nominative when the noun is not a man: dwie koleżanki.' },
    { c: 'num-cases', at: ['Locative','5 (6 and up the same way)'], form: 'noun loc.pl.m2', s: 'Byłem{I have been} w{in} sześciu{six} ___ Europy{of Europe|f}.', base: 'kraj', gloss: 'country', a: ['krajach'], en: 'I have been to six European countries.', why: 'W with a place takes the locative, so the noun is locative plural after sześciu: krajach.' },
    { c: 'num-cases', at: ['Instrumental','2, masc. and neuter'], kind: 'number', s: 'Idę{I am going} na{for} spacer{a walk|m2} z{with} ___ psami{dogs|m1.pl}.', base: 'dwa', hint: '2', gloss: 'two', a: ['dwoma'], en: 'I am going for a walk with two dogs.', why: 'Z takes the instrumental. For masculine and neuter nouns two becomes dwoma.' },
    { c: 'num-cases', at: ['Dative','3 (4 the same way)'], kind: 'number', s: 'Czytam{I read} bajki{fairy tales|f.pl} ___ dzieciom{children|n.pl}.', base: 'trzy', hint: '3', gloss: 'three', a: ['trzem'], en: 'I read fairy tales to three children.', why: 'Dzieciom is dative, so three is dative too: trzem.' },
    { c: 'num-cases', at: ['Genitive','3 (4 the same way)'], kind: 'number', s: 'Na{at} lekcji{lesson|f} nie{not} było{there were} ___ uczniów{pupils|m1.pl}.', base: 'cztery', hint: '4', gloss: 'four', a: ['czterech'], en: 'Four pupils were missing from the lesson.', why: 'Nie było takes the genitive, and the genitive of cztery is czterech.' },
    { c: 'num-cases', at: ['Locative','5 (6 and up the same way)'], kind: 'number', s: 'Mieszkaliśmy{we lived} w{in} ___ krajach{countries|m2.pl}.', base: 'pięć', hint: '5', gloss: 'five', a: ['pięciu'], en: 'We have lived in five countries.', why: 'W with a place takes the locative, and the locative of pięć is pięciu.' },
    { c: 'num-cases', at: ['Instrumental','3 (4 the same way)'], kind: 'number', s: 'Szukamy{we are looking for} domu{house|m2} z{with} ___ sypialniami{bedrooms|f.pl}.', base: 'cztery', hint: '4', gloss: 'four', a: ['czterema'], en: 'We are looking for a house with four bedrooms.', why: 'Z takes the instrumental, and the instrumental of cztery is czterema.' },
    { c: 'num-cases', at: ['Genitive','5 (6 and up the same way)'], kind: 'number', s: 'Poproszę{I would like} stolik{a table|m2} dla{for} ___ osób{people|f.pl}.', base: 'sześć', hint: '6', gloss: 'six', a: ['sześciu'], en: 'A table for six, please.', why: 'Dla takes the genitive, and the genitive of sześć is sześciu.' },
  ],
};
