/* Idioms: fun, common Polish idioms, practised through their endings. Same format as data-numbers.js.
   Each group has one table: the idiom (who), what it says literally, and what it means.
   In sentences, word{gloss} gives the hover translation and ___ is the gap.
   Sentences have no p (person); at points to the idiom's row and the Meaning column.
   Check with: node validate.js data-idioms.js IDIOMS */

const IDIOMS = {
  id: 'idioms', pl: 'Idiomy', en: 'Idioms',
  intro: 'Polish idioms are full of flies, horses, raspberries and snakes. They are fixed phrases, but the words inside them still change their endings: the verb follows the person and tense, and the nouns keep the case the preposition asks for. Learn each idiom in its dictionary form, then practise putting it into a real sentence.',
  groups: [
    {
      id: 'idiom-mood', pl: 'Nastroje', en: 'Moods and annoyance', q: 'mieć muchy w nosie',
      summary: 'Idioms for bad moods, anger, being fed up and, now and then, being very happy. Most of them are built around a body part (nose, foot, nerves) and a preposition that fixes the case.',
      tables: [
        { title: 'Moods and annoyance',
          cols: [{ label: 'Literally', tint: 'all' }, { label: 'Meaning', tint: 'all' }],
          rows: [
            { who: 'mieć muchy w nosie', cells: ['to have flies in your nose', 'to be in a bad mood, to sulk'] },
            { who: 'wstać lewą nogą', cells: ['to get up with the left foot', 'to get out of bed on the wrong side'] },
            { who: 'działać komuś na nerwy', cells: ['to act on somebody\'s nerves', 'to get on somebody\'s nerves'] },
            { who: 'mieć czegoś po dziurki w nosie', cells: ['to have something up to the holes in your nose', 'to be fed up with something'] },
            { who: 'krew kogoś zalewa', cells: ['blood floods somebody', 'somebody is furious'] },
            { who: 'wyjść z siebie', cells: ['to come out of yourself', 'to lose your temper'] },
            { who: 'być w siódmym niebie', cells: ['to be in the seventh heaven', 'to be over the moon'] },
            { who: 'nie mój cyrk, nie moje małpy', cells: ['not my circus, not my monkeys', 'not my problem'] },
            { who: 'mieć ciche dni', cells: ['to have quiet days', 'to not be speaking to each other after a quarrel'] },
          ] },
      ],
      rules: [
        { t: 'W with a place takes the locative, so nos becomes nosie', ex: 'Szef ma dziś muchy w nosie.', en: 'The boss is in a bad mood today.' },
        { t: 'Wstać lewą nogą is almost always in the past tense', ex: 'Chyba wstałeś dziś lewą nogą.', en: 'You must have got out of bed on the wrong side today.' },
        { t: 'Działać na nerwy takes the dative for the person and the accusative plural nerwy', ex: 'Ten hałas działa mi na nerwy.', en: 'This noise is getting on my nerves.' },
        { t: 'Po dziurki w nosie takes the genitive for the thing you are fed up with', ex: 'Mam tego po dziurki w nosie.', en: 'I am sick and tired of it.' },
      ],
      watch: [
        'In krew kogoś zalewa the angry person is the object (accusative): krew mnie zalewa, krew go zalała.',
        'Wyjść z siebie keeps siebie for every person: wyszłam z siebie, wyszli z siebie.',
        'Nie mój cyrk, nie moje małpy is a fixed saying; only moje changes if you say twój: nie twój cyrk, nie twoje małpy.',
      ],
    },
    {
      id: 'idiom-lies', pl: 'Kłamstwa', en: 'Lying and fooling people', q: 'robić kogoś w konia',
      summary: 'Idioms for lying, cheating and taking people for a ride. Polish lets you turn someone into a horse, lead them into the raspberries or stuff them into a bottle, and the person being fooled is always in the accusative.',
      tables: [
        { title: 'Lying and fooling people',
          cols: [{ label: 'Literally', tint: 'all' }, { label: 'Meaning', tint: 'all' }],
          rows: [
            { who: 'robić kogoś w konia', cells: ['to make somebody into a horse', 'to fool somebody, to pull a fast one'] },
            { who: 'wpuścić kogoś w maliny', cells: ['to let somebody into the raspberries', 'to trick somebody, to lead them up the garden path'] },
            { who: 'nabić kogoś w butelkę', cells: ['to stuff somebody into a bottle', 'to take somebody for a ride'] },
            { who: 'wciskać komuś kit', cells: ['to push putty on somebody', 'to feed somebody a lie'] },
            { who: 'wyssać coś z palca', cells: ['to suck something out of your finger', 'to make something up'] },
            { who: 'mydlić komuś oczy', cells: ['to soap somebody\'s eyes', 'to pull the wool over somebody\'s eyes'] },
            { who: 'zrobić kogoś na szaro', cells: ['to make somebody grey', 'to cheat somebody out of money'] },
            { who: 'kłamać jak z nut', cells: ['to lie as if from sheet music', 'to lie smoothly, without blinking'] },
            { who: 'wodzić kogoś za nos', cells: ['to lead somebody by the nose', 'to string somebody along'] },
          ] },
      ],
      rules: [
        { t: 'The person who gets fooled is in the accusative', ex: 'Zrobili mnie w konia.', en: 'They made a fool of me.' },
        { t: 'W with movement into something takes the accusative', ex: 'Wpuścił nas w maliny.', en: 'He led us up the garden path.' },
        { t: 'Dać się + infinitive means to let yourself be fooled', ex: 'Dałem się nabić w butelkę.', en: 'I let myself be taken for a ride.' },
        { t: 'After nie the object goes into the genitive', ex: 'Nie wciskaj mi kitu!', en: 'Don\'t feed me that nonsense!' },
      ],
      watch: [
        'Koń is a living thing, so its accusative looks like the genitive: w konia, not w koń.',
        'Oko has an irregular plural: oczy, and in the genitive oczu (nie mydl mi oczu).',
        'Wyssać is perfective: wyssał z palca. The idiom is almost always in the past.',
      ],
    },
    {
      id: 'idiom-easy', pl: 'Łatwe i trudne', en: 'Easy and hard', q: 'bułka z masłem',
      summary: 'Idioms for things that are a piece of cake and things that are an uphill struggle. Butter shows up twice: a roll with butter is easy, and going as if over butter means everything runs smoothly.',
      tables: [
        { title: 'Easy and hard',
          cols: [{ label: 'Literally', tint: 'all' }, { label: 'Meaning', tint: 'all' }],
          rows: [
            { who: 'bułka z masłem', cells: ['a bread roll with butter', 'a piece of cake'] },
            { who: 'iść jak po maśle', cells: ['to go as if over butter', 'to go smoothly'] },
            { who: 'iść jak po grudzie', cells: ['to go as if over frozen clods', 'to go slowly and with difficulty'] },
            { who: 'mieć pod górkę', cells: ['to have it uphill', 'to have a hard time'] },
            { who: 'z górki', cells: ['downhill', 'easy from now on'] },
            { who: 'szukać igły w stogu siana', cells: ['to look for a needle in a haystack', 'to look for something almost impossible to find'] },
            { who: 'mieć coś w małym palcu', cells: ['to have something in your little finger', 'to know something inside out'] },
            { who: 'rzucić się na głęboką wodę', cells: ['to throw yourself into deep water', 'to take the plunge'] },
            { who: 'wysoko zawiesić poprzeczkę', cells: ['to hang the bar high', 'to set high standards'] },
          ] },
      ],
      rules: [
        { t: 'Z meaning with takes the instrumental', ex: 'To bułka z masłem.', en: 'It\'s a piece of cake.' },
        { t: 'Po in these comparisons takes the locative: masło becomes maśle', ex: 'Wszystko poszło jak po maśle.', en: 'Everything went smoothly.' },
        { t: 'Pod górkę takes the accusative, z górki the genitive', ex: 'Teraz już będzie z górki.', en: 'It will be easy from now on.' },
        { t: 'Na with movement onto something takes the accusative', ex: 'Rzuciłam się na głęboką wodę.', en: 'I took the plunge.' },
      ],
      watch: [
        'Masło changes its consonant in the locative: masło, po maśle.',
        'Iść jak po maśle is usually in the past with the perfective pójść: poszło jak po maśle.',
        'Palec loses its e in other cases: w małym palcu, z palca.',
      ],
    },
    {
      id: 'idiom-money', pl: 'Pieniądze', en: 'Money', q: 'mieć węża w kieszeni',
      summary: 'Idioms for being stingy, broke, rich or ripped off. A stingy person has a snake in their pocket, a broke one has not a single grosz, and something very expensive costs as much as at the chemist\'s.',
      tables: [
        { title: 'Money',
          cols: [{ label: 'Literally', tint: 'all' }, { label: 'Meaning', tint: 'all' }],
          rows: [
            { who: 'mieć węża w kieszeni', cells: ['to have a snake in your pocket', 'to be stingy'] },
            { who: 'nie mieć ani grosza', cells: ['to not have a single grosz', 'to be broke'] },
            { who: 'klepać biedę', cells: ['to pat poverty', 'to scrape by, to be poor'] },
            { who: 'wiązać koniec z końcem', cells: ['to tie end with end', 'to make ends meet'] },
            { who: 'zbić fortunę', cells: ['to beat a fortune', 'to make a fortune'] },
            { who: 'zapłacić jak za zboże', cells: ['to pay as if for grain', 'to pay through the nose'] },
            { who: 'drogo jak w aptece', cells: ['as expensive as at the chemist\'s', 'very expensive'] },
            { who: 'puścić kogoś z torbami', cells: ['to send somebody off with bags', 'to ruin somebody financially'] },
            { who: 'żyć na cudzy koszt', cells: ['to live at someone else\'s cost', 'to sponge off other people'] },
          ] },
      ],
      rules: [
        { t: 'Wąż is a living thing, so its accusative looks like the genitive: węża', ex: 'On ma węża w kieszeni.', en: 'He is stingy.' },
        { t: 'After nie mieć the object goes into the genitive', ex: 'Nie mam ani grosza.', en: 'I am completely broke.' },
        { t: 'Z meaning with takes the instrumental', ex: 'Ledwo wiążemy koniec z końcem.', en: 'We can barely make ends meet.' },
        { t: 'W with a place takes the locative', ex: 'Tu jest drogo jak w aptece.', en: 'It\'s very expensive here.' },
      ],
      watch: [
        'Wąż changes its vowel in the other cases: wąż, węża, wężem.',
        'Kieszeń is feminine and soft: w kieszeni.',
        'Koniec loses its e: koniec, końca, z końcem.',
      ],
    },
    {
      id: 'idiom-talk', pl: 'Gadanie', en: 'Talking nonsense', q: 'owijać w bawełnę',
      summary: 'Idioms about how people talk: beating around the bush, waffling, talking nonstop, talking to a brick wall, or speaking bluntly. One is about the listener: someone who fell off a Christmas tree has no idea what is going on.',
      tables: [
        { title: 'Talking nonsense',
          cols: [{ label: 'Literally', tint: 'all' }, { label: 'Meaning', tint: 'all' }],
          rows: [
            { who: 'owijać w bawełnę', cells: ['to wrap in cotton', 'to beat around the bush'] },
            { who: 'gadać jak dziad do obrazu', cells: ['to talk like a beggar to a holy picture', 'to talk to a brick wall'] },
            { who: 'z choinki się urwać', cells: ['to have fallen off a Christmas tree', 'to be clueless, to not know what is going on'] },
            { who: 'pleść trzy po trzy', cells: ['to weave three by three', 'to talk nonsense'] },
            { who: 'gadać jak najęty', cells: ['to talk like someone hired', 'to talk nonstop'] },
            { who: 'trzymać język za zębami', cells: ['to hold your tongue behind your teeth', 'to keep your mouth shut'] },
            { who: 'mówić prosto z mostu', cells: ['to speak straight from the bridge', 'to speak bluntly'] },
            { who: 'lać wodę', cells: ['to pour water', 'to waffle, to pad with empty words'] },
            { who: 'wziąć kogoś za język', cells: ['to take somebody by the tongue', 'to get information out of somebody'] },
          ] },
      ],
      rules: [
        { t: 'W with movement into something takes the accusative', ex: 'Nie owijaj w bawełnę.', en: 'Don\'t beat around the bush.' },
        { t: 'Z meaning from takes the genitive', ex: 'Z choinki się urwałeś?', en: 'Where have you been? (literally: did you fall off a Christmas tree?)' },
        { t: 'Za meaning behind takes the instrumental', ex: 'Trzymaj język za zębami.', en: 'Keep your mouth shut.' },
        { t: 'Najęty agrees with the speaker like an adjective', ex: 'Ona gada jak najęta.', en: 'She talks nonstop.' },
      ],
      watch: [
        'Pleść has an irregular past: plótł, plotła, pletli.',
        'Ząb changes its vowel: ząb, zęby, za zębami.',
        'Lać has the present leję, lejesz, leje, the same verb as in leje jak z cebra (it\'s pouring).',
      ],
    },
  ],
  sentences: [
    // Nastroje
    { c: 'idiom-mood', at: ['mieć muchy w nosie','Meaning'], s: 'Szef{the boss|m1} ma{has} dziś{today} muchy{flies|f.pl} w{in} ___.', base: 'nos', gloss: 'nose', a: ['nosie'], en: 'The boss is in a bad mood today.', why: 'Mieć muchy w nosie means to be in a bad mood. W with a place takes the locative: nosie.' },
    { c: 'idiom-mood', at: ['mieć muchy w nosie','Meaning'], s: 'Nie{don\'t} rozmawiaj{talk} z{with} nim{him}, on{he} ma{has} dziś{today} ___ w{in} nosie{nose|m2}.', base: 'mucha', gloss: 'fly', a: ['muchy'], en: 'Don\'t talk to him, he\'s in a foul mood today.', why: 'Mieć muchy w nosie means to be in a bad mood. The flies are the object of mieć, in the accusative plural: muchy.' },
    { c: 'idiom-mood', at: ['wstać lewą nogą','Meaning'], s: 'Marek{Marek|m1} chyba{must have} ___ dziś{today} lewą{left|f} nogą{foot|f}.', base: 'wstać', gloss: 'to get up', a: ['wstał'], en: 'Marek must have got out of bed on the wrong side today.', why: 'Wstać lewą nogą means to be grumpy from the start of the day. Marek is a man, so the past tense is wstał.' },
    { c: 'idiom-mood', at: ['działać komuś na nerwy','Meaning'], s: 'Ten{this|m2} hałas{noise|m2} działa{acts} mi{on me} na{on} ___.', base: 'nerw', gloss: 'nerve', a: ['nerwy'], en: 'This noise is getting on my nerves.', why: 'Działać komuś na nerwy means to annoy somebody. Na with this verb takes the accusative plural: nerwy.' },
    { c: 'idiom-mood', at: ['działać komuś na nerwy','Meaning'], s: 'Jego{his} ciągłe{constant} spóźnienia{lateness|n.pl} ___ mi{on me} na{on} nerwy{nerves|m2.pl}.', base: 'działać', gloss: 'to act', a: ['działają'], en: 'His constant lateness gets on my nerves.', why: 'Działać komuś na nerwy means to annoy somebody. The subject spóźnienia is plural, so the verb is działają.' },
    { c: 'idiom-mood', at: ['mieć czegoś po dziurki w nosie','Meaning'], s: 'Mam{I have} już{already} tej{this|f} ___ po{up to} dziurki{holes|f.pl} w{in} nosie{nose|m2}.', base: 'praca', gloss: 'job', a: ['pracy'], en: 'I\'m fed up with this job.', why: 'Mieć czegoś po dziurki w nosie means to be fed up with something. The thing you are fed up with is in the genitive: pracy.' },
    { c: 'idiom-mood', at: ['krew kogoś zalewa','Meaning'], s: 'Kiedy{when} to{this} usłyszałam{I heard}, krew{blood|f} mnie{me} ___.', base: 'zalać', gloss: 'to flood', a: ['zalała'], en: 'When I heard that, I was furious.', why: 'Krew kogoś zalewa means somebody is furious. The subject is krew, which is feminine, so the past tense is zalała.' },
    { c: 'idiom-mood', at: ['wyjść z siebie','Meaning'], s: 'Mama{mum|f} ___ z{out of} siebie{herself}, kiedy{when} zobaczyła{she saw} bałagan{the mess|m2}.', base: 'wyjść', gloss: 'to come out', a: ['wyszła'], en: 'Mum lost her temper when she saw the mess.', why: 'Wyjść z siebie means to lose your temper. Mama is feminine, and the past of wyjść is irregular: wyszła.' },
    { c: 'idiom-mood', at: ['być w siódmym niebie','Meaning'], s: 'Po{after} tej{this|f} wiadomości{news|f} Ania{Ania|f} była{was} w{in} siódmym{seventh|n} ___.', base: 'niebo', gloss: 'heaven', a: ['niebie'], en: 'After that news Ania was over the moon.', why: 'Być w siódmym niebie means to be extremely happy. W with a place takes the locative: niebie.' },
    { c: 'idiom-mood', at: ['nie mój cyrk, nie moje małpy','Meaning'], s: 'Niech{let} sami{themselves} to{it} załatwią{sort out}. Nie{not} mój{my|m2} cyrk{circus|m2}, nie{not} moje{my} ___.', base: 'małpa', gloss: 'monkey', a: ['małpy'], en: 'Let them sort it out themselves. Not my problem.', why: 'Nie mój cyrk, nie moje małpy means it is not my problem. Małpy is the nominative plural of małpa.' },
    { c: 'idiom-mood', at: ['mieć ciche dni','Meaning'], s: 'Moi{my} rodzice{parents|m1.pl} mają{are having} teraz{now} ciche{quiet} ___.', base: 'dzień', gloss: 'day', a: ['dni'], en: 'My parents aren\'t speaking to each other at the moment.', why: 'Mieć ciche dni means not to speak to each other after a quarrel. Dzień has an irregular plural: dni.' },

    // Kłamstwa
    { c: 'idiom-lies', at: ['robić kogoś w konia','Meaning'], s: 'Sprzedawca{the salesman|m1} zrobił{made} mnie{me} w{into} ___.', base: 'koń', gloss: 'horse', a: ['konia'], en: 'The salesman made a fool of me.', why: 'Robić kogoś w konia means to fool somebody. W with movement takes the accusative, and for a living masculine noun it looks like the genitive: konia.' },
    { c: 'idiom-lies', at: ['robić kogoś w konia','Meaning'], s: 'Nie{don\'t} ___ mnie{me} w{into} konia{horse|m1}!', base: 'robić', gloss: 'to make', a: ['rób'], en: 'Don\'t try to fool me!', why: 'Robić kogoś w konia means to fool somebody. This is a command to one person, so robić becomes rób.' },
    { c: 'idiom-lies', at: ['wpuścić kogoś w maliny','Meaning'], s: 'Ten{this|m1} facet{guy|m1} wpuścił{let} nas{us} w{into} ___.', base: 'malina', gloss: 'raspberry', a: ['maliny'], en: 'That guy led us up the garden path.', why: 'Wpuścić kogoś w maliny means to trick somebody. W with movement takes the accusative, here plural: maliny.' },
    { c: 'idiom-lies', at: ['nabić kogoś w butelkę','Meaning'], s: 'Znowu{again} dałem{I let} się{myself} nabić{stuff} w{into} ___.', base: 'butelka', gloss: 'bottle', a: ['butelkę'], en: 'I let myself be taken for a ride again.', why: 'Nabić kogoś w butelkę means to fool somebody. W with movement takes the accusative: butelkę.' },
    { c: 'idiom-lies', at: ['wciskać komuś kit','Meaning'], s: 'On{he} zawsze{always} ___ ludziom{people} kit{putty|m2}.', base: 'wciskać', gloss: 'to push', a: ['wciska'], en: 'He is always feeding people lies.', why: 'Wciskać komuś kit means to lie to somebody. On takes the third person singular: wciska.' },
    { c: 'idiom-lies', at: ['wciskać komuś kit','Meaning'], s: 'Nie{don\'t} wciskaj{push} mi{on me} ___!', base: 'kit', gloss: 'putty', a: ['kitu'], en: 'Don\'t feed me that nonsense!', why: 'Wciskać komuś kit means to lie to somebody. After nie the object goes into the genitive: kitu.' },
    { c: 'idiom-lies', at: ['wyssać coś z palca','Meaning'], s: 'Dziennikarz{the journalist|m1} wyssał{sucked} tę{this|f} historię{story|f} z{out of} ___.', base: 'palec', gloss: 'finger', a: ['palca'], en: 'The journalist made that story up.', why: 'Wyssać coś z palca means to make something up. Z meaning out of takes the genitive, and palec loses its e: palca.' },
    { c: 'idiom-lies', at: ['mydlić komuś oczy','Meaning'], s: 'Politycy{politicians|m1.pl} ___ nam{us} oczy{eyes|n.pl} pięknymi{fine} obietnicami{promises|f.pl}.', base: 'mydlić', gloss: 'to soap', a: ['mydlą'], en: 'Politicians pull the wool over our eyes with fine promises.', why: 'Mydlić komuś oczy means to deceive somebody. The subject politycy is plural, so the verb is mydlą.' },
    { c: 'idiom-lies', at: ['mydlić komuś oczy','Meaning'], s: 'Przestań{stop}, nie{don\'t} mydl{soap} mi{my} ___!', base: 'oko', gloss: 'eye', a: ['oczu'], en: 'Stop it, don\'t try to deceive me!', why: 'Mydlić komuś oczy means to deceive somebody. After nie the object goes into the genitive, and oko has the irregular genitive plural oczu.' },
    { c: 'idiom-lies', at: ['zrobić kogoś na szaro','Meaning'], s: 'Ta{this|f} firma{company|f} ___ klientów{customers|m1.pl} na{into} szaro{grey}.', base: 'zrobić', gloss: 'to make', a: ['zrobiła'], en: 'This company cheated its customers.', why: 'Zrobić kogoś na szaro means to cheat somebody out of money. Firma is feminine, so the past tense is zrobiła.' },
    { c: 'idiom-lies', at: ['kłamać jak z nut','Meaning'], s: 'Ona{she} kłamie{lies} jak{as if} z{from} ___.', base: 'nuta', gloss: 'note (music)', a: ['nut'], en: 'She lies without batting an eyelid.', why: 'Kłamać jak z nut means to lie smoothly. Z meaning from takes the genitive, and the genitive plural of nuta has no ending: nut.' },
    { c: 'idiom-lies', at: ['wodzić kogoś za nos','Meaning'], s: 'Ona{she} ___ go{him} za{by} nos{the nose|m2} od{for} miesięcy{months|m2.pl}.', base: 'wodzić', gloss: 'to lead', a: ['wodzi'], en: 'She has been stringing him along for months.', why: 'Wodzić kogoś za nos means to string somebody along. Ona takes the third person singular: wodzi.' },

    // Łatwe i trudne
    { c: 'idiom-easy', at: ['bułka z masłem','Meaning'], s: 'Ten{this|m2} egzamin{exam|m2} to{was} bułka{a roll|f} z{with} ___.', base: 'masło', gloss: 'butter', a: ['masłem'], en: 'That exam is a piece of cake.', why: 'Bułka z masłem means something very easy. Z meaning with takes the instrumental: masłem.' },
    { c: 'idiom-easy', at: ['bułka z masłem','Meaning'], s: 'Naprawa{fixing|f} tego{this|m2} kranu{tap|m2} to{is} dla{for} ___ bułka{a roll|f} z{with} masłem{butter|n}.', base: 'ja', gloss: 'I', a: ['mnie'], en: 'Fixing this tap is a piece of cake for me.', why: 'Bułka z masłem means something very easy. Dla takes the genitive, and the genitive of ja is mnie.' },
    { c: 'idiom-easy', at: ['iść jak po maśle','Meaning'], s: 'Remont{the renovation|m2} poszedł{went} jak{as if} po{over} ___.', base: 'masło', gloss: 'butter', a: ['maśle'], en: 'The renovation went smoothly.', why: 'Iść jak po maśle means to go smoothly. Po here takes the locative, and masło changes to maśle.' },
    { c: 'idiom-easy', at: ['iść jak po maśle','Meaning'], s: 'Na{luckily} szczęście{fortune|n} wszystko{everything|n} ___ jak{as if} po{over} maśle{butter|n}.', base: 'pójść', gloss: 'to go', a: ['poszło'], en: 'Luckily everything went smoothly.', why: 'Iść jak po maśle means to go smoothly. Wszystko is neuter, so the past tense of pójść is poszło.' },
    { c: 'idiom-easy', at: ['iść jak po grudzie','Meaning'], s: 'Rozmowy{the talks|f.pl} ___ jak{as if} po{over} grudzie{frozen clods|f}.', base: 'iść', gloss: 'to go', a: ['szły'], en: 'The talks were slow and difficult.', why: 'Iść jak po grudzie means to go slowly and with difficulty. Rozmowy is a plural of things, so the past tense of iść is szły.' },
    { c: 'idiom-easy', at: ['mieć pod górkę','Meaning'], s: 'Nowi{new|m1.pl} pracownicy{employees|m1.pl} zawsze{always} ___ pod{up} górkę{the hill|f}.', base: 'mieć', gloss: 'to have', a: ['mają'], en: 'New employees always have a hard time.', why: 'Mieć pod górkę means to have a hard time. The subject is plural, so mieć becomes mają.' },
    { c: 'idiom-easy', at: ['z górki','Meaning'], s: 'Najgorsze{the worst} już{already} za{behind} nami{us}, teraz{now} będzie{it will be} z{down} ___.', base: 'górka', gloss: 'hill', a: ['górki'], en: 'The worst is behind us, it will be easy from now on.', why: 'Z górki means easy from now on. Z meaning from or down takes the genitive: górki.' },
    { c: 'idiom-easy', at: ['szukać igły w stogu siana','Meaning'], s: 'Szukanie{looking for} kluczy{keys|m2.pl} w{in} tym{this|m2} bałaganie{mess|m2} to{is} jak{like} szukanie{looking for} ___ w{in} stogu{stack|m2} siana{of hay|n}.', base: 'igła', gloss: 'needle', a: ['igły'], en: 'Looking for keys in this mess is like looking for a needle in a haystack.', why: 'Szukać igły w stogu siana means to look for something almost impossible to find. Szukać takes the genitive: igły.' },
    { c: 'idiom-easy', at: ['mieć coś w małym palcu','Meaning'], s: 'Ona{she} ma{has} gramatykę{grammar|f} w{in} małym{little|m2} ___.', base: 'palec', gloss: 'finger', a: ['palcu'], en: 'She knows grammar inside out.', why: 'Mieć coś w małym palcu means to know something perfectly. W with a place takes the locative, and palec loses its e: palcu.' },
    { c: 'idiom-easy', at: ['rzucić się na głęboką wodę','Meaning'], s: 'Po{after} przeprowadzce{the move|f} do{to} Polski{Poland|f} rzuciłem{I threw} się{myself} na{into} głęboką{deep|f} ___.', base: 'woda', gloss: 'water', a: ['wodę'], en: 'After moving to Poland I took the plunge.', why: 'Rzucić się na głęboką wodę means to take the plunge. Na with movement takes the accusative: wodę.' },
    { c: 'idiom-easy', at: ['wysoko zawiesić poprzeczkę','Meaning'], s: 'Nasz{our|m1} trener{coach|m1} wysoko{high} ___ poprzeczkę{the bar|f}.', base: 'zawiesić', gloss: 'to hang', a: ['zawiesił'], en: 'Our coach has set high standards.', why: 'Wysoko zawiesić poprzeczkę means to set high standards. Trener is a man, so the past tense is zawiesił.' },

    // Pieniądze
    { c: 'idiom-money', at: ['mieć węża w kieszeni','Meaning'], s: 'Mój{my|m1} wujek{uncle|m1} ma{has} węża{a snake|m1} w{in} ___.', base: 'kieszeń', gloss: 'pocket', a: ['kieszeni'], en: 'My uncle is stingy.', why: 'Mieć węża w kieszeni means to be stingy. W with a place takes the locative: kieszeni.' },
    { c: 'idiom-money', at: ['mieć węża w kieszeni','Meaning'], s: 'Nie{don\'t} bądź{be} taki{so} skąpy{stingy}! Masz{do you have} ___ w{in} kieszeni{pocket|f}?', base: 'wąż', gloss: 'snake', a: ['węża'], en: 'Don\'t be so stingy! Are you afraid to spend money?', why: 'Mieć węża w kieszeni means to be stingy. Wąż is a living thing, so its accusative looks like the genitive, and the vowel changes: węża.' },
    { c: 'idiom-money', at: ['nie mieć ani grosza','Meaning'], s: 'Pod{at} koniec{the end|m2} miesiąca{of the month|m2} nie{not} mam{I have} ani{a single} ___.', base: 'grosz', gloss: 'grosz (penny)', a: ['grosza'], en: 'At the end of the month I am completely broke.', why: 'Nie mieć ani grosza means to be broke. After nie mieć the object goes into the genitive: grosza.' },
    { c: 'idiom-money', at: ['klepać biedę','Meaning'], s: 'Po{after} studiach{university} Tomek{Tomek|m1} przez{for} rok{a year|m2} ___ biedę{poverty|f}.', base: 'klepać', gloss: 'to pat', a: ['klepał'], en: 'After university Tomek scraped by for a year.', why: 'Klepać biedę means to be poor. Tomek is a man, so the past tense is klepał.' },
    { c: 'idiom-money', at: ['wiązać koniec z końcem','Meaning'], s: 'Wiele{many} rodzin{families|f.pl} ledwo{barely} wiąże{ties} koniec{end|m2} z{with} ___.', base: 'koniec', gloss: 'end', a: ['końcem'], en: 'Many families can barely make ends meet.', why: 'Wiązać koniec z końcem means to make ends meet. Z meaning with takes the instrumental, and koniec loses its e: końcem.' },
    { c: 'idiom-money', at: ['zbić fortunę','Meaning'], s: 'Jej{her} dziadek{grandfather|m1} zbił{beat} ___ na{on} nieruchomościach{property|f.pl}.', base: 'fortuna', gloss: 'fortune', a: ['fortunę'], en: 'Her grandfather made a fortune in property.', why: 'Zbić fortunę means to get rich. The fortune is the object, in the accusative: fortunę.' },
    { c: 'idiom-money', at: ['zapłacić jak za zboże','Meaning'], s: 'Za{for} naprawę{the repair|f} samochodu{of the car|m2} ___ jak{as if} za{for} zboże{grain|n}.', base: 'zapłacić', hint: 'we', gloss: 'to pay', a: ['zapłaciliśmy'], en: 'We paid through the nose for the car repair.', why: 'Zapłacić jak za zboże means to pay far too much. For we in the past tense the verb takes -liśmy: zapłaciliśmy.' },
    { c: 'idiom-money', at: ['drogo jak w aptece','Meaning'], s: 'W{in} tej{this|f} restauracji{restaurant|f} jest{it is} drogo{expensive} jak{as} w{in} ___.', base: 'apteka', gloss: 'pharmacy', a: ['aptece'], en: 'This restaurant is really expensive.', why: 'Drogo jak w aptece means very expensive. W with a place takes the locative, and k changes to c: aptece.' },
    { c: 'idiom-money', at: ['puścić kogoś z torbami','Meaning'], s: 'Ten{this|m2} rozwód{divorce|m2} puścił{sent} go{him} z{with} ___.', base: 'torba', gloss: 'bag', a: ['torbami'], en: 'That divorce ruined him financially.', why: 'Puścić kogoś z torbami means to ruin somebody. Z meaning with takes the instrumental plural: torbami.' },
    { c: 'idiom-money', at: ['puścić kogoś z torbami','Meaning'], s: 'Hazard{gambling|m2} puścił{sent} jego{his} ___ z{with} torbami{bags|f.pl}.', base: 'rodzina', gloss: 'family', a: ['rodzinę'], en: 'Gambling ruined his family.', why: 'Puścić kogoś z torbami means to ruin somebody. The person ruined is the object, in the accusative: rodzinę.' },
    { c: 'idiom-money', at: ['żyć na cudzy koszt','Meaning'], s: 'Mój{my|m1} brat{brother|m1} wciąż{still} ___ na{at} cudzy{someone else\'s|m2} koszt{expense|m2}.', base: 'żyć', gloss: 'to live', a: ['żyje'], en: 'My brother still sponges off other people.', why: 'Żyć na cudzy koszt means to live off other people\'s money. Brat takes the third person singular: żyje.' },

    // Gadanie
    { c: 'idiom-talk', at: ['owijać w bawełnę','Meaning'], s: 'Nie{don\'t} owijaj{wrap} w{in} ___, powiedz{tell} prawdę{the truth|f}.', base: 'bawełna', gloss: 'cotton', a: ['bawełnę'], en: 'Don\'t beat around the bush, tell the truth.', why: 'Owijać w bawełnę means to avoid saying something directly. W with movement takes the accusative: bawełnę.' },
    { c: 'idiom-talk', at: ['owijać w bawełnę','Meaning'], s: 'Dlaczego{why} zawsze{always} ___ w{in} bawełnę{cotton|f}?', base: 'owijać', hint: 'you', gloss: 'to wrap', a: ['owijasz'], en: 'Why do you always beat around the bush?', why: 'Owijać w bawełnę means to avoid saying something directly. For ty the verb ends in -sz: owijasz.' },
    { c: 'idiom-talk', at: ['gadać jak dziad do obrazu','Meaning'], s: 'Mówię{I talk} do{to} niego{him} jak{like} dziad{a beggar|m1} do{to} ___.', base: 'obraz', gloss: 'picture', a: ['obrazu'], en: 'Talking to him is like talking to a brick wall.', why: 'Gadać jak dziad do obrazu means to talk to someone who does not listen. Do takes the genitive: obrazu.' },
    { c: 'idiom-talk', at: ['z choinki się urwać','Meaning'], s: 'Czy{(question)} ty{you} z{from} ___ się{yourself} urwałeś{broke off}?', base: 'choinka', gloss: 'Christmas tree', a: ['choinki'], en: 'Where have you been? Don\'t you know anything?', why: 'Z choinki się urwać means to have no idea what is going on. Z meaning from takes the genitive: choinki.' },
    { c: 'idiom-talk', at: ['z choinki się urwać','Meaning'], s: 'Kasia{Kasia|f} chyba{must have} się{herself} ___ z{from} choinki{Christmas tree|f}, nic{nothing} nie{not} wie{she knows} o{about} ślubie{the wedding|m2}.', base: 'urwać', gloss: 'to break off', a: ['urwała'], en: 'Kasia must be completely clueless, she knows nothing about the wedding.', why: 'Z choinki się urwać means to have no idea what is going on. Kasia is a woman, so the past tense is urwała.' },
    { c: 'idiom-talk', at: ['pleść trzy po trzy','Meaning'], s: 'Po{after} dwóch{two} piwach{beers|n.pl} Marek{Marek|m1} ___ trzy{three} po{by} trzy{three}.', base: 'pleść', gloss: 'to weave', a: ['plótł'], en: 'After two beers Marek was talking nonsense.', why: 'Pleść trzy po trzy means to talk nonsense. Pleść has an irregular past: for a man it is plótł.' },
    { c: 'idiom-talk', at: ['gadać jak najęty','Meaning'], s: 'Ona{she} gadała{talked} jak{like} ___ przez{for} całą{the whole|f} podróż{journey|f}.', base: 'najęty', gloss: 'hired', a: ['najęta'], en: 'She talked nonstop the whole journey.', why: 'Gadać jak najęty means to talk nonstop. Najęty agrees with the speaker, and ona is feminine: najęta.' },
    { c: 'idiom-talk', at: ['trzymać język za zębami','Meaning'], s: 'To{this} tajemnica{is a secret|f}, więc{so} trzymaj{hold} język{your tongue|m2} za{behind} ___.', base: 'ząb', gloss: 'tooth', a: ['zębami'], en: 'It\'s a secret, so keep your mouth shut.', why: 'Trzymać język za zębami means to keep quiet. Za meaning behind takes the instrumental plural, and ą changes to ę: zębami.' },
    { c: 'idiom-talk', at: ['mówić prosto z mostu','Meaning'], s: 'Powiem{I\'ll tell} ci{you} prosto{straight} z{from} ___: to{this} zły{bad|m2} pomysł{idea|m2}.', base: 'most', gloss: 'bridge', a: ['mostu'], en: 'I\'ll tell you straight: it\'s a bad idea.', why: 'Mówić prosto z mostu means to speak bluntly. Z meaning from takes the genitive: mostu.' },
    { c: 'idiom-talk', at: ['lać wodę','Meaning'], s: 'Ten{this|m1} polityk{politician|m1} tylko{only} ___ wodę{water|f}.', base: 'lać', gloss: 'to pour', a: ['leje'], en: 'That politician just waffles.', why: 'Lać wodę means to talk a lot without saying anything. Lać has the present stem lej-, so on is leje.' },
    { c: 'idiom-talk', at: ['lać wodę','Meaning'], s: 'W{in} tym{this|n} wypracowaniu{essay|n} jest{there is} za{too} dużo{much} lania{pouring|n} ___.', base: 'woda', gloss: 'water', a: ['wody'], en: 'There is too much waffle in this essay.', why: 'Lać wodę means to waffle. After the noun lanie the object goes into the genitive: lania wody.' },
    { c: 'idiom-talk', at: ['wziąć kogoś za język','Meaning'], s: 'Policjanci{the police officers|m1.pl} ___ go{him} za{by} język{the tongue|m2} i{and} wszystko{everything} powiedział{he told}.', base: 'wziąć', gloss: 'to take', a: ['wzięli'], en: 'The police officers got him talking and he told them everything.', why: 'Wziąć kogoś za język means to get information out of somebody. Policjanci are men, so the past plural is wzięli.' },
  ],
};
