/* Other small words with their own forms in each case: demonstratives, question words, quantifiers and indefinites.
   Companion to PRONOUNS in data.js. */

// Words that agree with a noun in gender and number. Six forms per case, in this order:
// [masculine animate, masculine inanimate, neuter, feminine, plural with men, other plural]
const SMALL_WORDS = [
  { word: 'tamten', en: 'that (over there)', note: 'Points further away than ten: ten dom tu, tamten dom tam. Unlike tę, the feminine accusative is the regular tamtą.',
    forms: {
      nom: ['tamten', 'tamten', 'tamto', 'tamta', 'tamci', 'tamte'],
      gen: ['tamtego', 'tamtego', 'tamtego', 'tamtej', 'tamtych', 'tamtych'],
      dat: ['tamtemu', 'tamtemu', 'tamtemu', 'tamtej', 'tamtym', 'tamtym'],
      acc: ['tamtego', 'tamten', 'tamto', 'tamtą', 'tamtych', 'tamte'],
      ins: ['tamtym', 'tamtym', 'tamtym', 'tamtą', 'tamtymi', 'tamtymi'],
      loc: ['tamtym', 'tamtym', 'tamtym', 'tamtej', 'tamtych', 'tamtych'],
      voc: ['tamten', 'tamten', 'tamto', 'tamta', 'tamci', 'tamte'],
    } },
  { word: 'który', en: 'which, who (relative)', note: 'As a relative it takes the gender and number of the noun it refers to, and the case its own clause needs: kobieta, która…, ludzie, z którymi…',
    forms: {
      nom: ['który', 'który', 'które', 'która', 'którzy', 'które'],
      gen: ['którego', 'którego', 'którego', 'której', 'których', 'których'],
      dat: ['któremu', 'któremu', 'któremu', 'której', 'którym', 'którym'],
      acc: ['którego', 'który', 'które', 'którą', 'których', 'które'],
      ins: ['którym', 'którym', 'którym', 'którą', 'którymi', 'którymi'],
      loc: ['którym', 'którym', 'którym', 'której', 'których', 'których'],
      voc: ['który', 'który', 'które', 'która', 'którzy', 'które'],
    } },
  { word: 'jaki', en: 'what kind of, what… like', note: 'Asks about kind or quality and expects an adjective in reply: Jaki jest ten film? Dobry. Compare który, which picks one out of a set.',
    forms: {
      nom: ['jaki', 'jaki', 'jakie', 'jaka', 'jacy', 'jakie'],
      gen: ['jakiego', 'jakiego', 'jakiego', 'jakiej', 'jakich', 'jakich'],
      dat: ['jakiemu', 'jakiemu', 'jakiemu', 'jakiej', 'jakim', 'jakim'],
      acc: ['jakiego', 'jaki', 'jakie', 'jaką', 'jakich', 'jakie'],
      ins: ['jakim', 'jakim', 'jakim', 'jaką', 'jakimi', 'jakimi'],
      loc: ['jakim', 'jakim', 'jakim', 'jakiej', 'jakich', 'jakich'],
      voc: ['jaki', 'jaki', 'jakie', 'jaka', 'jacy', 'jakie'],
    } },
  { word: 'taki', en: 'such, so', note: 'Pairs with jaki: Jaki ojciec, taki syn. Before an adjective it means so: taki duży dom, taka miła osoba.',
    forms: {
      nom: ['taki', 'taki', 'takie', 'taka', 'tacy', 'takie'],
      gen: ['takiego', 'takiego', 'takiego', 'takiej', 'takich', 'takich'],
      dat: ['takiemu', 'takiemu', 'takiemu', 'takiej', 'takim', 'takim'],
      acc: ['takiego', 'taki', 'takie', 'taką', 'takich', 'takie'],
      ins: ['takim', 'takim', 'takim', 'taką', 'takimi', 'takimi'],
      loc: ['takim', 'takim', 'takim', 'takiej', 'takich', 'takich'],
      voc: ['taki', 'taki', 'takie', 'taka', 'tacy', 'takie'],
    } },
  { word: 'czyj', en: 'whose', note: 'Agrees with the thing owned, not the owner: Czyja to torba? Czyje są te klucze? Declines like mój.',
    forms: {
      nom: ['czyj', 'czyj', 'czyje', 'czyja', 'czyi', 'czyje'],
      gen: ['czyjego', 'czyjego', 'czyjego', 'czyjej', 'czyich', 'czyich'],
      dat: ['czyjemu', 'czyjemu', 'czyjemu', 'czyjej', 'czyim', 'czyim'],
      acc: ['czyjego', 'czyj', 'czyje', 'czyją', 'czyich', 'czyje'],
      ins: ['czyim', 'czyim', 'czyim', 'czyją', 'czyimi', 'czyimi'],
      loc: ['czyim', 'czyim', 'czyim', 'czyjej', 'czyich', 'czyich'],
      voc: ['czyj', 'czyj', 'czyje', 'czyja', 'czyi', 'czyje'],
    } },
  { word: 'jakiś', en: 'some, some kind of', note: 'Jaki plus -ś. The case ending sits before the ś: jakiegoś, jakiejś, jakimś. Ktoś and coś work the same way.',
    forms: {
      nom: ['jakiś', 'jakiś', 'jakieś', 'jakaś', 'jacyś', 'jakieś'],
      gen: ['jakiegoś', 'jakiegoś', 'jakiegoś', 'jakiejś', 'jakichś', 'jakichś'],
      dat: ['jakiemuś', 'jakiemuś', 'jakiemuś', 'jakiejś', 'jakimś', 'jakimś'],
      acc: ['jakiegoś', 'jakiś', 'jakieś', 'jakąś', 'jakichś', 'jakieś'],
      ins: ['jakimś', 'jakimś', 'jakimś', 'jakąś', 'jakimiś', 'jakimiś'],
      loc: ['jakimś', 'jakimś', 'jakimś', 'jakiejś', 'jakichś', 'jakichś'],
      voc: ['jakiś', 'jakiś', 'jakieś', 'jakaś', 'jacyś', 'jakieś'],
    } },
  { word: 'każdy, wszyscy', en: 'every; all', note: 'Każdy is singular only. In the plural Polish says all instead: wszyscy for a group with men, wszystkie for everything else. Każdy student, wszyscy studenci.',
    forms: {
      nom: ['każdy', 'każdy', 'każde', 'każda', 'wszyscy', 'wszystkie'],
      gen: ['każdego', 'każdego', 'każdego', 'każdej', 'wszystkich', 'wszystkich'],
      dat: ['każdemu', 'każdemu', 'każdemu', 'każdej', 'wszystkim', 'wszystkim'],
      acc: ['każdego', 'każdy', 'każde', 'każdą', 'wszystkich', 'wszystkie'],
      ins: ['każdym', 'każdym', 'każdym', 'każdą', 'wszystkimi', 'wszystkimi'],
      loc: ['każdym', 'każdym', 'każdym', 'każdej', 'wszystkich', 'wszystkich'],
      voc: ['każdy', 'każdy', 'każde', 'każda', 'wszyscy', 'wszystkie'],
    } },
  { word: 'żaden', en: 'no, none, not any', note: 'Always goes with a negated verb: Nie mam żadnych pytań. Żaden student nie przyszedł. The e of żaden drops before an ending.',
    forms: {
      nom: ['żaden', 'żaden', 'żadne', 'żadna', 'żadni', 'żadne'],
      gen: ['żadnego', 'żadnego', 'żadnego', 'żadnej', 'żadnych', 'żadnych'],
      dat: ['żadnemu', 'żadnemu', 'żadnemu', 'żadnej', 'żadnym', 'żadnym'],
      acc: ['żadnego', 'żaden', 'żadne', 'żadną', 'żadnych', 'żadne'],
      ins: ['żadnym', 'żadnym', 'żadnym', 'żadną', 'żadnymi', 'żadnymi'],
      loc: ['żadnym', 'żadnym', 'żadnym', 'żadnej', 'żadnych', 'żadnych'],
      voc: ['żaden', 'żaden', 'żadne', 'żadna', 'żadni', 'żadne'],
    } },
  { word: 'jeden', en: 'one, a certain', note: 'Declines like ten, with the short nominative jeden, jedno, jedna. The plural means some or a certain: jedni ludzie, jedne drzwi (doors is plural in Polish).',
    forms: {
      nom: ['jeden', 'jeden', 'jedno', 'jedna', 'jedni', 'jedne'],
      gen: ['jednego', 'jednego', 'jednego', 'jednej', 'jednych', 'jednych'],
      dat: ['jednemu', 'jednemu', 'jednemu', 'jednej', 'jednym', 'jednym'],
      acc: ['jednego', 'jeden', 'jedno', 'jedną', 'jednych', 'jedne'],
      ins: ['jednym', 'jednym', 'jednym', 'jedną', 'jednymi', 'jednymi'],
      loc: ['jednym', 'jednym', 'jednym', 'jednej', 'jednych', 'jednych'],
      voc: ['jeden', 'jeden', 'jedno', 'jedna', 'jedni', 'jedne'],
    } },
  { word: 'sam', en: 'alone, oneself, the very', note: 'Short nominative sam, sama, samo, not samy. Sam w domu (alone), sama to zrobiłam (myself), w samym centrum (the very centre).',
    forms: {
      nom: ['sam', 'sam', 'samo', 'sama', 'sami', 'same'],
      gen: ['samego', 'samego', 'samego', 'samej', 'samych', 'samych'],
      dat: ['samemu', 'samemu', 'samemu', 'samej', 'samym', 'samym'],
      acc: ['samego', 'sam', 'samo', 'samą', 'samych', 'same'],
      ins: ['samym', 'samym', 'samym', 'samą', 'samymi', 'samymi'],
      loc: ['samym', 'samym', 'samym', 'samej', 'samych', 'samych'],
      voc: ['sam', 'sam', 'samo', 'sama', 'sami', 'same'],
    } },
  { word: 'cały', en: 'whole, all (of one thing)', note: 'Declines like an adjective. Very common in time phrases in the accusative: cały dzień, całą noc, całe lato, przez cały rok.',
    forms: {
      nom: ['cały', 'cały', 'całe', 'cała', 'cali', 'całe'],
      gen: ['całego', 'całego', 'całego', 'całej', 'całych', 'całych'],
      dat: ['całemu', 'całemu', 'całemu', 'całej', 'całym', 'całym'],
      acc: ['całego', 'cały', 'całe', 'całą', 'całych', 'całe'],
      ins: ['całym', 'całym', 'całym', 'całą', 'całymi', 'całymi'],
      loc: ['całym', 'całym', 'całym', 'całej', 'całych', 'całych'],
      voc: ['cały', 'cały', 'całe', 'cała', 'cali', 'całe'],
    } },
  { word: 'inny', en: 'other, different', note: 'Declines like an adjective and often stands alone for other people: inni mówią, z innymi, dla innych.',
    forms: {
      nom: ['inny', 'inny', 'inne', 'inna', 'inni', 'inne'],
      gen: ['innego', 'innego', 'innego', 'innej', 'innych', 'innych'],
      dat: ['innemu', 'innemu', 'innemu', 'innej', 'innym', 'innym'],
      acc: ['innego', 'inny', 'inne', 'inną', 'innych', 'inne'],
      ins: ['innym', 'innym', 'innym', 'inną', 'innymi', 'innymi'],
      loc: ['innym', 'innym', 'innym', 'innej', 'innych', 'innych'],
      voc: ['inny', 'inny', 'inne', 'inna', 'inni', 'inne'],
    } },
];

// Words that behave like kto / co: one form per case, and optionally a different form after a preposition.
// [plain form] or [plain form, form after a preposition]. Only gen, dat, acc, ins, loc are needed.
const SMALL_WORDS_PERSONAL = [
  { word: 'ktoś', en: 'someone', gen: ['kogoś'], dat: ['komuś'], acc: ['kogoś'], ins: ['kimś'], loc: ['kimś'] },
  { word: 'coś', en: 'something', gen: ['czegoś'], dat: ['czemuś'], acc: ['coś'], ins: ['czymś'], loc: ['czymś'] },
  { word: 'wszystko', en: 'everything', gen: ['wszystkiego'], dat: ['wszystkiemu'], acc: ['wszystko'], ins: ['wszystkim'], loc: ['wszystkim'] },
];
